// mamekit knowledge graph — driver src/mame/taito/qix.cpp
// generated 2026-09-05T03:50:27.831Z
CREATE CONSTRAINT mamekit_id IF NOT EXISTS FOR (n:KG) REQUIRE n.id IS UNIQUE;
MERGE (n:KG {id: 'file:src/mame/taito/qix.cpp'}) SET n:SourceFile SET n += {path: 'src/mame/taito/qix.cpp'};
MERGE (n:KG {id: 'file:emu.h'}) SET n:SourceFile SET n += {path: 'emu.h', external: true};
MERGE (n:KG {id: 'file:qix.h'}) SET n:SourceFile SET n += {path: 'qix.h', external: true};
MERGE (n:KG {id: 'file:machine/nvram.h'}) SET n:SourceFile SET n += {path: 'machine/nvram.h', external: true};
MERGE (n:KG {id: 'file:elecyoyo.lh'}) SET n:SourceFile SET n += {path: 'elecyoyo.lh', external: true};
MERGE (n:KG {id: 'file:sound/discrete.h'}) SET n:SourceFile SET n += {path: 'sound/discrete.h', external: true};
MERGE (n:KG {id: 'file:src/mame/taito/qix_v.cpp'}) SET n:SourceFile SET n += {path: 'src/mame/taito/qix_v.cpp'};
MERGE (n:KG {id: 'file:src/mame/taito/qix_a.cpp'}) SET n:SourceFile SET n += {path: 'src/mame/taito/qix_a.cpp'};
MERGE (n:KG {id: 'file:cpu/m6800/m6800.h'}) SET n:SourceFile SET n += {path: 'cpu/m6800/m6800.h', external: true};
MERGE (n:KG {id: 'file:machine/input_merger.h'}) SET n:SourceFile SET n += {path: 'machine/input_merger.h', external: true};
MERGE (n:KG {id: 'file:speaker.h'}) SET n:SourceFile SET n += {path: 'speaker.h', external: true};
MERGE (n:KG {id: 'game:qix'}) SET n:Game SET n += {name: 'qix', year: '1981', company: 'Taito America', fullname: 'Qix (Rev 2)', monitor: 'ROT270', cls: 'qix_state', init: 'empty_init', flags: 'MACHINE_SUPPORTS_SAVE', kind: 'arcade', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 1498, sourceColumn: 1, sourceEndLine: 1498};
MERGE (n:KG {id: 'romset:qix'}) SET n:RomSet SET n += {name: 'qix', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 763, sourceColumn: 1, sourceEndLine: 763};
MERGE (n:KG {id: 'region:qix/maincpu'}) SET n:RomRegion SET n += {tag: 'maincpu', size: 65536, flags: '0', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 764, sourceColumn: 2, sourceEndLine: 764};
MERGE (n:KG {id: 'rom:qix/maincpu/qq12_rev2.u12'}) SET n:Rom SET n += {file: 'qq12_rev2.u12', offset: 49152, size: 2048, crc: 'aad35508', sha1: '5fa72e00b4373de21e27a86b49a44a9769f769f4', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 765, sourceColumn: 2, sourceEndLine: 765};
MERGE (n:KG {id: 'rom:qix/maincpu/qq13_rev2.u13'}) SET n:Rom SET n += {file: 'qq13_rev2.u13', offset: 51200, size: 2048, crc: '46c13504', sha1: '19c084c38b75f14bf5094b317afeecaca6870f7a', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 766, sourceColumn: 2, sourceEndLine: 766};
MERGE (n:KG {id: 'rom:qix/maincpu/qq14_rev2.u14'}) SET n:Rom SET n += {file: 'qq14_rev2.u14', offset: 53248, size: 2048, crc: '5115e896', sha1: '8359a1700fff7a38e8ea4f92a4f18bc628cf1cb1', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 767, sourceColumn: 2, sourceEndLine: 767};
MERGE (n:KG {id: 'rom:qix/maincpu/qq15_rev2.u15'}) SET n:Rom SET n += {file: 'qq15_rev2.u15', offset: 55296, size: 2048, crc: 'ccd52a1b', sha1: '86d134cd769ef12820638b96a4ffedd8b15dffd2', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 768, sourceColumn: 2, sourceEndLine: 768};
MERGE (n:KG {id: 'rom:qix/maincpu/qq16_rev2.u16'}) SET n:Rom SET n += {file: 'qq16_rev2.u16', offset: 57344, size: 2048, crc: 'cd1c36ee', sha1: 'b379b1fe3109947a12c9683cd0c2400c2ee845b3', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 769, sourceColumn: 2, sourceEndLine: 769};
MERGE (n:KG {id: 'rom:qix/maincpu/qq17_rev2.u17'}) SET n:Rom SET n += {file: 'qq17_rev2.u17', offset: 59392, size: 2048, crc: '1acb682d', sha1: 'a2c60964e8d838d09662f8a670c6da41ba850df9', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 770, sourceColumn: 2, sourceEndLine: 770};
MERGE (n:KG {id: 'rom:qix/maincpu/qq18_rev2.u18'}) SET n:Rom SET n += {file: 'qq18_rev2.u18', offset: 61440, size: 2048, crc: 'de77728b', sha1: '8e183bb27858aad9a996e4a2e5a95f0145d1f5b4', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 771, sourceColumn: 2, sourceEndLine: 771};
MERGE (n:KG {id: 'rom:qix/maincpu/qq19_rev2.u19'}) SET n:Rom SET n += {file: 'qq19_rev2.u19', offset: 63488, size: 2048, crc: 'c0994776', sha1: '9452a98c78a038679c4e58f4a9983adb28ea5e78', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 772, sourceColumn: 2, sourceEndLine: 772};
MERGE (n:KG {id: 'region:qix/videocpu'}) SET n:RomRegion SET n += {tag: 'videocpu', size: 65536, flags: '0', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 774, sourceColumn: 2, sourceEndLine: 774};
MERGE (n:KG {id: 'rom:qix/videocpu/qq4_rev2.u4'}) SET n:Rom SET n += {file: 'qq4_rev2.u4', offset: 51200, size: 2048, crc: '5b906a09', sha1: '84a2e817d6718e0276fcea702811a91bc054a670', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 775, sourceColumn: 2, sourceEndLine: 775};
MERGE (n:KG {id: 'rom:qix/videocpu/qq5_rev2.u5'}) SET n:Rom SET n += {file: 'qq5_rev2.u5', offset: 53248, size: 2048, crc: '254a3587', sha1: '66045c71cc1d04d4e03c728e578f570fbf7c650d', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 776, sourceColumn: 2, sourceEndLine: 776};
MERGE (n:KG {id: 'rom:qix/videocpu/qq6_rev2.u6'}) SET n:Rom SET n += {file: 'qq6_rev2.u6', offset: 55296, size: 2048, crc: 'ace30389', sha1: '50c6275d13cfbca7750d5a3e725faedba7574e04', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 777, sourceColumn: 2, sourceEndLine: 777};
MERGE (n:KG {id: 'rom:qix/videocpu/qq7_rev2.u7'}) SET n:Rom SET n += {file: 'qq7_rev2.u7', offset: 57344, size: 2048, crc: '8ebcfa7c', sha1: '21ccf5e74424ab5470473d1059ee6a43d144f685', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 778, sourceColumn: 2, sourceEndLine: 778};
MERGE (n:KG {id: 'rom:qix/videocpu/qq8_rev2.u8'}) SET n:Rom SET n += {file: 'qq8_rev2.u8', offset: 59392, size: 2048, crc: 'b8a3c8f9', sha1: '32ba771913ef44b1133ecfaedaae7f96dcc84343', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 779, sourceColumn: 2, sourceEndLine: 779};
MERGE (n:KG {id: 'rom:qix/videocpu/qq9_rev2.u9'}) SET n:Rom SET n += {file: 'qq9_rev2.u9', offset: 61440, size: 2048, crc: '26cbcd55', sha1: '2e55e222f850548cd1d461ab5337e98dd817b567', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 780, sourceColumn: 2, sourceEndLine: 780};
MERGE (n:KG {id: 'rom:qix/videocpu/qq10_rev2.u10'}) SET n:Rom SET n += {file: 'qq10_rev2.u10', offset: 63488, size: 2048, crc: '568be942', sha1: '8b6a01d983d355a64372fa76af810ab53e09d5df', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 781, sourceColumn: 2, sourceEndLine: 781};
MERGE (n:KG {id: 'region:qix/audiocpu'}) SET n:RomRegion SET n += {tag: 'audiocpu', size: 65536, flags: '0', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 783, sourceColumn: 2, sourceEndLine: 783};
MERGE (n:KG {id: 'rom:qix/audiocpu/qq27.u27'}) SET n:Rom SET n += {file: 'qq27.u27', offset: 63488, size: 2048, crc: 'f3782bd0', sha1: 'bfc6d29f9668e02857453e96c005c81568ae931d', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 784, sourceColumn: 2, sourceEndLine: 784};
MERGE (n:KG {id: 'map:qix_state.qix_main_map'}) SET n:AddressMap SET n += {cls: 'qix_state', name: 'qix_main_map', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 279, sourceColumn: 1, sourceEndLine: 291};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range0'}) SET n:AddressRange SET n += {start: 32768, end: 33791, raw: 'map(0x8000, 0x83ff).ram().share("sharedram")', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 281, sourceColumn: 2, sourceEndLine: 281, ram: true, share: 'sharedram'};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range1'}) SET n:AddressRange SET n += {start: 33792, end: 34815, raw: 'map(0x8400, 0x87ff).ram()', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 282, sourceColumn: 2, sourceEndLine: 282, ram: true};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range2'}) SET n:AddressRange SET n += {start: 34816, end: 35839, raw: 'map(0x8800, 0x8bff).nopr()', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 283, sourceColumn: 2, sourceEndLine: 283, nopr: true};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range3'}) SET n:AddressRange SET n += {start: 35840, end: 35840, raw: 'map(0x8c00, 0x8c00).mirror(0x3fe).rw(FUNC(qix_state::video_firq_r), FUNC(qix_state::video_firq_w))', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 284, sourceColumn: 2, sourceEndLine: 284, mirror: 1022};
MERGE (n:KG {id: 'handler:qix_state.video_firq_r'}) SET n:Handler SET n += {method: 'video_firq_r', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 145, sourceColumn: 1, sourceEndLine: 150, sourceConstants: ['M6809_FIRQ_LINE=1'], sourceParameters: 'address_space &space', sourceBody: 'if (!machine().side_effects_disabled())
		m_videocpu->set_input_line(M6809_FIRQ_LINE, ASSERT_LINE);
	return space.unmap();'};
MERGE (n:KG {id: 'handler:qix_state.video_firq_w'}) SET n:Handler SET n += {method: 'video_firq_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 133, sourceColumn: 1, sourceEndLine: 136, sourceConstants: ['M6809_FIRQ_LINE=1'], sourceParameters: 'uint8_t data', sourceBody: 'm_videocpu->set_input_line(M6809_FIRQ_LINE, ASSERT_LINE);'};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range4'}) SET n:AddressRange SET n += {start: 35841, end: 35841, raw: 'map(0x8c01, 0x8c01).mirror(0x3fe).rw(FUNC(qix_state::data_firq_ack_r), FUNC(qix_state::data_firq_ack_w))', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 285, sourceColumn: 2, sourceEndLine: 285, mirror: 1022};
MERGE (n:KG {id: 'handler:qix_state.data_firq_ack_r'}) SET n:Handler SET n += {method: 'data_firq_ack_r', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 118, sourceColumn: 1, sourceEndLine: 123, sourceConstants: ['M6809_FIRQ_LINE=1'], sourceParameters: 'address_space &space', sourceBody: 'if (!machine().side_effects_disabled())
		m_maincpu->set_input_line(M6809_FIRQ_LINE, CLEAR_LINE);
	return space.unmap();'};
MERGE (n:KG {id: 'handler:qix_state.data_firq_ack_w'}) SET n:Handler SET n += {method: 'data_firq_ack_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 104, sourceColumn: 1, sourceEndLine: 107, sourceConstants: ['M6809_FIRQ_LINE=1'], sourceParameters: 'uint8_t data', sourceBody: 'm_maincpu->set_input_line(M6809_FIRQ_LINE, CLEAR_LINE);'};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range5'}) SET n:AddressRange SET n += {start: 36864, end: 37887, raw: 'map(0x9000, 0x93ff).rw(m_sndpia[0], FUNC(pia6821_device::read), FUNC(pia6821_device::write))', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 286, sourceColumn: 2, sourceEndLine: 286};
MERGE (n:KG {id: 'handler:pia6821_device.read'}) SET n:Handler SET n += {method: 'read', ownerClass: 'pia6821_device', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 131, sourceColumn: 2, sourceEndLine: 131};
MERGE (n:KG {id: 'handler:pia6821_device.write'}) SET n:Handler SET n += {method: 'write', ownerClass: 'pia6821_device', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 131, sourceColumn: 2, sourceEndLine: 131};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range6'}) SET n:AddressRange SET n += {start: 37888, end: 38911, raw: 'map(0x9400, 0x97ff).r(m_pia[0], FUNC(pia6821_device::read)).w(FUNC(qix_state::pia_w))', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 287, sourceColumn: 2, sourceEndLine: 287};
MERGE (n:KG {id: 'handler:qix_state.pia_w'}) SET n:Handler SET n += {method: 'pia_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 260, sourceColumn: 1, sourceEndLine: 265, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: '// make all the CPUs synchronize, and only AFTER that write the command to the PIA
	// otherwise the 68705 will miss commands
	machine().scheduler().synchronize(timer_expired_delegate(FUNC(qix_state::pia_w_callback), this), data | (offset << 8));'};
MERGE (n:KG {id: 'handler:qix_state.pia_w_callback'}) SET n:Handler SET n += {method: 'pia_w_callback', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 254, sourceColumn: 1, sourceEndLine: 257, sourceParameters: 'int param', sourceBody: 'm_pia[0]->write(param >> 8, param & 0xff);'};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range7'}) SET n:AddressRange SET n += {start: 38912, end: 39935, raw: 'map(0x9800, 0x9bff).rw(m_pia[1], FUNC(pia6821_device::read), FUNC(pia6821_device::write))', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 288, sourceColumn: 2, sourceEndLine: 288};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range8'}) SET n:AddressRange SET n += {start: 39936, end: 40959, raw: 'map(0x9c00, 0x9fff).rw(m_pia[2], FUNC(pia6821_device::read), FUNC(pia6821_device::write))', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 289, sourceColumn: 2, sourceEndLine: 289};
MERGE (n:KG {id: 'map:qix_state.qix_main_map/range9'}) SET n:AddressRange SET n += {start: 40960, end: 65535, raw: 'map(0xa000, 0xffff).rom()', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 290, sourceColumn: 2, sourceEndLine: 290, rom: true};
MERGE (n:KG {id: 'map:qix_state.qix_video_map'}) SET n:AddressMap SET n += {cls: 'qix_state', name: 'qix_video_map', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 285, sourceColumn: 1, sourceEndLine: 300};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 32767, raw: 'map(0x0000, 0x7fff).rw(FUNC(qix_state::videoram_r), FUNC(qix_state::videoram_w))', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 287, sourceColumn: 2, sourceEndLine: 287};
MERGE (n:KG {id: 'handler:qix_state.videoram_r'}) SET n:Handler SET n += {method: 'videoram_r', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 79, sourceColumn: 1, sourceEndLine: 84, sourceParameters: 'offs_t offset', sourceBody: '/* add in the upper bit of the address latch */
	offset += (m_videoram_address[0] & 0x80) << 8;
	return m_videoram[offset];'};
MERGE (n:KG {id: 'handler:qix_state.videoram_w'}) SET n:Handler SET n += {method: 'videoram_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 87, sourceColumn: 1, sourceEndLine: 99, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: '/* update the screen in case the game is writing "behind" the beam -
	   Zookeeper likes to do this */
//  m_screen->update_now();
	m_screen->update_partial(m_screen->vpos());

	/* add in the upper bit of the address latch */
	offset += (m_videoram_address[0] & 0x80) << 8;

	/* write the data */
	m_videoram[offset] = data;'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range1'}) SET n:AddressRange SET n += {start: 32768, end: 33791, raw: 'map(0x8000, 0x83ff).ram().share("sharedram")', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 288, sourceColumn: 2, sourceEndLine: 288, ram: true, share: 'sharedram'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range2'}) SET n:AddressRange SET n += {start: 33792, end: 34815, raw: 'map(0x8400, 0x87ff).ram().share("nvram")', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 289, sourceColumn: 2, sourceEndLine: 289, ram: true, share: 'nvram'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range3'}) SET n:AddressRange SET n += {start: 34816, end: 34816, raw: 'map(0x8800, 0x8800).mirror(0x03ff).w(FUNC(qix_state::palettebank_w))', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 290, sourceColumn: 2, sourceEndLine: 290, mirror: 1023};
MERGE (n:KG {id: 'handler:qix_state.palettebank_w'}) SET n:Handler SET n += {method: 'palettebank_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 194, sourceColumn: 1, sourceEndLine: 206, sourceParameters: 'uint8_t data', sourceBody: '/* set the bank value */
	if (m_palette_bank != (data & 3))
	{
		//m_screen->update_now();
		m_screen->update_partial(m_screen->vpos());
		m_palette_bank = data & 3;
	}

	/* LEDs are in the upper 6 bits */
	m_leds = ~data & 0xfc;'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range4'}) SET n:AddressRange SET n += {start: 35840, end: 35840, raw: 'map(0x8c00, 0x8c00).mirror(0x03fe).rw(FUNC(qix_state::data_firq_r), FUNC(qix_state::data_firq_w))', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 291, sourceColumn: 2, sourceEndLine: 291, mirror: 1022};
MERGE (n:KG {id: 'handler:qix_state.data_firq_r'}) SET n:Handler SET n += {method: 'data_firq_r', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 110, sourceColumn: 1, sourceEndLine: 115, sourceConstants: ['M6809_FIRQ_LINE=1'], sourceParameters: 'address_space &space', sourceBody: 'if (!machine().side_effects_disabled())
		m_maincpu->set_input_line(M6809_FIRQ_LINE, ASSERT_LINE);
	return space.unmap();'};
MERGE (n:KG {id: 'handler:qix_state.data_firq_w'}) SET n:Handler SET n += {method: 'data_firq_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 98, sourceColumn: 1, sourceEndLine: 101, sourceConstants: ['M6809_FIRQ_LINE=1'], sourceParameters: 'uint8_t data', sourceBody: 'm_maincpu->set_input_line(M6809_FIRQ_LINE, ASSERT_LINE);'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range5'}) SET n:AddressRange SET n += {start: 35841, end: 35841, raw: 'map(0x8c01, 0x8c01).mirror(0x03fe).rw(FUNC(qix_state::video_firq_ack_r), FUNC(qix_state::video_firq_ack_w))', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 292, sourceColumn: 2, sourceEndLine: 292, mirror: 1022};
MERGE (n:KG {id: 'handler:qix_state.video_firq_ack_r'}) SET n:Handler SET n += {method: 'video_firq_ack_r', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 153, sourceColumn: 1, sourceEndLine: 158, sourceConstants: ['M6809_FIRQ_LINE=1'], sourceParameters: 'address_space &space', sourceBody: 'if (!machine().side_effects_disabled())
		m_videocpu->set_input_line(M6809_FIRQ_LINE, CLEAR_LINE);
	return space.unmap();'};
MERGE (n:KG {id: 'handler:qix_state.video_firq_ack_w'}) SET n:Handler SET n += {method: 'video_firq_ack_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 139, sourceColumn: 1, sourceEndLine: 142, sourceConstants: ['M6809_FIRQ_LINE=1'], sourceParameters: 'uint8_t data', sourceBody: 'm_videocpu->set_input_line(M6809_FIRQ_LINE, CLEAR_LINE);'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range6'}) SET n:AddressRange SET n += {start: 36864, end: 37887, raw: 'map(0x9000, 0x93ff).ram().w(FUNC(qix_state::paletteram_w)).share("palette")', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 293, sourceColumn: 2, sourceEndLine: 293, ram: true, share: 'palette'};
MERGE (n:KG {id: 'handler:qix_state.paletteram_w'}) SET n:Handler SET n += {method: 'paletteram_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 177, sourceColumn: 1, sourceEndLine: 191, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'uint8_t const old_data = m_palette->read8(offset);

	/* trigger an update if a currently visible pen has changed */
	if (((offset >> 8) == m_palette_bank) &&
		(old_data != data))
	{
	//  m_screen->update_now();
		m_screen->update_partial(m_screen->vpos());
	}

	/* set the palette RAM value */
	m_palette->write8(offset, data);'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range7'}) SET n:AddressRange SET n += {start: 37888, end: 37888, raw: 'map(0x9400, 0x9400).mirror(0x03fc).rw(FUNC(qix_state::addresslatch_r), FUNC(qix_state::addresslatch_w))', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 294, sourceColumn: 2, sourceEndLine: 294, mirror: 1020};
MERGE (n:KG {id: 'handler:qix_state.addresslatch_r'}) SET n:Handler SET n += {method: 'addresslatch_r', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 133, sourceColumn: 1, sourceEndLine: 138, sourceParameters: '', sourceBody: '/* compute the value at the address latch */
	offs_t const offset = (m_videoram_address[0] << 8) | m_videoram_address[1];
	return m_videoram[offset];'};
MERGE (n:KG {id: 'handler:qix_state.addresslatch_w'}) SET n:Handler SET n += {method: 'addresslatch_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 141, sourceColumn: 1, sourceEndLine: 152, sourceParameters: 'uint8_t data', sourceBody: '/* update the screen in case the game is writing "behind" the beam */
//  m_screen->update_now();
	m_screen->update_partial(m_screen->vpos());

	/* compute the value at the address latch */
	offs_t const offset = (m_videoram_address[0] << 8) | m_videoram_address[1];

	/* write the data */
	m_videoram[offset] = data;'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range8'}) SET n:AddressRange SET n += {start: 37890, end: 37891, raw: 'map(0x9402, 0x9403).mirror(0x03fc).writeonly().share(m_videoram_address)', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 295, sourceColumn: 2, sourceEndLine: 295, mirror: 1020, writeonly: true, share: 'videoram_address'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range9'}) SET n:AddressRange SET n += {start: 38912, end: 38912, raw: 'map(0x9800, 0x9800).mirror(0x03ff).readonly().share(m_scanline_latch)', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 296, sourceColumn: 2, sourceEndLine: 296, mirror: 1023, readonly: true, share: 'scanline_latch'};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range10'}) SET n:AddressRange SET n += {start: 39936, end: 39936, raw: 'map(0x9c00, 0x9c00).mirror(0x03fe).w(m_crtc, FUNC(mc6845_device::address_w))', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 297, sourceColumn: 2, sourceEndLine: 297, mirror: 1022};
MERGE (n:KG {id: 'handler:mc6845_device.address_w'}) SET n:Handler SET n += {method: 'address_w', ownerClass: 'mc6845_device', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 354, sourceColumn: 2, sourceEndLine: 354};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range11'}) SET n:AddressRange SET n += {start: 39937, end: 39937, raw: 'map(0x9c01, 0x9c01).mirror(0x03fe).rw(m_crtc, FUNC(mc6845_device::register_r), FUNC(mc6845_device::register_w))', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 298, sourceColumn: 2, sourceEndLine: 298, mirror: 1022};
MERGE (n:KG {id: 'handler:mc6845_device.register_r'}) SET n:Handler SET n += {method: 'register_r', ownerClass: 'mc6845_device', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 355, sourceColumn: 2, sourceEndLine: 355};
MERGE (n:KG {id: 'handler:mc6845_device.register_w'}) SET n:Handler SET n += {method: 'register_w', ownerClass: 'mc6845_device', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 355, sourceColumn: 2, sourceEndLine: 355};
MERGE (n:KG {id: 'map:qix_state.qix_video_map/range12'}) SET n:AddressRange SET n += {start: 40960, end: 65535, raw: 'map(0xa000, 0xffff).rom()', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 299, sourceColumn: 2, sourceEndLine: 299, rom: true};
MERGE (n:KG {id: 'map:qix_state.audio_map'}) SET n:AddressMap SET n += {cls: 'qix_state', name: 'audio_map', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 128, sourceColumn: 1, sourceEndLine: 133};
MERGE (n:KG {id: 'map:qix_state.audio_map/range0'}) SET n:AddressRange SET n += {start: 8192, end: 8195, raw: 'map(0x2000, 0x2003).mirror(0x5ffc).rw(m_sndpia[2], FUNC(pia6821_device::read), FUNC(pia6821_device::write))', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 130, sourceColumn: 2, sourceEndLine: 130, mirror: 24572};
MERGE (n:KG {id: 'map:qix_state.audio_map/range1'}) SET n:AddressRange SET n += {start: 16384, end: 16387, raw: 'map(0x4000, 0x4003).mirror(0x3ffc).rw(m_sndpia[1], FUNC(pia6821_device::read), FUNC(pia6821_device::write))', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 131, sourceColumn: 2, sourceEndLine: 131, mirror: 16380};
MERGE (n:KG {id: 'map:qix_state.audio_map/range2'}) SET n:AddressRange SET n += {start: 53248, end: 65535, raw: 'map(0xd000, 0xffff).rom()', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 132, sourceColumn: 2, sourceEndLine: 132, rom: true};
MERGE (n:KG {id: 'machine:qix_state.qix_base'}) SET n:MachineConfig SET n += {cls: 'qix_state', name: 'qix_base', calls: ['qix_video'], stateMembers: ['{"name":"m_flip","bits":1}', '{"name":"m_palette_bank","bits":8}', '{"name":"m_leds","bits":8}'], perfectQuantum: true, startHandlers: ['qix_state.video_start'], sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 635, sourceColumn: 1, sourceEndLine: 665};
MERGE (n:KG {id: 'handler:qix_state.video_start'}) SET n:Handler SET n += {method: 'video_start', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 20, sourceColumn: 1, sourceEndLine: 26, sourceParameters: '', sourceBody: '/* set up save states */
	save_item(NAME(m_flip));
	save_item(NAME(m_palette_bank));
	save_item(NAME(m_leds));'};
MERGE (n:KG {id: 'device:qix_state.qix_base/maincpu'}) SET n:Device SET n += {type: 'MC6809E', tag: 'maincpu', clock: 1250000, config: ['MC6809E(config, m_maincpu, MAIN_CLOCK_OSC/4/4)', 'm_maincpu->set_addrmap(AS_PROGRAM, &qix_state::qix_main_map)', 'config.set_perfect_quantum(m_maincpu)'], sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 638, sourceColumn: 2, sourceEndLine: 638};
MERGE (n:KG {id: 'device:qix_state.qix_base/nvram'}) SET n:Device SET n += {type: 'NVRAM', tag: 'nvram', clock: null, config: ['NVRAM(config, "nvram", nvram_device::DEFAULT_ALL_0)'], sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 645, sourceColumn: 2, sourceEndLine: 645, clockExpr: 'nvram_device::DEFAULT_ALL_0'};
MERGE (n:KG {id: 'device:qix_state.qix_base/pia0'}) SET n:Device SET n += {type: 'PIA6821', tag: 'pia0', clock: null, config: ['PIA6821(config, m_pia[0])', 'm_pia[0]->readpa_handler().set_ioport("P1")', 'm_pia[0]->set_port_a_input_overrides_output_mask(0xff)', 'm_pia[0]->readpb_handler().set_ioport("COIN")'], sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 647, sourceColumn: 2, sourceEndLine: 647, configCalls: ['set_port_a_input_overrides_output_mask(255)']};
MERGE (n:KG {id: 'device:qix_state.qix_base/pia0/callback:pia0:0'}) SET n:Callback SET n += {signal: 'readpa_handler', operation: 'set_ioport', raw: 'm_pia[0]->readpa_handler().set_ioport("P1")', ownerTag: 'pia0', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 648, sourceColumn: 2, sourceEndLine: 648, targetTag: 'P1', targetPort: 'P1'};
MERGE (n:KG {id: 'device:qix_state.qix_base/pia0/callback:pia0:1'}) SET n:Callback SET n += {signal: 'readpb_handler', operation: 'set_ioport', raw: 'm_pia[0]->readpb_handler().set_ioport("COIN")', ownerTag: 'pia0', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 650, sourceColumn: 2, sourceEndLine: 650, targetTag: 'COIN', targetPort: 'COIN'};
MERGE (n:KG {id: 'device:qix_state.qix_base/pia1'}) SET n:Device SET n += {type: 'PIA6821', tag: 'pia1', clock: null, config: ['PIA6821(config, m_pia[1])', 'm_pia[1]->readpa_handler().set_ioport("SPARE")', 'm_pia[1]->set_port_a_input_overrides_output_mask(0xff)', 'm_pia[1]->readpb_handler().set_ioport("IN0")'], sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 652, sourceColumn: 2, sourceEndLine: 652, configCalls: ['set_port_a_input_overrides_output_mask(255)']};
MERGE (n:KG {id: 'device:qix_state.qix_base/pia1/callback:pia1:0'}) SET n:Callback SET n += {signal: 'readpa_handler', operation: 'set_ioport', raw: 'm_pia[1]->readpa_handler().set_ioport("SPARE")', ownerTag: 'pia1', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 653, sourceColumn: 2, sourceEndLine: 653, targetTag: 'SPARE', targetPort: 'SPARE'};
MERGE (n:KG {id: 'device:qix_state.qix_base/pia1/callback:pia1:1'}) SET n:Callback SET n += {signal: 'readpb_handler', operation: 'set_ioport', raw: 'm_pia[1]->readpb_handler().set_ioport("IN0")', ownerTag: 'pia1', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 655, sourceColumn: 2, sourceEndLine: 655, targetTag: 'IN0', targetPort: 'IN0'};
MERGE (n:KG {id: 'device:qix_state.qix_base/pia2'}) SET n:Device SET n += {type: 'PIA6821', tag: 'pia2', clock: null, config: ['PIA6821(config, m_pia[2])', 'm_pia[2]->readpa_handler().set_ioport("P2")', 'm_pia[2]->set_port_a_input_overrides_output_mask(0xff)', 'm_pia[2]->writepb_handler().set(FUNC(qix_state::coinctr_w))', 'm_pia[2]->tspb_handler().set_constant(0)'], sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 657, sourceColumn: 2, sourceEndLine: 657, configCalls: ['set_port_a_input_overrides_output_mask(255)']};
MERGE (n:KG {id: 'device:qix_state.qix_base/pia2/callback:pia2:0'}) SET n:Callback SET n += {signal: 'readpa_handler', operation: 'set_ioport', raw: 'm_pia[2]->readpa_handler().set_ioport("P2")', ownerTag: 'pia2', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 658, sourceColumn: 2, sourceEndLine: 658, targetTag: 'P2', targetPort: 'P2'};
MERGE (n:KG {id: 'device:qix_state.qix_base/pia2/callback:pia2:1'}) SET n:Callback SET n += {signal: 'writepb_handler', operation: 'set', raw: 'm_pia[2]->writepb_handler().set(FUNC(qix_state::coinctr_w))', ownerTag: 'pia2', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 660, sourceColumn: 2, sourceEndLine: 660, targetClass: 'qix_state', targetMethod: 'coinctr_w'};
MERGE (n:KG {id: 'handler:qix_state.coinctr_w'}) SET n:Handler SET n += {method: 'coinctr_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 275, sourceColumn: 1, sourceEndLine: 279, sourceParameters: 'uint8_t data', sourceBody: 'machine().bookkeeping().coin_lockout_w(0, BIT(~data, 2));
	machine().bookkeeping().coin_counter_w(0, BIT(data, 1));'};
MERGE (n:KG {id: 'machine:qix_state.qix'}) SET n:MachineConfig SET n += {cls: 'qix_state', name: 'qix', calls: ['qix_base', 'qix_audio'], stateMembers: ['{"name":"m_flip","bits":1}', '{"name":"m_palette_bank","bits":8}', '{"name":"m_leds","bits":8}'], startHandlers: ['qix_state.video_start'], sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 668, sourceColumn: 1, sourceEndLine: 672};
MERGE (n:KG {id: 'machine:qix_state.qix_video'}) SET n:MachineConfig SET n += {cls: 'qix_state', name: 'qix_video', calls: [], stateMembers: ['{"name":"m_flip","bits":1}', '{"name":"m_palette_bank","bits":8}', '{"name":"m_leds","bits":8}'], startHandlers: ['qix_state.video_start'], sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 367, sourceColumn: 1, sourceEndLine: 388};
MERGE (n:KG {id: 'device:qix_state.qix_video/videocpu'}) SET n:Device SET n += {type: 'MC6809E', tag: 'videocpu', clock: 1250000, config: ['MC6809E(config, m_videocpu, MAIN_CLOCK_OSC/4/4)', 'm_videocpu->set_addrmap(AS_PROGRAM, &qix_state::qix_video_map)'], sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 371, sourceColumn: 2, sourceEndLine: 371};
MERGE (n:KG {id: 'device:qix_state.qix_video/vid_u18'}) SET n:Device SET n += {type: 'MC6845', tag: 'vid_u18', clock: 625000, config: ['MC6845(config, m_crtc, QIX_CHARACTER_CLOCK)', 'm_crtc->set_screen(m_screen)', 'm_crtc->set_show_border_area(false)', 'm_crtc->set_char_width(8)', 'm_crtc->set_begin_update_callback(FUNC(qix_state::crtc_begin_update))', 'm_crtc->set_update_row_callback(FUNC(qix_state::crtc_update_row))', 'm_crtc->out_de_callback().set(FUNC(qix_state::display_enable_changed))', 'm_crtc->out_vsync_callback().set(FUNC(qix_state::vsync_changed))'], sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 374, sourceColumn: 2, sourceEndLine: 374, configCalls: ['set_char_width(8)']};
MERGE (n:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:0'}) SET n:Callback SET n += {signal: 'set_begin_update_callback', delegate: 1, operation: 'set_begin_update_callback', raw: 'm_crtc->set_begin_update_callback(FUNC(qix_state::crtc_begin_update))', ownerTag: 'vid_u18', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 378, sourceColumn: 2, sourceEndLine: 378, targetClass: 'qix_state', targetMethod: 'crtc_begin_update'};
MERGE (n:KG {id: 'handler:qix_state.crtc_begin_update'}) SET n:Handler SET n += {method: 'crtc_begin_update', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 378, sourceColumn: 2, sourceEndLine: 378};
MERGE (n:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:1'}) SET n:Callback SET n += {signal: 'set_update_row_callback', delegate: 1, operation: 'set_update_row_callback', raw: 'm_crtc->set_update_row_callback(FUNC(qix_state::crtc_update_row))', ownerTag: 'vid_u18', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 379, sourceColumn: 2, sourceEndLine: 379, targetClass: 'qix_state', targetMethod: 'crtc_update_row'};
MERGE (n:KG {id: 'handler:qix_state.crtc_update_row'}) SET n:Handler SET n += {method: 'crtc_update_row', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 379, sourceColumn: 2, sourceEndLine: 379};
MERGE (n:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:2'}) SET n:Callback SET n += {signal: 'out_de_callback', operation: 'set', raw: 'm_crtc->out_de_callback().set(FUNC(qix_state::display_enable_changed))', ownerTag: 'vid_u18', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 380, sourceColumn: 2, sourceEndLine: 380, targetClass: 'qix_state', targetMethod: 'display_enable_changed'};
MERGE (n:KG {id: 'handler:qix_state.display_enable_changed'}) SET n:Handler SET n += {method: 'display_enable_changed', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 36, sourceColumn: 1, sourceEndLine: 47, sourceParameters: 'int state', sourceBody: '/* on the rising edge, latch the scanline */
	if (state)
	{
		uint16_t const ma = m_crtc->get_ma();
		uint8_t const ra = m_crtc->get_ra();

		/* RA0-RA2 goes to D0-D2 and MA5-MA9 goes to D3-D7 */
		*m_scanline_latch = ((ma >> 2) & 0xf8) | (ra & 0x07);
	}'};
MERGE (n:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:3'}) SET n:Callback SET n += {signal: 'out_vsync_callback', operation: 'set', raw: 'm_crtc->out_vsync_callback().set(FUNC(qix_state::vsync_changed))', ownerTag: 'vid_u18', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 381, sourceColumn: 2, sourceEndLine: 381, targetClass: 'qix_state', targetMethod: 'vsync_changed'};
MERGE (n:KG {id: 'handler:qix_state.vsync_changed'}) SET n:Handler SET n += {method: 'vsync_changed', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_m.cpp', sourceLine: 70, sourceColumn: 1, sourceEndLine: 73, sourceParameters: 'int state', sourceBody: 'm_sndpia[0]->cb1_w(state);'};
MERGE (n:KG {id: 'device:qix_state.qix_video/screen'}) SET n:Device SET n += {type: 'SCREEN', tag: 'screen', clock: null, config: ['SCREEN(config, m_screen, SCREEN_TYPE_RASTER)', 'm_screen->set_raw(QIX_CHARACTER_CLOCK*8, 0x148, 0, 0x100, 0x111, 0, 0x100)', 'm_screen->set_screen_update(m_crtc, FUNC(mc6845_device::screen_update))'], sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 383, sourceColumn: 2, sourceEndLine: 383, configCalls: ['set_raw(5000000,328,0,256,273,0,256)'], clockExpr: 'SCREEN_TYPE_RASTER', screenRaw: [5000000, 328, 0, 256, 273, 0, 256], screenRawExpr: ['QIX_CHARACTER_CLOCK*8', '0x148', '0', '0x100', '0x111', '0', '0x100']};
MERGE (n:KG {id: 'device:qix_state.qix_video/screen/callback:screen:0'}) SET n:Callback SET n += {signal: 'set_screen_update', operation: 'set_screen_update', raw: 'm_screen->set_screen_update(m_crtc, FUNC(mc6845_device::screen_update))', ownerTag: 'screen', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 385, sourceColumn: 2, sourceEndLine: 385, targetClass: 'mc6845_device', targetMethod: 'screen_update', targetTag: 'vid_u18'};
MERGE (n:KG {id: 'handler:mc6845_device.screen_update'}) SET n:Handler SET n += {method: 'screen_update', ownerClass: 'mc6845_device', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 385, sourceColumn: 2, sourceEndLine: 385};
MERGE (n:KG {id: 'device:qix_state.qix_video/palette'}) SET n:Device SET n += {type: 'PALETTE', tag: 'palette', clock: null, config: ['PALETTE(config, m_palette, palette_device::BLACK).set_format(1, &qix_state::qix_R2G2B2I2, 0x400)'], sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 387, sourceColumn: 2, sourceEndLine: 387, clockExpr: 'palette_device::BLACK'};
MERGE (n:KG {id: 'machine:qix_state.qix_audio'}) SET n:MachineConfig SET n += {cls: 'qix_state', name: 'qix_audio', calls: [], stateMembers: ['{"name":"m_flip","bits":1}', '{"name":"m_palette_bank","bits":8}', '{"name":"m_leds","bits":8}'], startHandlers: ['qix_state.video_start'], sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 143, sourceColumn: 1, sourceEndLine: 184};
MERGE (n:KG {id: 'device:qix_state.qix_audio/audiocpu'}) SET n:Device SET n += {type: 'M6802', tag: 'audiocpu', clock: 3686400, config: ['M6802(config, m_audiocpu, SOUND_CLOCK_OSC/2)', 'm_audiocpu->set_addrmap(AS_PROGRAM, &qix_state::audio_map)'], sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 147, sourceColumn: 2, sourceEndLine: 147};
MERGE (n:KG {id: 'device:qix_state.qix_audio/dint'}) SET n:Device SET n += {type: 'INPUT_MERGER_ANY_HIGH', tag: 'dint', clock: null, config: ['INPUT_MERGER_ANY_HIGH(config, "dint").output_handler().set_inputline(m_maincpu, M6809_IRQ_LINE)'], sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 151, sourceColumn: 2, sourceEndLine: 151};
MERGE (n:KG {id: 'device:qix_state.qix_audio/dint/callback:dint:0'}) SET n:Callback SET n += {signal: 'output_handler', operation: 'set_inputline', raw: 'INPUT_MERGER_ANY_HIGH(config, "dint").output_handler().set_inputline(m_maincpu, M6809_IRQ_LINE)', ownerTag: 'dint', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 151, sourceColumn: 2, sourceEndLine: 151, inputLine: 'M6809_IRQ_LINE', targetTag: 'maincpu'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sint'}) SET n:Device SET n += {type: 'INPUT_MERGER_ANY_HIGH', tag: 'sint', clock: null, config: ['INPUT_MERGER_ANY_HIGH(config, "sint").output_handler().set_inputline(m_audiocpu, M6802_IRQ_LINE)'], sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 154, sourceColumn: 2, sourceEndLine: 154};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sint/callback:sint:0'}) SET n:Callback SET n += {signal: 'output_handler', operation: 'set_inputline', raw: 'INPUT_MERGER_ANY_HIGH(config, "sint").output_handler().set_inputline(m_audiocpu, M6802_IRQ_LINE)', ownerTag: 'sint', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 154, sourceColumn: 2, sourceEndLine: 154, inputLine: 'M6802_IRQ_LINE', targetTag: 'audiocpu'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia0'}) SET n:Device SET n += {type: 'PIA6821', tag: 'sndpia0', clock: null, config: ['PIA6821(config, m_sndpia[0])', 'm_sndpia[0]->writepa_handler().set(FUNC(qix_state::sync_sndpia1_porta_w))', 'm_sndpia[0]->writepb_handler().set(FUNC(qix_state::vol_w))', 'm_sndpia[0]->tspb_handler().set_constant(0xff)', 'm_sndpia[0]->ca2_handler().set(m_sndpia[1], FUNC(pia6821_device::ca1_w))', 'm_sndpia[0]->cb2_handler().set(FUNC(qix_state::flip_screen_w))', 'm_sndpia[0]->irqa_handler().set("dint", FUNC(input_merger_device::in_w<0>))', 'm_sndpia[0]->irqb_handler().set("dint", FUNC(input_merger_device::in_w<1>))'], sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 156, sourceColumn: 2, sourceEndLine: 156};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:0'}) SET n:Callback SET n += {signal: 'writepa_handler', operation: 'set', raw: 'm_sndpia[0]->writepa_handler().set(FUNC(qix_state::sync_sndpia1_porta_w))', ownerTag: 'sndpia0', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 157, sourceColumn: 2, sourceEndLine: 157, targetClass: 'qix_state', targetMethod: 'sync_sndpia1_porta_w'};
MERGE (n:KG {id: 'handler:qix_state.sync_sndpia1_porta_w'}) SET n:Handler SET n += {method: 'sync_sndpia1_porta_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 114, sourceColumn: 1, sourceEndLine: 118, sourceParameters: 'uint8_t data', sourceBody: '/* we need to synchronize this so the sound CPU doesn\'t drop anything important */
	machine().scheduler().synchronize(timer_expired_delegate(FUNC(qix_state::deferred_sndpia1_porta_w), this), data);'};
MERGE (n:KG {id: 'handler:qix_state.deferred_sndpia1_porta_w'}) SET n:Handler SET n += {method: 'deferred_sndpia1_porta_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 108, sourceColumn: 1, sourceEndLine: 111, sourceParameters: 'int param', sourceBody: 'm_sndpia[1]->porta_w(param);'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:1'}) SET n:Callback SET n += {signal: 'writepb_handler', operation: 'set', raw: 'm_sndpia[0]->writepb_handler().set(FUNC(qix_state::vol_w))', ownerTag: 'sndpia0', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 158, sourceColumn: 2, sourceEndLine: 158, targetClass: 'qix_state', targetMethod: 'vol_w'};
MERGE (n:KG {id: 'handler:qix_state.vol_w'}) SET n:Handler SET n += {method: 'vol_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 38, sourceColumn: 1, sourceEndLine: 41, sourceParameters: 'uint8_t data', sourceBody: 'm_discrete->write(QIX_VOL_DATA, data);'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:2'}) SET n:Callback SET n += {signal: 'ca2_handler', operation: 'set', raw: 'm_sndpia[0]->ca2_handler().set(m_sndpia[1], FUNC(pia6821_device::ca1_w))', ownerTag: 'sndpia0', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 160, sourceColumn: 2, sourceEndLine: 160, targetClass: 'pia6821_device', targetMethod: 'ca1_w', targetTag: 'sndpia1'};
MERGE (n:KG {id: 'handler:pia6821_device.ca1_w'}) SET n:Handler SET n += {method: 'ca1_w', ownerClass: 'pia6821_device', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 169, sourceColumn: 2, sourceEndLine: 169};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:3'}) SET n:Callback SET n += {signal: 'cb2_handler', operation: 'set', raw: 'm_sndpia[0]->cb2_handler().set(FUNC(qix_state::flip_screen_w))', ownerTag: 'sndpia0', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 161, sourceColumn: 2, sourceEndLine: 161, targetClass: 'qix_state', targetMethod: 'flip_screen_w'};
MERGE (n:KG {id: 'handler:qix_state.flip_screen_w'}) SET n:Handler SET n += {method: 'flip_screen_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 57, sourceColumn: 1, sourceEndLine: 60, sourceParameters: 'int state', sourceBody: 'm_flip = state;'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:4'}) SET n:Callback SET n += {signal: 'irqa_handler', operation: 'set', raw: 'm_sndpia[0]->irqa_handler().set("dint", FUNC(input_merger_device::in_w<0>))', ownerTag: 'sndpia0', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 162, sourceColumn: 2, sourceEndLine: 162, targetTag: 'dint', targetClass: 'input_merger_device', targetMethod: 'in_w_0'};
MERGE (n:KG {id: 'handler:input_merger_device.in_w_0'}) SET n:Handler SET n += {method: 'in_w_0', ownerClass: 'input_merger_device', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 196, sourceColumn: 2, sourceEndLine: 196};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:5'}) SET n:Callback SET n += {signal: 'irqb_handler', operation: 'set', raw: 'm_sndpia[0]->irqb_handler().set("dint", FUNC(input_merger_device::in_w<1>))', ownerTag: 'sndpia0', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 163, sourceColumn: 2, sourceEndLine: 163, targetTag: 'dint', targetClass: 'input_merger_device', targetMethod: 'in_w_1'};
MERGE (n:KG {id: 'handler:input_merger_device.in_w_1'}) SET n:Handler SET n += {method: 'in_w_1', ownerClass: 'input_merger_device', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 197, sourceColumn: 2, sourceEndLine: 197};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia1'}) SET n:Device SET n += {type: 'PIA6821', tag: 'sndpia1', clock: null, config: ['PIA6821(config, m_sndpia[1])', 'm_sndpia[1]->writepa_handler().set(m_sndpia[0], FUNC(pia6821_device::porta_w))', 'm_sndpia[1]->writepb_handler().set(FUNC(qix_state::dac_w))', 'm_sndpia[1]->tspb_handler().set_constant(0)', 'm_sndpia[1]->ca2_handler().set(m_sndpia[0], FUNC(pia6821_device::ca1_w))', 'm_sndpia[1]->irqa_handler().set("sint", FUNC(input_merger_device::in_w<0>))', 'm_sndpia[1]->irqb_handler().set("sint", FUNC(input_merger_device::in_w<1>))'], sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 165, sourceColumn: 2, sourceEndLine: 165};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:0'}) SET n:Callback SET n += {signal: 'writepa_handler', operation: 'set', raw: 'm_sndpia[1]->writepa_handler().set(m_sndpia[0], FUNC(pia6821_device::porta_w))', ownerTag: 'sndpia1', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 166, sourceColumn: 2, sourceEndLine: 166, targetClass: 'pia6821_device', targetMethod: 'porta_w', targetTag: 'sndpia0'};
MERGE (n:KG {id: 'handler:pia6821_device.porta_w'}) SET n:Handler SET n += {method: 'porta_w', ownerClass: 'pia6821_device', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 166, sourceColumn: 2, sourceEndLine: 166};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:1'}) SET n:Callback SET n += {signal: 'writepb_handler', operation: 'set', raw: 'm_sndpia[1]->writepb_handler().set(FUNC(qix_state::dac_w))', ownerTag: 'sndpia1', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 167, sourceColumn: 2, sourceEndLine: 167, targetClass: 'qix_state', targetMethod: 'dac_w'};
MERGE (n:KG {id: 'handler:qix_state.dac_w'}) SET n:Handler SET n += {method: 'dac_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 33, sourceColumn: 1, sourceEndLine: 36, sourceParameters: 'uint8_t data', sourceBody: 'm_discrete->write(QIX_DAC_DATA, data);'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:2'}) SET n:Callback SET n += {signal: 'ca2_handler', operation: 'set', raw: 'm_sndpia[1]->ca2_handler().set(m_sndpia[0], FUNC(pia6821_device::ca1_w))', ownerTag: 'sndpia1', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 169, sourceColumn: 2, sourceEndLine: 169, targetClass: 'pia6821_device', targetMethod: 'ca1_w', targetTag: 'sndpia0'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:3'}) SET n:Callback SET n += {signal: 'irqa_handler', operation: 'set', raw: 'm_sndpia[1]->irqa_handler().set("sint", FUNC(input_merger_device::in_w<0>))', ownerTag: 'sndpia1', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 170, sourceColumn: 2, sourceEndLine: 170, targetTag: 'sint', targetClass: 'input_merger_device', targetMethod: 'in_w_0'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:4'}) SET n:Callback SET n += {signal: 'irqb_handler', operation: 'set', raw: 'm_sndpia[1]->irqb_handler().set("sint", FUNC(input_merger_device::in_w<1>))', ownerTag: 'sndpia1', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 171, sourceColumn: 2, sourceEndLine: 171, targetTag: 'sint', targetClass: 'input_merger_device', targetMethod: 'in_w_1'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia2'}) SET n:Device SET n += {type: 'PIA6821', tag: 'sndpia2', clock: null, config: ['PIA6821(config, m_sndpia[2])', 'm_sndpia[2]->writepa_handler().set(FUNC(qix_state::sndpia_2_warning_w))', 'm_sndpia[2]->writepb_handler().set(FUNC(qix_state::sndpia_2_warning_w))', 'm_sndpia[2]->ca2_handler().set(FUNC(qix_state::sndpia_2_warning_w))', 'm_sndpia[2]->cb2_handler().set(FUNC(qix_state::sndpia_2_warning_w))'], sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 173, sourceColumn: 2, sourceEndLine: 173};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:0'}) SET n:Callback SET n += {signal: 'writepa_handler', operation: 'set', raw: 'm_sndpia[2]->writepa_handler().set(FUNC(qix_state::sndpia_2_warning_w))', ownerTag: 'sndpia2', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 174, sourceColumn: 2, sourceEndLine: 174, targetClass: 'qix_state', targetMethod: 'sndpia_2_warning_w'};
MERGE (n:KG {id: 'handler:qix_state.sndpia_2_warning_w'}) SET n:Handler SET n += {method: 'sndpia_2_warning_w', ownerClass: 'qix_state', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 100, sourceColumn: 1, sourceEndLine: 105, sourceParameters: 'uint8_t data', sourceBody: '// this PIA is supposedly unused
	if (machine().phase() > machine_phase::RESET)
		logerror("PIA 5 write!!\\n");'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:1'}) SET n:Callback SET n += {signal: 'writepb_handler', operation: 'set', raw: 'm_sndpia[2]->writepb_handler().set(FUNC(qix_state::sndpia_2_warning_w))', ownerTag: 'sndpia2', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 175, sourceColumn: 2, sourceEndLine: 175, targetClass: 'qix_state', targetMethod: 'sndpia_2_warning_w'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:2'}) SET n:Callback SET n += {signal: 'ca2_handler', operation: 'set', raw: 'm_sndpia[2]->ca2_handler().set(FUNC(qix_state::sndpia_2_warning_w))', ownerTag: 'sndpia2', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 176, sourceColumn: 2, sourceEndLine: 176, targetClass: 'qix_state', targetMethod: 'sndpia_2_warning_w'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:3'}) SET n:Callback SET n += {signal: 'cb2_handler', operation: 'set', raw: 'm_sndpia[2]->cb2_handler().set(FUNC(qix_state::sndpia_2_warning_w))', ownerTag: 'sndpia2', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 177, sourceColumn: 2, sourceEndLine: 177, targetClass: 'qix_state', targetMethod: 'sndpia_2_warning_w'};
MERGE (n:KG {id: 'device:qix_state.qix_audio/speaker'}) SET n:Device SET n += {type: 'SPEAKER', tag: 'speaker', clock: 2, config: ['SPEAKER(config, "speaker", 2).front()'], sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 179, sourceColumn: 2, sourceEndLine: 179};
MERGE (n:KG {id: 'device:qix_state.qix_audio/discrete'}) SET n:Device SET n += {type: 'DISCRETE', tag: 'discrete', clock: null, config: ['DISCRETE(config, m_discrete, qix_discrete)', 'm_discrete->add_route(0, "speaker", 1.0, 0)', 'm_discrete->add_route(1, "speaker", 1.0, 1)'], sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 181, sourceColumn: 2, sourceEndLine: 181, clockExpr: 'qix_discrete'};
MERGE (n:KG {id: 'audioroute:device:qix_state.qix_audio/discrete/0'}) SET n:AudioRoute SET n += {output: '0', target: 'speaker', gain: 1, input: 0, raw: 'm_discrete->add_route(0, "speaker", 1.0, 0)', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 182, sourceColumn: 2, sourceEndLine: 182};
MERGE (n:KG {id: 'audioroute:device:qix_state.qix_audio/discrete/1'}) SET n:AudioRoute SET n += {output: '1', target: 'speaker', gain: 1, input: 1, raw: 'm_discrete->add_route(1, "speaker", 1.0, 1)', sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 183, sourceColumn: 2, sourceEndLine: 183};
MERGE (n:KG {id: 'inputs:qix'}) SET n:InputPorts SET n += {name: 'qix', sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 343, sourceColumn: 8, sourceEndLine: 343};
MERGE (n:KG {id: 'inputs:qix/P1'}) SET n:Port SET n += {tag: 'P1', modify: false};
MERGE (n:KG {id: 'inputs:qix/P1/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_UP', modifiers: ['PORT_4WAY'], defaultValue: 1};
MERGE (n:KG {id: 'inputs:qix/P1/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_RIGHT', modifiers: ['PORT_4WAY'], defaultValue: 2};
MERGE (n:KG {id: 'inputs:qix/P1/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_DOWN', modifiers: ['PORT_4WAY'], defaultValue: 4};
MERGE (n:KG {id: 'inputs:qix/P1/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_LEFT', modifiers: ['PORT_4WAY'], defaultValue: 8};
MERGE (n:KG {id: 'inputs:qix/P1/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_BUTTON2', defaultValue: 16};
MERGE (n:KG {id: 'inputs:qix/P1/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_START2', defaultValue: 32};
MERGE (n:KG {id: 'inputs:qix/P1/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 64, activeLow: true, type: 'IPT_START1', defaultValue: 64};
MERGE (n:KG {id: 'inputs:qix/P1/f7'}) SET n:PortField SET n += {kind: 'bit', mask: 128, activeLow: true, type: 'IPT_BUTTON1', defaultValue: 128};
MERGE (n:KG {id: 'inputs:qix/COIN'}) SET n:Port SET n += {tag: 'COIN', modify: false};
MERGE (n:KG {id: 'inputs:qix/COIN/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_SERVICE1', modifiers: ['PORT_NAME("Test Advance")'], defaultValue: 1};
MERGE (n:KG {id: 'inputs:qix/COIN/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_SERVICE2', modifiers: ['PORT_NAME("Test Next line")'], defaultValue: 2};
MERGE (n:KG {id: 'inputs:qix/COIN/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_SERVICE3', modifiers: ['PORT_NAME("Test Slew Up")'], defaultValue: 4};
MERGE (n:KG {id: 'inputs:qix/COIN/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_SERVICE4', modifiers: ['PORT_NAME("Test Slew Down")'], defaultValue: 8};
MERGE (n:KG {id: 'inputs:qix/COIN/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_COIN1', defaultValue: 16};
MERGE (n:KG {id: 'inputs:qix/COIN/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_COIN2', defaultValue: 32};
MERGE (n:KG {id: 'inputs:qix/COIN/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 64, activeLow: true, type: 'IPT_COIN3', defaultValue: 64};
MERGE (n:KG {id: 'inputs:qix/COIN/f7'}) SET n:PortField SET n += {kind: 'bit', mask: 128, activeLow: true, type: 'IPT_TILT', defaultValue: 128};
MERGE (n:KG {id: 'inputs:qix/SPARE'}) SET n:Port SET n += {tag: 'SPARE', modify: false};
MERGE (n:KG {id: 'inputs:qix/SPARE/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 255, activeLow: true, type: 'IPT_UNKNOWN', defaultValue: 255};
MERGE (n:KG {id: 'inputs:qix/IN0'}) SET n:Port SET n += {tag: 'IN0', modify: false};
MERGE (n:KG {id: 'inputs:qix/IN0/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 255, activeLow: true, type: 'IPT_UNKNOWN', defaultValue: 255};
MERGE (n:KG {id: 'inputs:qix/P2'}) SET n:Port SET n += {tag: 'P2', modify: false};
MERGE (n:KG {id: 'inputs:qix/P2/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_UP', modifiers: ['PORT_4WAY', 'PORT_COCKTAIL'], defaultValue: 1};
MERGE (n:KG {id: 'inputs:qix/P2/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_RIGHT', modifiers: ['PORT_4WAY', 'PORT_COCKTAIL'], defaultValue: 2};
MERGE (n:KG {id: 'inputs:qix/P2/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_DOWN', modifiers: ['PORT_4WAY', 'PORT_COCKTAIL'], defaultValue: 4};
MERGE (n:KG {id: 'inputs:qix/P2/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_LEFT', modifiers: ['PORT_4WAY', 'PORT_COCKTAIL'], defaultValue: 8};
MERGE (n:KG {id: 'inputs:qix/P2/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_BUTTON2', modifiers: ['PORT_COCKTAIL'], defaultValue: 16};
MERGE (n:KG {id: 'inputs:qix/P2/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 96, activeLow: true, type: 'IPT_UNKNOWN', defaultValue: 96};
MERGE (n:KG {id: 'inputs:qix/P2/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 128, activeLow: true, type: 'IPT_BUTTON1', modifiers: ['PORT_COCKTAIL'], defaultValue: 128};
MATCH (a:KG {id: 'game:qix'}), (b:KG {id: 'file:src/mame/taito/qix.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 1498, sourceColumn: 1, sourceEndLine: 1498};
MATCH (a:KG {id: 'game:qix'}), (b:KG {id: 'machine:qix_state.qix'}) MERGE (a)-[r:USES_MACHINE]->(b);
MATCH (a:KG {id: 'game:qix'}), (b:KG {id: 'inputs:qix'}) MERGE (a)-[r:USES_INPUTS]->(b);
MATCH (a:KG {id: 'game:qix'}), (b:KG {id: 'romset:qix'}) MERGE (a)-[r:USES_ROMSET]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix.cpp'}), (b:KG {id: 'file:emu.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix.cpp'}), (b:KG {id: 'file:qix.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix.cpp'}), (b:KG {id: 'file:machine/nvram.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix.cpp'}), (b:KG {id: 'file:elecyoyo.lh'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix'}), (b:KG {id: 'file:src/mame/taito/qix.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 668, sourceColumn: 1, sourceEndLine: 672};
MATCH (a:KG {id: 'machine:qix_state.qix'}), (b:KG {id: 'handler:qix_state.video_start'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix'}), (b:KG {id: 'machine:qix_state.qix_base'}) MERGE (a)-[r:CALLS]->(b) SET r += {order: 0};
MATCH (a:KG {id: 'machine:qix_state.qix'}), (b:KG {id: 'machine:qix_state.qix_audio'}) MERGE (a)-[r:CALLS]->(b) SET r += {order: 0};
MATCH (a:KG {id: 'inputs:qix'}), (b:KG {id: 'file:src/mame/taito/qix.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 343, sourceColumn: 8, sourceEndLine: 343};
MATCH (a:KG {id: 'inputs:qix'}), (b:KG {id: 'inputs:qix/P1'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:qix'}), (b:KG {id: 'inputs:qix/COIN'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:qix'}), (b:KG {id: 'inputs:qix/SPARE'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:qix'}), (b:KG {id: 'inputs:qix/IN0'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:qix'}), (b:KG {id: 'inputs:qix/P2'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'romset:qix'}), (b:KG {id: 'file:src/mame/taito/qix.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 763, sourceColumn: 1, sourceEndLine: 763};
MATCH (a:KG {id: 'romset:qix'}), (b:KG {id: 'region:qix/maincpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:qix'}), (b:KG {id: 'region:qix/videocpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:qix'}), (b:KG {id: 'region:qix/audiocpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_base'}), (b:KG {id: 'file:src/mame/taito/qix.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 635, sourceColumn: 1, sourceEndLine: 665};
MATCH (a:KG {id: 'machine:qix_state.qix_base'}), (b:KG {id: 'handler:qix_state.video_start'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_base'}), (b:KG {id: 'machine:qix_state.qix_video'}) MERGE (a)-[r:CALLS]->(b) SET r += {order: 5};
MATCH (a:KG {id: 'machine:qix_state.qix_base'}), (b:KG {id: 'device:qix_state.qix_base/maincpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_base'}), (b:KG {id: 'device:qix_state.qix_base/nvram'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_base'}), (b:KG {id: 'device:qix_state.qix_base/pia0'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_base'}), (b:KG {id: 'device:qix_state.qix_base/pia1'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_base'}), (b:KG {id: 'device:qix_state.qix_base/pia2'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'file:src/mame/taito/qix_a.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 143, sourceColumn: 1, sourceEndLine: 184};
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'handler:qix_state.video_start'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'device:qix_state.qix_audio/audiocpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'device:qix_state.qix_audio/dint'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'device:qix_state.qix_audio/sint'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia0'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia1'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia2'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'device:qix_state.qix_audio/speaker'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_audio'}), (b:KG {id: 'device:qix_state.qix_audio/discrete'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'inputs:qix/P1'}), (b:KG {id: 'inputs:qix/P1/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P1'}), (b:KG {id: 'inputs:qix/P1/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P1'}), (b:KG {id: 'inputs:qix/P1/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P1'}), (b:KG {id: 'inputs:qix/P1/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P1'}), (b:KG {id: 'inputs:qix/P1/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P1'}), (b:KG {id: 'inputs:qix/P1/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P1'}), (b:KG {id: 'inputs:qix/P1/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P1'}), (b:KG {id: 'inputs:qix/P1/f7'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/COIN'}), (b:KG {id: 'inputs:qix/COIN/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/COIN'}), (b:KG {id: 'inputs:qix/COIN/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/COIN'}), (b:KG {id: 'inputs:qix/COIN/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/COIN'}), (b:KG {id: 'inputs:qix/COIN/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/COIN'}), (b:KG {id: 'inputs:qix/COIN/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/COIN'}), (b:KG {id: 'inputs:qix/COIN/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/COIN'}), (b:KG {id: 'inputs:qix/COIN/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/COIN'}), (b:KG {id: 'inputs:qix/COIN/f7'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/SPARE'}), (b:KG {id: 'inputs:qix/SPARE/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/IN0'}), (b:KG {id: 'inputs:qix/IN0/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P2'}), (b:KG {id: 'inputs:qix/P2/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P2'}), (b:KG {id: 'inputs:qix/P2/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P2'}), (b:KG {id: 'inputs:qix/P2/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P2'}), (b:KG {id: 'inputs:qix/P2/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P2'}), (b:KG {id: 'inputs:qix/P2/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P2'}), (b:KG {id: 'inputs:qix/P2/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:qix/P2'}), (b:KG {id: 'inputs:qix/P2/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'region:qix/maincpu'}), (b:KG {id: 'rom:qix/maincpu/qq12_rev2.u12'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/maincpu'}), (b:KG {id: 'rom:qix/maincpu/qq13_rev2.u13'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/maincpu'}), (b:KG {id: 'rom:qix/maincpu/qq14_rev2.u14'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/maincpu'}), (b:KG {id: 'rom:qix/maincpu/qq15_rev2.u15'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/maincpu'}), (b:KG {id: 'rom:qix/maincpu/qq16_rev2.u16'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/maincpu'}), (b:KG {id: 'rom:qix/maincpu/qq17_rev2.u17'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/maincpu'}), (b:KG {id: 'rom:qix/maincpu/qq18_rev2.u18'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/maincpu'}), (b:KG {id: 'rom:qix/maincpu/qq19_rev2.u19'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/videocpu'}), (b:KG {id: 'rom:qix/videocpu/qq4_rev2.u4'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/videocpu'}), (b:KG {id: 'rom:qix/videocpu/qq5_rev2.u5'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/videocpu'}), (b:KG {id: 'rom:qix/videocpu/qq6_rev2.u6'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/videocpu'}), (b:KG {id: 'rom:qix/videocpu/qq7_rev2.u7'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/videocpu'}), (b:KG {id: 'rom:qix/videocpu/qq8_rev2.u8'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/videocpu'}), (b:KG {id: 'rom:qix/videocpu/qq9_rev2.u9'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/videocpu'}), (b:KG {id: 'rom:qix/videocpu/qq10_rev2.u10'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:qix/audiocpu'}), (b:KG {id: 'rom:qix/audiocpu/qq27.u27'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_video'}), (b:KG {id: 'file:src/mame/taito/qix_v.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 367, sourceColumn: 1, sourceEndLine: 388};
MATCH (a:KG {id: 'machine:qix_state.qix_video'}), (b:KG {id: 'handler:qix_state.video_start'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_video'}), (b:KG {id: 'device:qix_state.qix_video/videocpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_video'}), (b:KG {id: 'device:qix_state.qix_video/vid_u18'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_video'}), (b:KG {id: 'device:qix_state.qix_video/screen'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:qix_state.qix_video'}), (b:KG {id: 'device:qix_state.qix_video/palette'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_base/maincpu'}), (b:KG {id: 'map:qix_state.qix_main_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:qix_state.qix_base/pia0'}), (b:KG {id: 'device:qix_state.qix_base/pia0/callback:pia0:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_base/pia0'}), (b:KG {id: 'device:qix_state.qix_base/pia0/callback:pia0:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_base/pia1'}), (b:KG {id: 'device:qix_state.qix_base/pia1/callback:pia1:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_base/pia1'}), (b:KG {id: 'device:qix_state.qix_base/pia1/callback:pia1:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_base/pia2'}), (b:KG {id: 'device:qix_state.qix_base/pia2/callback:pia2:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_base/pia2'}), (b:KG {id: 'device:qix_state.qix_base/pia2/callback:pia2:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix_a.cpp'}), (b:KG {id: 'file:emu.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix_a.cpp'}), (b:KG {id: 'file:qix.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix_a.cpp'}), (b:KG {id: 'file:cpu/m6800/m6800.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix_a.cpp'}), (b:KG {id: 'file:machine/input_merger.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix_a.cpp'}), (b:KG {id: 'file:sound/discrete.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix_a.cpp'}), (b:KG {id: 'file:speaker.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/audiocpu'}), (b:KG {id: 'map:qix_state.audio_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:qix_state.qix_audio/dint'}), (b:KG {id: 'device:qix_state.qix_audio/dint/callback:dint:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sint'}), (b:KG {id: 'device:qix_state.qix_audio/sint/callback:sint:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:2'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:3'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:4'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:5'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:2'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:3'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:4'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia2'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia2'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia2'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:2'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia2'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:3'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/discrete'}), (b:KG {id: 'audioroute:device:qix_state.qix_audio/discrete/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/discrete'}), (b:KG {id: 'audioroute:device:qix_state.qix_audio/discrete/1'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix_v.cpp'}), (b:KG {id: 'file:emu.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/taito/qix_v.cpp'}), (b:KG {id: 'file:qix.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/videocpu'}), (b:KG {id: 'map:qix_state.qix_video_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:qix_state.qix_video/vid_u18'}), (b:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/vid_u18'}), (b:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/vid_u18'}), (b:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:2'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/vid_u18'}), (b:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:3'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/screen'}), (b:KG {id: 'device:qix_state.qix_video/screen/callback:screen:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'file:src/mame/taito/qix.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix.cpp', sourceLine: 279, sourceColumn: 1, sourceEndLine: 291};
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range5'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range6'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range7'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range8'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map'}), (b:KG {id: 'map:qix_state.qix_main_map/range9'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_base/pia2/callback:pia2:1'}), (b:KG {id: 'handler:qix_state.coinctr_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'map:qix_state.audio_map'}), (b:KG {id: 'file:src/mame/taito/qix_a.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix_a.cpp', sourceLine: 128, sourceColumn: 1, sourceEndLine: 133};
MATCH (a:KG {id: 'map:qix_state.audio_map'}), (b:KG {id: 'map:qix_state.audio_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.audio_map'}), (b:KG {id: 'map:qix_state.audio_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.audio_map'}), (b:KG {id: 'map:qix_state.audio_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sint/callback:sint:0'}), (b:KG {id: 'device:qix_state.qix_audio/audiocpu'}) MERGE (a)-[r:TARGETS_DEVICE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:0'}), (b:KG {id: 'handler:qix_state.sync_sndpia1_porta_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:1'}), (b:KG {id: 'handler:qix_state.vol_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:2'}), (b:KG {id: 'handler:pia6821_device.ca1_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:3'}), (b:KG {id: 'handler:qix_state.flip_screen_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:4'}), (b:KG {id: 'handler:input_merger_device.in_w_0'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:4'}), (b:KG {id: 'device:qix_state.qix_audio/dint'}) MERGE (a)-[r:TARGETS_DEVICE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:5'}), (b:KG {id: 'handler:input_merger_device.in_w_1'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia0/callback:sndpia0:5'}), (b:KG {id: 'device:qix_state.qix_audio/dint'}) MERGE (a)-[r:TARGETS_DEVICE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:0'}), (b:KG {id: 'handler:pia6821_device.porta_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:0'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia0'}) MERGE (a)-[r:TARGETS_DEVICE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:1'}), (b:KG {id: 'handler:qix_state.dac_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:2'}), (b:KG {id: 'handler:pia6821_device.ca1_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:2'}), (b:KG {id: 'device:qix_state.qix_audio/sndpia0'}) MERGE (a)-[r:TARGETS_DEVICE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:3'}), (b:KG {id: 'handler:input_merger_device.in_w_0'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:3'}), (b:KG {id: 'device:qix_state.qix_audio/sint'}) MERGE (a)-[r:TARGETS_DEVICE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:4'}), (b:KG {id: 'handler:input_merger_device.in_w_1'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia1/callback:sndpia1:4'}), (b:KG {id: 'device:qix_state.qix_audio/sint'}) MERGE (a)-[r:TARGETS_DEVICE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:0'}), (b:KG {id: 'handler:qix_state.sndpia_2_warning_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:1'}), (b:KG {id: 'handler:qix_state.sndpia_2_warning_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:2'}), (b:KG {id: 'handler:qix_state.sndpia_2_warning_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_audio/sndpia2/callback:sndpia2:3'}), (b:KG {id: 'handler:qix_state.sndpia_2_warning_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'file:src/mame/taito/qix_v.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/taito/qix_v.cpp', sourceLine: 285, sourceColumn: 1, sourceEndLine: 300};
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range5'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range6'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range7'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range8'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range9'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range10'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range11'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map'}), (b:KG {id: 'map:qix_state.qix_video_map/range12'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:0'}), (b:KG {id: 'handler:qix_state.crtc_begin_update'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:1'}), (b:KG {id: 'handler:qix_state.crtc_update_row'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:2'}), (b:KG {id: 'handler:qix_state.display_enable_changed'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/vid_u18/callback:vid_u18:3'}), (b:KG {id: 'handler:qix_state.vsync_changed'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/screen/callback:screen:0'}), (b:KG {id: 'handler:mc6845_device.screen_update'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:qix_state.qix_video/screen/callback:screen:0'}), (b:KG {id: 'device:qix_state.qix_video/vid_u18'}) MERGE (a)-[r:TARGETS_DEVICE]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range3'}), (b:KG {id: 'handler:qix_state.video_firq_r'}) MERGE (a)-[r:READS]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range3'}), (b:KG {id: 'handler:qix_state.video_firq_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range4'}), (b:KG {id: 'handler:qix_state.data_firq_ack_r'}) MERGE (a)-[r:READS]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range4'}), (b:KG {id: 'handler:qix_state.data_firq_ack_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range5'}), (b:KG {id: 'handler:pia6821_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'sndpia0'};
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range5'}), (b:KG {id: 'handler:pia6821_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'sndpia0'};
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range6'}), (b:KG {id: 'handler:pia6821_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'pia0'};
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range6'}), (b:KG {id: 'handler:qix_state.pia_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range7'}), (b:KG {id: 'handler:pia6821_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'pia1'};
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range7'}), (b:KG {id: 'handler:pia6821_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'pia1'};
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range8'}), (b:KG {id: 'handler:pia6821_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'pia2'};
MATCH (a:KG {id: 'map:qix_state.qix_main_map/range8'}), (b:KG {id: 'handler:pia6821_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'pia2'};
MATCH (a:KG {id: 'map:qix_state.audio_map/range0'}), (b:KG {id: 'handler:pia6821_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'sndpia2'};
MATCH (a:KG {id: 'map:qix_state.audio_map/range0'}), (b:KG {id: 'handler:pia6821_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'sndpia2'};
MATCH (a:KG {id: 'map:qix_state.audio_map/range1'}), (b:KG {id: 'handler:pia6821_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'sndpia1'};
MATCH (a:KG {id: 'map:qix_state.audio_map/range1'}), (b:KG {id: 'handler:pia6821_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'sndpia1'};
MATCH (a:KG {id: 'handler:qix_state.sync_sndpia1_porta_w'}), (b:KG {id: 'handler:qix_state.deferred_sndpia1_porta_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range0'}), (b:KG {id: 'handler:qix_state.videoram_r'}) MERGE (a)-[r:READS]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range0'}), (b:KG {id: 'handler:qix_state.videoram_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range3'}), (b:KG {id: 'handler:qix_state.palettebank_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range4'}), (b:KG {id: 'handler:qix_state.data_firq_r'}) MERGE (a)-[r:READS]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range4'}), (b:KG {id: 'handler:qix_state.data_firq_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range5'}), (b:KG {id: 'handler:qix_state.video_firq_ack_r'}) MERGE (a)-[r:READS]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range5'}), (b:KG {id: 'handler:qix_state.video_firq_ack_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range6'}), (b:KG {id: 'handler:qix_state.paletteram_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range7'}), (b:KG {id: 'handler:qix_state.addresslatch_r'}) MERGE (a)-[r:READS]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range7'}), (b:KG {id: 'handler:qix_state.addresslatch_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range10'}), (b:KG {id: 'handler:mc6845_device.address_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'vid_u18'};
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range11'}), (b:KG {id: 'handler:mc6845_device.register_r'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'vid_u18'};
MATCH (a:KG {id: 'map:qix_state.qix_video_map/range11'}), (b:KG {id: 'handler:mc6845_device.register_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'vid_u18'};
MATCH (a:KG {id: 'handler:qix_state.pia_w'}), (b:KG {id: 'handler:qix_state.pia_w_callback'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
