import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface GeneratedNesPlan {
  schemaVersion: 1;
  sourceFiles: string[];
  sourceDigest: string;
  mapperSlots: Record<number, string>;
  ppu: {
    type: 'PPU_2C02';
    width: number;
    visibleLines: number;
    totalLines: number;
  };
  apu: {
    clockDivider: number;
    noisePeriods: number[];
    dmcPeriods: number[];
  };
}

const SOURCE_FILES = [
  'src/devices/video/ppu2c0x.cpp',
  'src/devices/video/ppu2c0x.h',
  'src/devices/sound/nes_apu.cpp',
  'src/devices/sound/nes_apu.h',
  'src/devices/sound/nes_defs.h',
  'src/devices/bus/nes/nes_slot.cpp',
  'src/devices/bus/nes/nes_slot.h',
  'src/devices/bus/nes/nxrom.cpp',
  'src/devices/bus/nes/mmc1.cpp',
  'src/devices/bus/nes/mmc3.cpp',
  'src/devices/bus/nes_ctrl/ctrl.cpp',
  'src/devices/bus/nes_ctrl/joypad.cpp',
] as const;

const TEMPLATES = ['cart', 'ppu', 'apu', 'worklet', 'board'] as const;

/**
 * Lower the NES device family into browser artifacts.
 *
 * The output is deliberately generated beside the other device artifacts.
 * Nothing under src/runtime implements NES hardware. These compact TypeScript
 * templates are the browser backend for behavior traced to the MAME sources
 * above, in the same way audio-compiler emits a worklet backend from its plan.
 */
export function compileNesHardware(mameSrc: string): {
  plan: GeneratedNesPlan;
  artifacts: Record<(typeof TEMPLATES)[number], string>;
} {
  const sources = Object.fromEntries(SOURCE_FILES.map(file => [
    file,
    readFileSync(join(mameSrc, file), 'utf8'),
  ]));
  requireSource(sources[SOURCE_FILES[0]], 'DEFINE_DEVICE_TYPE(PPU_2C02');
  requireSource(sources['src/devices/sound/nes_apu.cpp'], 'nesapu_device::write');
  requireSource(sources['src/devices/bus/nes/nes_slot.cpp'], 'NES_CART_SLOT');
  requireSource(sources['src/devices/bus/nes/nxrom.cpp'], 'nes_nrom_device');
  requireSource(sources['src/devices/bus/nes/mmc1.cpp'], 'nes_sxrom_device');
  requireSource(sources['src/devices/bus/nes/mmc3.cpp'], 'nes_txrom_device');
  requireSource(sources['src/devices/bus/nes_ctrl/joypad.cpp'], 'read_bit0');

  const definitions = sources['src/devices/sound/nes_defs.h'];
  const tables = [...definitions.matchAll(
    /static const int (noise_freq|dpcm_clocks)\[2\]\[16\]\s*=\s*\{\s*\{([^}]+)\}/g,
  )].reduce<Record<string, number[]>>((result, match) => {
    result[match[1]!] = [...match[2]!.matchAll(/\d+/g)].map(value => Number(value[0]));
    return result;
  }, {});
  if (tables.noise_freq?.length !== 16 || tables.dpcm_clocks?.length !== 16) {
    throw new Error('NES APU period tables no longer match MAME’s 16-entry NTSC layout');
  }

  const digest = createHash('sha256');
  for (const file of SOURCE_FILES) digest.update(file).update('\0').update(sources[file]);
  const plan: GeneratedNesPlan = {
    schemaVersion: 1,
    sourceFiles: [...SOURCE_FILES],
    sourceDigest: digest.digest('hex'),
    mapperSlots: { 0: 'nrom', 1: 'sxrom', 2: 'uxrom', 3: 'cnrom', 4: 'txrom' },
    ppu: { type: 'PPU_2C02', width: 256, visibleLines: 240, totalLines: 262 },
    apu: {
      clockDivider: 2,
      noisePeriods: tables.noise_freq,
      dmcPeriods: tables.dpcm_clocks,
    },
  };
  const provenance = `// Generated by mamekit from MAME (${plan.sourceDigest.slice(0, 16)}).\n` +
    `// Sources: ${plan.sourceFiles.join(', ')}\n`;
  const artifacts = Object.fromEntries(TEMPLATES.map(name => [
    name,
    provenance + readFileSync(new URL(`./nes-runtime-templates/${name}.ts.txt`, import.meta.url), 'utf8'),
  ])) as Record<(typeof TEMPLATES)[number], string>;
  artifacts.apu = replaceNumberTable(
    artifacts.apu,
    'NES_NOISE_PERIODS',
    plan.apu.noisePeriods,
  );
  artifacts.apu = replaceNumberTable(
    artifacts.apu,
    'NES_DMC_RATES',
    plan.apu.dmcPeriods,
  );
  return { plan, artifacts };
}

function requireSource(source: string, token: string): void {
  if (!source.includes(token)) {
    throw new Error(`NES source lowering expected MAME token ${JSON.stringify(token)}`);
  }
}

function replaceNumberTable(source: string, name: string, values: number[]): string {
  const pattern = new RegExp(
    `(export const ${name}: readonly number\\[\\] = \\[)[\\s\\S]*?(\\n\\];)`,
  );
  if (!pattern.test(source)) throw new Error(`NES artifact backend is missing table ${name}`);
  return source.replace(pattern, `$1\n  ${values.join(', ')},$2`);
}
