import assert from 'node:assert/strict';
import { compileNesHardware } from './nes-compiler.ts';

const generated = compileNesHardware(process.env.MAME_SRC ?? '../mame');

assert.equal(generated.plan.schemaVersion, 1);
assert.equal(generated.plan.ppu.type, 'PPU_2C02');
assert.equal(generated.plan.ppu.width, 256);
assert.equal(generated.plan.ppu.visibleLines, 240);
assert.equal(generated.plan.apu.noisePeriods.length, 16);
assert.equal(generated.plan.apu.dmcPeriods.length, 16);
assert.deepEqual(generated.plan.mapperSlots, {
  0: 'nrom',
  1: 'sxrom',
  2: 'uxrom',
  3: 'cnrom',
  4: 'txrom',
});
assert.match(generated.artifacts.board, /createCpu\('RP2A03'/);
assert.match(generated.artifacts.board, /new NesBoard/);
assert.match(generated.artifacts.ppu, /class NesPpu/);
assert.match(generated.artifacts.apu, /class NesApu/);
assert.match(generated.artifacts.worklet, /registerProcessor\('nes'/);
for (const artifact of Object.values(generated.artifacts)) {
  assert.match(artifact, /Generated by mamekit from MAME/);
  assert.match(artifact, /src\/devices\/video\/ppu2c0x\.cpp/);
}

console.log('nes-compiler.spec: source-validated NES composition and five mapper plan passed');
