// mamekit knowledge graph — driver src/mame/capcom/gng.cpp
// generated 2026-07-30T09:33:50.361Z
CREATE CONSTRAINT mamekit_id IF NOT EXISTS FOR (n:KG) REQUIRE n.id IS UNIQUE;
MERGE (n:KG {id: 'file:src/mame/capcom/gng.cpp'}) SET n:SourceFile SET n += {path: 'src/mame/capcom/gng.cpp'};
MERGE (n:KG {id: 'file:emu.h'}) SET n:SourceFile SET n += {path: 'emu.h', external: true};
MERGE (n:KG {id: 'file:cpu/m6809/m6809.h'}) SET n:SourceFile SET n += {path: 'cpu/m6809/m6809.h', external: true};
MERGE (n:KG {id: 'file:cpu/z80/z80.h'}) SET n:SourceFile SET n += {path: 'cpu/z80/z80.h', external: true};
MERGE (n:KG {id: 'file:machine/74259.h'}) SET n:SourceFile SET n += {path: 'machine/74259.h', external: true};
MERGE (n:KG {id: 'file:machine/gen_latch.h'}) SET n:SourceFile SET n += {path: 'machine/gen_latch.h', external: true};
MERGE (n:KG {id: 'file:sound/ymopn.h'}) SET n:SourceFile SET n += {path: 'sound/ymopn.h', external: true};
MERGE (n:KG {id: 'file:video/bufsprite.h'}) SET n:SourceFile SET n += {path: 'video/bufsprite.h', external: true};
MERGE (n:KG {id: 'file:emupal.h'}) SET n:SourceFile SET n += {path: 'emupal.h', external: true};
MERGE (n:KG {id: 'file:screen.h'}) SET n:SourceFile SET n += {path: 'screen.h', external: true};
MERGE (n:KG {id: 'file:speaker.h'}) SET n:SourceFile SET n += {path: 'speaker.h', external: true};
MERGE (n:KG {id: 'file:tilemap.h'}) SET n:SourceFile SET n += {path: 'tilemap.h', external: true};
MERGE (n:KG {id: 'game:gng'}) SET n:Game SET n += {name: 'gng', year: '1985', company: 'Capcom', fullname: 'Ghosts\'n Goblins (World? set 1)', monitor: 'ROT0', cls: 'gng_state', init: 'empty_init', flags: 'MACHINE_SUPPORTS_SAVE', kind: 'arcade', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 1162, sourceColumn: 1, sourceEndLine: 1162};
MERGE (n:KG {id: 'romset:gng'}) SET n:RomSet SET n += {name: 'gng', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 636, sourceColumn: 1, sourceEndLine: 636};
MERGE (n:KG {id: 'region:gng/maincpu'}) SET n:RomRegion SET n += {tag: 'maincpu', size: 98304, flags: '0', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 637, sourceColumn: 2, sourceEndLine: 637};
MERGE (n:KG {id: 'rom:gng/maincpu/mm_c_04'}) SET n:Rom SET n += {file: 'mm_c_04', offset: 16384, size: 16384, crc: '4f94130f', sha1: '6863fee3c97c76ba314ccbada7efacb6783e7d32', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 638, sourceColumn: 2, sourceEndLine: 638};
MERGE (n:KG {id: 'rom:gng/maincpu/mm_c_03'}) SET n:Rom SET n += {file: 'mm_c_03', offset: 32768, size: 32768, crc: '1def138a', sha1: 'd29e12082c4d5c06a9910b3500ef66242cdec905', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 639, sourceColumn: 2, sourceEndLine: 639};
MERGE (n:KG {id: 'rom:gng/maincpu/mm_c_05'}) SET n:Rom SET n += {file: 'mm_c_05', offset: 65536, size: 32768, crc: 'ed28e86e', sha1: '064871918547a56be330c6994d4db2c9932e14db', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 640, sourceColumn: 2, sourceEndLine: 640};
MERGE (n:KG {id: 'region:gng/audiocpu'}) SET n:RomRegion SET n += {tag: 'audiocpu', size: 65536, flags: '0', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 642, sourceColumn: 2, sourceEndLine: 642};
MERGE (n:KG {id: 'rom:gng/audiocpu/gg2.bin'}) SET n:Rom SET n += {file: 'gg2.bin', offset: 0, size: 32768, crc: '615f5b6f', sha1: '7ef9ec5c2072e21c787a6bbf700033f50c759c1d', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 643, sourceColumn: 2, sourceEndLine: 643};
MERGE (n:KG {id: 'region:gng/chars'}) SET n:RomRegion SET n += {tag: 'chars', size: 16384, flags: '0', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 645, sourceColumn: 2, sourceEndLine: 645};
MERGE (n:KG {id: 'rom:gng/chars/gg1.bin'}) SET n:Rom SET n += {file: 'gg1.bin', offset: 0, size: 16384, crc: 'ecfccf07', sha1: '0a1518e19a2e0a4cc3dde4b9568202ea911b5ece', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 646, sourceColumn: 2, sourceEndLine: 646};
MERGE (n:KG {id: 'region:gng/tiles'}) SET n:RomRegion SET n += {tag: 'tiles', size: 98304, flags: '0', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 648, sourceColumn: 2, sourceEndLine: 648};
MERGE (n:KG {id: 'rom:gng/tiles/gg11.bin'}) SET n:Rom SET n += {file: 'gg11.bin', offset: 0, size: 16384, crc: 'ddd56fa9', sha1: 'f9d77eee5e2738b7e83ba02fcc55dd480391479f', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 649, sourceColumn: 2, sourceEndLine: 649};
MERGE (n:KG {id: 'rom:gng/tiles/gg10.bin'}) SET n:Rom SET n += {file: 'gg10.bin', offset: 16384, size: 16384, crc: '7302529d', sha1: '8434c994cc55d2586641f3b90b6b15fd65dfb67c', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 650, sourceColumn: 2, sourceEndLine: 650};
MERGE (n:KG {id: 'rom:gng/tiles/gg9.bin'}) SET n:Rom SET n += {file: 'gg9.bin', offset: 32768, size: 16384, crc: '20035bda', sha1: 'bbb1fba0eb19471f66d29526fa8423ccb047bd63', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 651, sourceColumn: 2, sourceEndLine: 651};
MERGE (n:KG {id: 'rom:gng/tiles/gg8.bin'}) SET n:Rom SET n += {file: 'gg8.bin', offset: 49152, size: 16384, crc: 'f12ba271', sha1: '1c42fa02cb27b35d10c3f7f036005e747f9f6b79', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 652, sourceColumn: 2, sourceEndLine: 652};
MERGE (n:KG {id: 'rom:gng/tiles/gg7.bin'}) SET n:Rom SET n += {file: 'gg7.bin', offset: 65536, size: 16384, crc: 'e525207d', sha1: '1947f159189b3a53f1251d8653b6e7c65c91fc3c', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 653, sourceColumn: 2, sourceEndLine: 653};
MERGE (n:KG {id: 'rom:gng/tiles/gg6.bin'}) SET n:Rom SET n += {file: 'gg6.bin', offset: 81920, size: 16384, crc: '2d77e9b2', sha1: '944da1ce29a18bf0fc8deff78bceacba0bf23a07', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 654, sourceColumn: 2, sourceEndLine: 654};
MERGE (n:KG {id: 'region:gng/sprites'}) SET n:RomRegion SET n += {tag: 'sprites', size: 131072, flags: 'ROMREGION_ERASEFF', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 656, sourceColumn: 2, sourceEndLine: 656};
MERGE (n:KG {id: 'rom:gng/sprites/gg17.bin'}) SET n:Rom SET n += {file: 'gg17.bin', offset: 0, size: 16384, crc: '93e50a8f', sha1: '42d367f57bb2fdf60a0445ac1533da99cfeaa617', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 657, sourceColumn: 2, sourceEndLine: 657};
MERGE (n:KG {id: 'rom:gng/sprites/gg16.bin'}) SET n:Rom SET n += {file: 'gg16.bin', offset: 16384, size: 16384, crc: '06d7e5ca', sha1: '9e06012bcd82f98fad43de666ef9a75979d940ab', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 658, sourceColumn: 2, sourceEndLine: 658};
MERGE (n:KG {id: 'rom:gng/sprites/gg15.bin'}) SET n:Rom SET n += {file: 'gg15.bin', offset: 32768, size: 16384, crc: 'bc1fe02d', sha1: 'e3a1421d465b87148ffa94f5673b2307f0246afe', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 659, sourceColumn: 2, sourceEndLine: 659};
MERGE (n:KG {id: 'rom:gng/sprites/gg14.bin'}) SET n:Rom SET n += {file: 'gg14.bin', offset: 65536, size: 16384, crc: '6aaf12f9', sha1: '207a7407288182a4f3eddaea634c6a6452131182', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 660, sourceColumn: 2, sourceEndLine: 660};
MERGE (n:KG {id: 'rom:gng/sprites/gg13.bin'}) SET n:Rom SET n += {file: 'gg13.bin', offset: 81920, size: 16384, crc: 'e80c3fca', sha1: 'cb641c25bb04b970b2cbeca41adb792bbe142fb5', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 661, sourceColumn: 2, sourceEndLine: 661};
MERGE (n:KG {id: 'rom:gng/sprites/gg12.bin'}) SET n:Rom SET n += {file: 'gg12.bin', offset: 98304, size: 16384, crc: '7780a925', sha1: '3f129ca6d695548b659955fe538584bd9ac2ff17', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 662, sourceColumn: 2, sourceEndLine: 662};
MERGE (n:KG {id: 'region:gng/proms'}) SET n:RomRegion SET n += {tag: 'proms', size: 512, flags: '0', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 664, sourceColumn: 2, sourceEndLine: 664};
MERGE (n:KG {id: 'rom:gng/proms/tbp24s10.14k'}) SET n:Rom SET n += {file: 'tbp24s10.14k', offset: 0, size: 256, crc: '0eaf5158', sha1: 'bafd4108708f66cd7b280e47152b108f3e254fc9', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 665, sourceColumn: 2, sourceEndLine: 665};
MERGE (n:KG {id: 'rom:gng/proms/63s141.2e'}) SET n:Rom SET n += {file: '63s141.2e', offset: 256, size: 256, crc: '4a1285a4', sha1: '5018c3950b675af58db499e2883ecbc55419b491', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 666, sourceColumn: 2, sourceEndLine: 666};
MERGE (n:KG {id: 'region:gng/plds'}) SET n:RomRegion SET n += {tag: 'plds', size: 256, flags: '0', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 668, sourceColumn: 2, sourceEndLine: 668};
MERGE (n:KG {id: 'rom:gng/plds/gg-pal10l8.bin'}) SET n:Rom SET n += {file: 'gg-pal10l8.bin', offset: 0, size: 44, crc: '87f1b7e0', sha1: 'b719c3be7bd4a02660bb0887f752e9769cbd37d2', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 669, sourceColumn: 2, sourceEndLine: 669};
MERGE (n:KG {id: 'map:gng_state.gng_main_map'}) SET n:AddressMap SET n += {cls: 'gng_state', name: 'gng_main_map', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 256, sourceColumn: 1, sourceEndLine: 277};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 7679, raw: 'map(0x0000, 0x1dff).ram()', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 258, sourceColumn: 2, sourceEndLine: 258, ram: true};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range1'}) SET n:AddressRange SET n += {start: 7680, end: 8191, raw: 'map(0x1e00, 0x1fff).ram().share("spriteram")', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 259, sourceColumn: 2, sourceEndLine: 259, ram: true, share: 'spriteram'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range2'}) SET n:AddressRange SET n += {start: 8192, end: 10239, raw: 'map(0x2000, 0x27ff).ram().w(FUNC(gng_state::fgvideoram_w)).share(m_fgvideoram)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 260, sourceColumn: 2, sourceEndLine: 260, ram: true, share: 'fgvideoram'};
MERGE (n:KG {id: 'handler:gng_state.fgvideoram_w'}) SET n:Handler SET n += {method: 'fgvideoram_w', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 162, sourceColumn: 1, sourceEndLine: 166, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_fgvideoram[offset] = data;
	m_fg_tilemap->mark_tile_dirty(offset & 0x3ff);'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range3'}) SET n:AddressRange SET n += {start: 10240, end: 12287, raw: 'map(0x2800, 0x2fff).ram().w(FUNC(gng_state::bgvideoram_w)).share(m_bgvideoram)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 261, sourceColumn: 2, sourceEndLine: 261, ram: true, share: 'bgvideoram'};
MERGE (n:KG {id: 'handler:gng_state.bgvideoram_w'}) SET n:Handler SET n += {method: 'bgvideoram_w', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 168, sourceColumn: 1, sourceEndLine: 172, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_bgvideoram[offset] = data;
	m_bg_tilemap->mark_tile_dirty(offset & 0x3ff);'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range4'}) SET n:AddressRange SET n += {start: 12288, end: 12288, raw: 'map(0x3000, 0x3000).portr("SYSTEM")', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 262, sourceColumn: 2, sourceEndLine: 262, portRead: 'SYSTEM'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range5'}) SET n:AddressRange SET n += {start: 12289, end: 12289, raw: 'map(0x3001, 0x3001).portr("P1")', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 263, sourceColumn: 2, sourceEndLine: 263, portRead: 'P1'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range6'}) SET n:AddressRange SET n += {start: 12290, end: 12290, raw: 'map(0x3002, 0x3002).portr("P2")', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 264, sourceColumn: 2, sourceEndLine: 264, portRead: 'P2'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range7'}) SET n:AddressRange SET n += {start: 12291, end: 12291, raw: 'map(0x3003, 0x3003).portr("DSW1")', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 265, sourceColumn: 2, sourceEndLine: 265, portRead: 'DSW1'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range8'}) SET n:AddressRange SET n += {start: 12292, end: 12292, raw: 'map(0x3004, 0x3004).portr("DSW2")', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 266, sourceColumn: 2, sourceEndLine: 266, portRead: 'DSW2'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range9'}) SET n:AddressRange SET n += {start: 14336, end: 14591, raw: 'map(0x3800, 0x38ff).w(m_palette, FUNC(palette_device::write8_ext)).share("palette_ext")', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 267, sourceColumn: 2, sourceEndLine: 267, share: 'palette_ext'};
MERGE (n:KG {id: 'handler:palette_device.write8_ext'}) SET n:Handler SET n += {method: 'write8_ext', ownerClass: 'palette_device', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 291, sourceColumn: 2, sourceEndLine: 291};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range10'}) SET n:AddressRange SET n += {start: 14592, end: 14847, raw: 'map(0x3900, 0x39ff).w(m_palette, FUNC(palette_device::write8)).share("palette")', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 268, sourceColumn: 2, sourceEndLine: 268, share: 'palette'};
MERGE (n:KG {id: 'handler:palette_device.write8'}) SET n:Handler SET n += {method: 'write8', ownerClass: 'palette_device', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 292, sourceColumn: 2, sourceEndLine: 292};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range11'}) SET n:AddressRange SET n += {start: 14848, end: 14848, raw: 'map(0x3a00, 0x3a00).w("soundlatch", FUNC(generic_latch_8_device::write))', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 269, sourceColumn: 2, sourceEndLine: 269};
MERGE (n:KG {id: 'handler:generic_latch_8_device.write'}) SET n:Handler SET n += {method: 'write', ownerClass: 'generic_latch_8_device', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 293, sourceColumn: 2, sourceEndLine: 293};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range12'}) SET n:AddressRange SET n += {start: 15112, end: 15113, raw: 'map(0x3b08, 0x3b09).w(FUNC(gng_state::bgscrollx_w))', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 270, sourceColumn: 2, sourceEndLine: 270};
MERGE (n:KG {id: 'handler:gng_state.bgscrollx_w'}) SET n:Handler SET n += {method: 'bgscrollx_w', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 175, sourceColumn: 1, sourceEndLine: 179, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_scrollx[offset] = data;
	m_bg_tilemap->set_scrollx(0, m_scrollx[0] + 256 * m_scrollx[1]);'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range13'}) SET n:AddressRange SET n += {start: 15114, end: 15115, raw: 'map(0x3b0a, 0x3b0b).w(FUNC(gng_state::bgscrolly_w))', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 271, sourceColumn: 2, sourceEndLine: 271};
MERGE (n:KG {id: 'handler:gng_state.bgscrolly_w'}) SET n:Handler SET n += {method: 'bgscrolly_w', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 181, sourceColumn: 1, sourceEndLine: 185, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_scrolly[offset] = data;
	m_bg_tilemap->set_scrolly(0, m_scrolly[0] + 256 * m_scrolly[1]);'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range14'}) SET n:AddressRange SET n += {start: 15360, end: 15360, raw: 'map(0x3c00, 0x3c00).w(m_spriteram, FUNC(buffered_spriteram8_device::write))', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 272, sourceColumn: 2, sourceEndLine: 272};
MERGE (n:KG {id: 'handler:buffered_spriteram8_device.write'}) SET n:Handler SET n += {method: 'write', ownerClass: 'buffered_spriteram8_device', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 296, sourceColumn: 2, sourceEndLine: 296};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range15'}) SET n:AddressRange SET n += {start: 15616, end: 15623, raw: 'map(0x3d00, 0x3d07).w("mainlatch", FUNC(ls259_device::write_d0))', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 273, sourceColumn: 2, sourceEndLine: 273};
MERGE (n:KG {id: 'handler:ls259_device.write_d0'}) SET n:Handler SET n += {method: 'write_d0', ownerClass: 'ls259_device', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 273, sourceColumn: 2, sourceEndLine: 273};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range16'}) SET n:AddressRange SET n += {start: 15872, end: 15872, raw: 'map(0x3e00, 0x3e00).w(FUNC(gng_state::bankswitch_w))', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 274, sourceColumn: 2, sourceEndLine: 274};
MERGE (n:KG {id: 'handler:gng_state.bankswitch_w'}) SET n:Handler SET n += {method: 'bankswitch_w', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 234, sourceColumn: 1, sourceEndLine: 240, sourceParameters: 'uint8_t data', sourceBody: 'if (data == 4)
		m_mainbank->set_entry(4);
	else
		m_mainbank->set_entry(data & 0x03);'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range17'}) SET n:AddressRange SET n += {start: 16384, end: 24575, raw: 'map(0x4000, 0x5fff).bankr(m_mainbank)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 275, sourceColumn: 2, sourceEndLine: 275, bankRead: 'mainbank'};
MERGE (n:KG {id: 'map:gng_state.gng_main_map/range18'}) SET n:AddressRange SET n += {start: 24576, end: 65535, raw: 'map(0x6000, 0xffff).rom()', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 276, sourceColumn: 2, sourceEndLine: 276, rom: true};
MERGE (n:KG {id: 'map:gng_state.sound_map'}) SET n:AddressMap SET n += {cls: 'gng_state', name: 'sound_map', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 308, sourceColumn: 1, sourceEndLine: 315};
MERGE (n:KG {id: 'map:gng_state.sound_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 32767, raw: 'map(0x0000, 0x7fff).rom()', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 310, sourceColumn: 2, sourceEndLine: 310, rom: true};
MERGE (n:KG {id: 'map:gng_state.sound_map/range1'}) SET n:AddressRange SET n += {start: 49152, end: 51199, raw: 'map(0xc000, 0xc7ff).ram()', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 311, sourceColumn: 2, sourceEndLine: 311, ram: true};
MERGE (n:KG {id: 'map:gng_state.sound_map/range2'}) SET n:AddressRange SET n += {start: 51200, end: 51200, raw: 'map(0xc800, 0xc800).r("soundlatch", FUNC(generic_latch_8_device::read))', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 312, sourceColumn: 2, sourceEndLine: 312};
MERGE (n:KG {id: 'handler:generic_latch_8_device.read'}) SET n:Handler SET n += {method: 'read', ownerClass: 'generic_latch_8_device', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 312, sourceColumn: 2, sourceEndLine: 312};
MERGE (n:KG {id: 'map:gng_state.sound_map/range3'}) SET n:AddressRange SET n += {start: 57344, end: 57345, raw: 'map(0xe000, 0xe001).w("ym1", FUNC(ym2203_device::write))', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 313, sourceColumn: 2, sourceEndLine: 313};
MERGE (n:KG {id: 'handler:ym2203_device.write'}) SET n:Handler SET n += {method: 'write', ownerClass: 'ym2203_device', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 314, sourceColumn: 2, sourceEndLine: 314};
MERGE (n:KG {id: 'map:gng_state.sound_map/range4'}) SET n:AddressRange SET n += {start: 57346, end: 57347, raw: 'map(0xe002, 0xe003).w("ym2", FUNC(ym2203_device::write))', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 314, sourceColumn: 2, sourceEndLine: 314};
MERGE (n:KG {id: 'machine:gng_state.gng'}) SET n:MachineConfig SET n += {cls: 'gng_state', name: 'gng', calls: [], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 572, sourceColumn: 1, sourceEndLine: 618};
MERGE (n:KG {id: 'bank:gng_state.gng/mainbank/0'}) SET n:MemoryBank SET n += {tag: 'mainbank', member: 'm_mainbank', startEntry: 0, entries: 4, region: 'maincpu', offset: 65536, stride: 8192, raw: 'm_mainbank->configure_entries(0, 4, &rombase[0x10000], 0x2000)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 540, sourceColumn: 1, sourceEndLine: 548};
MERGE (n:KG {id: 'bank:gng_state.gng/mainbank/1'}) SET n:MemoryBank SET n += {tag: 'mainbank', member: 'm_mainbank', startEntry: 4, entries: 1, region: 'maincpu', offset: 16384, stride: 0, raw: 'm_mainbank->configure_entry(4, &rombase[0x4000])', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 540, sourceColumn: 1, sourceEndLine: 548};
MERGE (n:KG {id: 'device:gng_state.gng/maincpu'}) SET n:Device SET n += {type: 'MC6809', tag: 'maincpu', clock: 6000000, config: ['MC6809(config, m_maincpu, XTAL(12\'000\'000) / 2)', 'm_maincpu->set_addrmap(AS_PROGRAM, &gng_state::gng_main_map)', 'm_maincpu->set_vblank_int("screen", FUNC(gng_state::irq0_line_hold))'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 575, sourceColumn: 2, sourceEndLine: 575};
MERGE (n:KG {id: 'device:gng_state.gng/maincpu/callback0'}) SET n:Callback SET n += {signal: 'set_vblank_int', operation: 'set_vblank_int', raw: 'm_maincpu->set_vblank_int("screen", FUNC(gng_state::irq0_line_hold))', ownerTag: 'maincpu', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 577, sourceColumn: 2, sourceEndLine: 577, targetTag: 'screen', targetClass: 'gng_state', targetMethod: 'irq0_line_hold'};
MERGE (n:KG {id: 'handler:gng_state.irq0_line_hold'}) SET n:Handler SET n += {method: 'irq0_line_hold', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 581, sourceColumn: 2, sourceEndLine: 581};
MERGE (n:KG {id: 'device:gng_state.gng/audiocpu'}) SET n:Device SET n += {type: 'Z80', tag: 'audiocpu', clock: 3000000, config: ['z80_device &audiocpu(Z80(config, "audiocpu", XTAL(12\'000\'000) / 4))', 'audiocpu.set_addrmap(AS_PROGRAM, &gng_state::sound_map)', 'audiocpu.set_periodic_int(FUNC(gng_state::irq0_line_hold), attotime::from_hz(4 * 60))'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 579, sourceColumn: 2, sourceEndLine: 579};
MERGE (n:KG {id: 'device:gng_state.gng/audiocpu/callback0'}) SET n:Callback SET n += {signal: 'set_periodic_int', operation: 'set_periodic_int', raw: 'audiocpu.set_periodic_int(FUNC(gng_state::irq0_line_hold), attotime::from_hz(4 * 60))', ownerTag: 'audiocpu', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 581, sourceColumn: 2, sourceEndLine: 581, periodHz: 240, periodExpr: 'attotime::from_hz(4 * 60)', targetClass: 'gng_state', targetMethod: 'irq0_line_hold'};
MERGE (n:KG {id: 'device:gng_state.gng/mainlatch'}) SET n:Device SET n += {type: 'LS259', tag: 'mainlatch', clock: null, config: ['ls259_device &mainlatch(LS259(config, "mainlatch"))', 'mainlatch.q_out_cb<0>().set(FUNC(gng_state::flip_screen_set)).invert()', 'mainlatch.q_out_cb<1>().set_inputline("audiocpu", INPUT_LINE_RESET).invert()', 'mainlatch.q_out_cb<1>().append(FUNC(gng_state::ym_reset_w))', 'mainlatch.q_out_cb<2>().set([this] (int state) { machine().bookkeeping().coin_counter_w(0, state); })', 'mainlatch.q_out_cb<3>().set([this] (int state) { machine().bookkeeping().coin_counter_w(1, state); })'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 583, sourceColumn: 2, sourceEndLine: 583};
MERGE (n:KG {id: 'device:gng_state.gng/mainlatch/callback0'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set', raw: 'mainlatch.q_out_cb<0>().set(FUNC(gng_state::flip_screen_set)).invert()', ownerTag: 'mainlatch', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 584, sourceColumn: 2, sourceEndLine: 584, slot: '0', transforms: ['invert'], targetClass: 'gng_state', targetMethod: 'flip_screen_set'};
MERGE (n:KG {id: 'handler:gng_state.flip_screen_set'}) SET n:Handler SET n += {method: 'flip_screen_set', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 584, sourceColumn: 2, sourceEndLine: 584};
MERGE (n:KG {id: 'device:gng_state.gng/mainlatch/callback1'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set_inputline', raw: 'mainlatch.q_out_cb<1>().set_inputline("audiocpu", INPUT_LINE_RESET).invert()', ownerTag: 'mainlatch', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 585, sourceColumn: 2, sourceEndLine: 585, slot: '1', transforms: ['invert'], targetTag: 'audiocpu', inputLine: 'INPUT_LINE_RESET'};
MERGE (n:KG {id: 'device:gng_state.gng/mainlatch/callback2'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'append', raw: 'mainlatch.q_out_cb<1>().append(FUNC(gng_state::ym_reset_w))', ownerTag: 'mainlatch', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 586, sourceColumn: 2, sourceEndLine: 586, slot: '1', targetClass: 'gng_state', targetMethod: 'ym_reset_w'};
MERGE (n:KG {id: 'handler:gng_state.ym_reset_w'}) SET n:Handler SET n += {method: 'ym_reset_w', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 242, sourceColumn: 1, sourceEndLine: 249, sourceParameters: 'int state', sourceBody: 'if (!state)
	{
		m_ym[0]->reset();
		m_ym[1]->reset();
	}'};
MERGE (n:KG {id: 'device:gng_state.gng/spriteram'}) SET n:Device SET n += {type: 'BUFFERED_SPRITERAM8', tag: 'spriteram', clock: null, config: ['BUFFERED_SPRITERAM8(config, m_spriteram)'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 591, sourceColumn: 2, sourceEndLine: 591};
MERGE (n:KG {id: 'device:gng_state.gng/screen'}) SET n:Device SET n += {type: 'SCREEN', tag: 'screen', clock: null, config: ['screen_device &screen(SCREEN(config, "screen", SCREEN_TYPE_RASTER))', 'screen.set_raw(XTAL(12\'000\'000) / 2, 384, 0, 256, 262, 16, 240)', 'screen.set_screen_update(FUNC(gng_state::screen_update))', 'screen.set_palette(m_palette)'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 593, sourceColumn: 2, sourceEndLine: 593, configCalls: ['set_raw(6000000,384,0,256,262,16,240)'], clockExpr: 'SCREEN_TYPE_RASTER', screenRaw: [6000000, 384, 0, 256, 262, 16, 240]};
MERGE (n:KG {id: 'device:gng_state.gng/screen/callback0'}) SET n:Callback SET n += {signal: 'set_screen_update', operation: 'set_screen_update', raw: 'screen.set_screen_update(FUNC(gng_state::screen_update))', ownerTag: 'screen', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 595, sourceColumn: 2, sourceEndLine: 595, targetClass: 'gng_state', targetMethod: 'screen_update'};
MERGE (n:KG {id: 'handler:gng_state.screen_update'}) SET n:Handler SET n += {method: 'screen_update', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 224, sourceColumn: 1, sourceEndLine: 231, sourceParameters: 'screen_device &screen, bitmap_ind16 &bitmap, const rectangle &cliprect', sourceBody: 'm_bg_tilemap->draw(screen, bitmap, cliprect, TILEMAP_DRAW_LAYER1, 0);
	draw_sprites(bitmap, cliprect);
	m_bg_tilemap->draw(screen, bitmap, cliprect, TILEMAP_DRAW_LAYER0, 0);
	m_fg_tilemap->draw(screen, bitmap, cliprect, 0, 0);
	return 0;'};
MERGE (n:KG {id: 'handler:gng_state.draw_sprites'}) SET n:Handler SET n += {method: 'draw_sprites', ownerClass: 'gng_state', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 195, sourceColumn: 1, sourceEndLine: 222, sourceParameters: 'bitmap_ind16 &bitmap, const rectangle &cliprect', sourceBody: 'uint8_t *spriteram = m_spriteram->buffer();
	gfx_element *gfx = m_gfxdecode->gfx(2);

	for (int offs = m_spriteram->bytes() - 4; offs >= 0; offs -= 4)
	{
		uint8_t attributes = spriteram[offs + 1];
		int sx = spriteram[offs + 3] - 0x100 * (attributes & 0x01);
		int sy = spriteram[offs + 2];
		int flipx = attributes & 0x04;
		int flipy = attributes & 0x08;

		if (flip_screen())
		{
			sx = 240 - sx;
			sy = 240 - sy;
			flipx = !flipx;
			flipy = !flipy;
		}

		gfx->transpen(bitmap,cliprect,
				spriteram[offs] + ((attributes << 2) & 0x300),
				(attributes >> 4) & 3,
				flipx, flipy,
				sx, sy, 15);
	}'};
MERGE (n:KG {id: 'device:gng_state.gng/gfxdecode'}) SET n:Device SET n += {type: 'GFXDECODE', tag: 'gfxdecode', clock: null, config: ['GFXDECODE(config, m_gfxdecode, m_palette, gfx_gng)'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 598, sourceColumn: 2, sourceEndLine: 598, clockExpr: 'm_palette, gfx_gng'};
MERGE (n:KG {id: 'device:gng_state.gng/palette'}) SET n:Device SET n += {type: 'PALETTE', tag: 'palette', clock: null, config: ['PALETTE(config, m_palette).set_format(palette_device::RGBx_444, 256)'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 600, sourceColumn: 2, sourceEndLine: 600};
MERGE (n:KG {id: 'device:gng_state.gng/mono'}) SET n:Device SET n += {type: 'SPEAKER', tag: 'mono', clock: null, config: ['SPEAKER(config, "mono").front_center()'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 603, sourceColumn: 2, sourceEndLine: 603};
MERGE (n:KG {id: 'device:gng_state.gng/soundlatch'}) SET n:Device SET n += {type: 'GENERIC_LATCH_8', tag: 'soundlatch', clock: null, config: ['GENERIC_LATCH_8(config, "soundlatch")'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 605, sourceColumn: 2, sourceEndLine: 605};
MERGE (n:KG {id: 'device:gng_state.gng/ym1'}) SET n:Device SET n += {type: 'YM2203', tag: 'ym1', clock: 1500000, config: ['YM2203(config, m_ym[0], XTAL(12\'000\'000) / 8)', 'm_ym[0]->add_route(0, "mono", 0.40)', 'm_ym[0]->add_route(1, "mono", 0.40)', 'm_ym[0]->add_route(2, "mono", 0.40)', 'm_ym[0]->add_route(3, "mono", 0.20)'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 607, sourceColumn: 2, sourceEndLine: 607};
MERGE (n:KG {id: 'audioroute:device:gng_state.gng/ym1/0'}) SET n:AudioRoute SET n += {output: '0', target: 'mono', gain: 0.4, raw: 'm_ym[0]->add_route(0, "mono", 0.40)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 608, sourceColumn: 2, sourceEndLine: 608};
MERGE (n:KG {id: 'audioroute:device:gng_state.gng/ym1/1'}) SET n:AudioRoute SET n += {output: '1', target: 'mono', gain: 0.4, raw: 'm_ym[0]->add_route(1, "mono", 0.40)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 609, sourceColumn: 2, sourceEndLine: 609};
MERGE (n:KG {id: 'audioroute:device:gng_state.gng/ym1/2'}) SET n:AudioRoute SET n += {output: '2', target: 'mono', gain: 0.4, raw: 'm_ym[0]->add_route(2, "mono", 0.40)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 610, sourceColumn: 2, sourceEndLine: 610};
MERGE (n:KG {id: 'audioroute:device:gng_state.gng/ym1/3'}) SET n:AudioRoute SET n += {output: '3', target: 'mono', gain: 0.2, raw: 'm_ym[0]->add_route(3, "mono", 0.20)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 611, sourceColumn: 2, sourceEndLine: 611};
MERGE (n:KG {id: 'device:gng_state.gng/ym2'}) SET n:Device SET n += {type: 'YM2203', tag: 'ym2', clock: 1500000, config: ['YM2203(config, m_ym[1], XTAL(12\'000\'000) / 8)', 'm_ym[1]->add_route(0, "mono", 0.40)', 'm_ym[1]->add_route(1, "mono", 0.40)', 'm_ym[1]->add_route(2, "mono", 0.40)', 'm_ym[1]->add_route(3, "mono", 0.20)'], sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 613, sourceColumn: 2, sourceEndLine: 613};
MERGE (n:KG {id: 'audioroute:device:gng_state.gng/ym2/0'}) SET n:AudioRoute SET n += {output: '0', target: 'mono', gain: 0.4, raw: 'm_ym[1]->add_route(0, "mono", 0.40)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 614, sourceColumn: 2, sourceEndLine: 614};
MERGE (n:KG {id: 'audioroute:device:gng_state.gng/ym2/1'}) SET n:AudioRoute SET n += {output: '1', target: 'mono', gain: 0.4, raw: 'm_ym[1]->add_route(1, "mono", 0.40)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 615, sourceColumn: 2, sourceEndLine: 615};
MERGE (n:KG {id: 'audioroute:device:gng_state.gng/ym2/2'}) SET n:AudioRoute SET n += {output: '2', target: 'mono', gain: 0.4, raw: 'm_ym[1]->add_route(2, "mono", 0.40)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 616, sourceColumn: 2, sourceEndLine: 616};
MERGE (n:KG {id: 'audioroute:device:gng_state.gng/ym2/3'}) SET n:AudioRoute SET n += {output: '3', target: 'mono', gain: 0.2, raw: 'm_ym[1]->add_route(3, "mono", 0.20)', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 617, sourceColumn: 2, sourceEndLine: 617};
MERGE (n:KG {id: 'inputs:gng'}) SET n:InputPorts SET n += {name: 'gng', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 318, sourceColumn: 8, sourceEndLine: 318};
MERGE (n:KG {id: 'inputs:gng/SYSTEM'}) SET n:Port SET n += {tag: 'SYSTEM', modify: false};
MERGE (n:KG {id: 'inputs:gng/SYSTEM/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_START1'};
MERGE (n:KG {id: 'inputs:gng/SYSTEM/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_START2'};
MERGE (n:KG {id: 'inputs:gng/SYSTEM/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 12, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:gng/SYSTEM/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:gng/SYSTEM/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_SERVICE1'};
MERGE (n:KG {id: 'inputs:gng/SYSTEM/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 64, activeLow: true, type: 'IPT_COIN1'};
MERGE (n:KG {id: 'inputs:gng/SYSTEM/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 128, activeLow: true, type: 'IPT_COIN2'};
MERGE (n:KG {id: 'inputs:gng/P1'}) SET n:Port SET n += {tag: 'P1', modify: false};
MERGE (n:KG {id: 'inputs:gng/P1/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_RIGHT', modifiers: ['PORT_4WAY']};
MERGE (n:KG {id: 'inputs:gng/P1/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_LEFT', modifiers: ['PORT_4WAY']};
MERGE (n:KG {id: 'inputs:gng/P1/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_DOWN', modifiers: ['PORT_4WAY']};
MERGE (n:KG {id: 'inputs:gng/P1/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_UP', modifiers: ['PORT_4WAY']};
MERGE (n:KG {id: 'inputs:gng/P1/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_BUTTON1'};
MERGE (n:KG {id: 'inputs:gng/P1/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_BUTTON2'};
MERGE (n:KG {id: 'inputs:gng/P1/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 192, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:gng/P2'}) SET n:Port SET n += {tag: 'P2', modify: false};
MERGE (n:KG {id: 'inputs:gng/P2/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_RIGHT', modifiers: ['PORT_4WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gng/P2/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_LEFT', modifiers: ['PORT_4WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gng/P2/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_DOWN', modifiers: ['PORT_4WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gng/P2/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_UP', modifiers: ['PORT_4WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gng/P2/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_BUTTON1', modifiers: ['PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gng/P2/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_BUTTON2', modifiers: ['PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gng/P2/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 192, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:gng/DSW1'}) SET n:Port SET n += {tag: 'DSW1', modify: false};
MERGE (n:KG {id: 'inputs:gng/DSW1/f0'}) SET n:PortField SET n += {kind: 'dip', mask: 15, name: 'Coinage', defaultValue: 15, location: 'SW1:8,7,6,5', settings: ['2=4C 1C', '5=3C 1C', '8=2C 1C', '4=3C 2C', '1=4C 3C', '15=1C 1C', '3=3C 4C', '7=2C 3C', '14=1C 2C', '6=2C 5C', '13=1C 3C', '12=1C 4C', '11=1C 5C', '10=1C 6C', '9=1C 7C', '0=Free Play']};
MERGE (n:KG {id: 'inputs:gng/DSW1/f1'}) SET n:PortField SET n += {kind: 'dip', mask: 16, name: 'Coinage affects', defaultValue: 16, location: 'SW1:4', settings: ['16=Coin A', '0=Coin B']};
MERGE (n:KG {id: 'inputs:gng/DSW1/f2'}) SET n:PortField SET n += {kind: 'dip', mask: 32, name: 'Demo Sounds', defaultValue: 0, location: 'SW1:3', settings: ['32=Off', '0=On']};
MERGE (n:KG {id: 'inputs:gng/DSW1/f3'}) SET n:PortField SET n += {kind: 'service', mask: 64, activeLow: true};
MERGE (n:KG {id: 'inputs:gng/DSW1/f4'}) SET n:PortField SET n += {kind: 'dip', mask: 128, name: 'Flip Screen', defaultValue: 128, location: 'SW1:1', settings: ['128=Off', '0=On']};
MERGE (n:KG {id: 'inputs:gng/DSW2'}) SET n:Port SET n += {tag: 'DSW2', modify: false};
MERGE (n:KG {id: 'inputs:gng/DSW2/f0'}) SET n:PortField SET n += {kind: 'dip', mask: 3, name: 'Lives', defaultValue: 3, location: 'SW2:8,7', settings: ['3=3', '2=4', '1=5', '0=7']};
MERGE (n:KG {id: 'inputs:gng/DSW2/f1'}) SET n:PortField SET n += {kind: 'dip', mask: 4, name: 'Cabinet', defaultValue: 0, location: 'SW2:6', settings: ['0=Upright', '4=Cocktail']};
MERGE (n:KG {id: 'inputs:gng/DSW2/f2'}) SET n:PortField SET n += {kind: 'dip', mask: 24, name: 'Bonus Life', defaultValue: 24, location: 'SW2:5,4', settings: ['24=20K 70K Every 70K', '16=30K 80K Every 80K', '8=20K and 80K Only', '0=30K and 80K Only']};
MERGE (n:KG {id: 'inputs:gng/DSW2/f3'}) SET n:PortField SET n += {kind: 'dip', mask: 96, name: 'Difficulty', defaultValue: 96, location: 'SW2:3,2', settings: ['64=Easy', '96=Normal', '32=Difficult', '0=Very Difficult']};
MERGE (n:KG {id: 'inputs:gng/DSW2/f4'}) SET n:PortField SET n += {kind: 'dip', mask: 128, name: 'Unused'};
MERGE (n:KG {id: 'gfxlayout:charlayout'}) SET n:GfxLayout SET n += {name: 'charlayout', width: 8, height: 8, total: 'RGN_FRAC(1,1)', planes: 2, planeOffsets: [4, 0], xOffsets: [0, 1, 2, 3, 8, 9, 10, 11], yOffsets: [0, 16, 32, 48, 64, 80, 96, 112], charIncrement: 128};
MERGE (n:KG {id: 'gfxlayout:tilelayout'}) SET n:GfxLayout SET n += {name: 'tilelayout', width: 16, height: 16, total: 'RGN_FRAC(1,3)', planes: 3, planeOffsets: ['RGN_FRAC(2,3)', 'RGN_FRAC(1,3)', 'RGN_FRAC(0,3)'], xOffsets: [0, 1, 2, 3, 4, 5, 6, 7, 128, 129, 130, 131, 132, 133, 134, 135], yOffsets: [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120], charIncrement: 256};
MERGE (n:KG {id: 'gfxlayout:spritelayout'}) SET n:GfxLayout SET n += {name: 'spritelayout', width: 16, height: 16, total: 'RGN_FRAC(1,2)', planes: 4, planeOffsets: ['RGN_FRAC(1,2)+4', 'RGN_FRAC(1,2)+0', 4, 0], xOffsets: [0, 1, 2, 3, 8, 9, 10, 11, 256, 257, 258, 259, 264, 265, 266, 267], yOffsets: [0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240], charIncrement: 512};
MERGE (n:KG {id: 'gfxdecode:gfx_gng'}) SET n:GfxDecode SET n += {name: 'gfx_gng', sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 531, sourceColumn: 8, sourceEndLine: 531};
MERGE (n:KG {id: 'gfxdecode:gfx_gng/e0'}) SET n:GfxDecodeEntry SET n += {region: 'chars', offset: 0, layout: 'charlayout', colorBase: 128, colorCount: 16, xscale: 1, yscale: 1};
MERGE (n:KG {id: 'gfxdecode:gfx_gng/e1'}) SET n:GfxDecodeEntry SET n += {region: 'tiles', offset: 0, layout: 'tilelayout', colorBase: 0, colorCount: 8, xscale: 1, yscale: 1};
MERGE (n:KG {id: 'gfxdecode:gfx_gng/e2'}) SET n:GfxDecodeEntry SET n += {region: 'sprites', offset: 0, layout: 'spritelayout', colorBase: 64, colorCount: 4, xscale: 1, yscale: 1};
MATCH (a:KG {id: 'game:gng'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 1162, sourceColumn: 1, sourceEndLine: 1162};
MATCH (a:KG {id: 'game:gng'}), (b:KG {id: 'machine:gng_state.gng'}) MERGE (a)-[r:USES_MACHINE]->(b);
MATCH (a:KG {id: 'game:gng'}), (b:KG {id: 'inputs:gng'}) MERGE (a)-[r:USES_INPUTS]->(b);
MATCH (a:KG {id: 'game:gng'}), (b:KG {id: 'romset:gng'}) MERGE (a)-[r:USES_ROMSET]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:emu.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:cpu/m6809/m6809.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:cpu/z80/z80.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:machine/74259.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:machine/gen_latch.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:sound/ymopn.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:video/bufsprite.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:emupal.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:screen.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:speaker.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/gng.cpp'}), (b:KG {id: 'file:tilemap.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 572, sourceColumn: 1, sourceEndLine: 618};
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'bank:gng_state.gng/mainbank/0'}) MERGE (a)-[r:HAS_BANK]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'bank:gng_state.gng/mainbank/1'}) MERGE (a)-[r:HAS_BANK]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/maincpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/audiocpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/mainlatch'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/spriteram'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/screen'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/gfxdecode'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'gfxdecode:gfx_gng'}) MERGE (a)-[r:DECODES]->(b) SET r += {deviceTag: 'gfxdecode'};
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/palette'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/mono'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/soundlatch'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/ym1'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gng_state.gng'}), (b:KG {id: 'device:gng_state.gng/ym2'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'inputs:gng'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 318, sourceColumn: 8, sourceEndLine: 318};
MATCH (a:KG {id: 'inputs:gng'}), (b:KG {id: 'inputs:gng/SYSTEM'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:gng'}), (b:KG {id: 'inputs:gng/P1'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:gng'}), (b:KG {id: 'inputs:gng/P2'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:gng'}), (b:KG {id: 'inputs:gng/DSW1'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:gng'}), (b:KG {id: 'inputs:gng/DSW2'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'romset:gng'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 636, sourceColumn: 1, sourceEndLine: 636};
MATCH (a:KG {id: 'romset:gng'}), (b:KG {id: 'region:gng/maincpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gng'}), (b:KG {id: 'region:gng/audiocpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gng'}), (b:KG {id: 'region:gng/chars'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gng'}), (b:KG {id: 'region:gng/tiles'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gng'}), (b:KG {id: 'region:gng/sprites'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gng'}), (b:KG {id: 'region:gng/proms'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gng'}), (b:KG {id: 'region:gng/plds'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'bank:gng_state.gng/mainbank/0'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 540, sourceColumn: 1, sourceEndLine: 548};
MATCH (a:KG {id: 'bank:gng_state.gng/mainbank/1'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 540, sourceColumn: 1, sourceEndLine: 548};
MATCH (a:KG {id: 'device:gng_state.gng/maincpu'}), (b:KG {id: 'device:gng_state.gng/maincpu/callback0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/maincpu'}), (b:KG {id: 'map:gng_state.gng_main_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:gng_state.gng/audiocpu'}), (b:KG {id: 'device:gng_state.gng/audiocpu/callback0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/audiocpu'}), (b:KG {id: 'map:gng_state.sound_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:gng_state.gng/mainlatch'}), (b:KG {id: 'device:gng_state.gng/mainlatch/callback0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/mainlatch'}), (b:KG {id: 'device:gng_state.gng/mainlatch/callback1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/mainlatch'}), (b:KG {id: 'device:gng_state.gng/mainlatch/callback2'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/screen'}), (b:KG {id: 'device:gng_state.gng/screen/callback0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gng'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 531, sourceColumn: 8, sourceEndLine: 531};
MATCH (a:KG {id: 'gfxdecode:gfx_gng'}), (b:KG {id: 'gfxdecode:gfx_gng/e0'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gng'}), (b:KG {id: 'gfxdecode:gfx_gng/e1'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gng'}), (b:KG {id: 'gfxdecode:gfx_gng/e2'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/ym1'}), (b:KG {id: 'audioroute:device:gng_state.gng/ym1/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/ym1'}), (b:KG {id: 'audioroute:device:gng_state.gng/ym1/1'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/ym1'}), (b:KG {id: 'audioroute:device:gng_state.gng/ym1/2'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/ym1'}), (b:KG {id: 'audioroute:device:gng_state.gng/ym1/3'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/ym2'}), (b:KG {id: 'audioroute:device:gng_state.gng/ym2/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/ym2'}), (b:KG {id: 'audioroute:device:gng_state.gng/ym2/1'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/ym2'}), (b:KG {id: 'audioroute:device:gng_state.gng/ym2/2'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/ym2'}), (b:KG {id: 'audioroute:device:gng_state.gng/ym2/3'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'inputs:gng/SYSTEM'}), (b:KG {id: 'inputs:gng/SYSTEM/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/SYSTEM'}), (b:KG {id: 'inputs:gng/SYSTEM/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/SYSTEM'}), (b:KG {id: 'inputs:gng/SYSTEM/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/SYSTEM'}), (b:KG {id: 'inputs:gng/SYSTEM/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/SYSTEM'}), (b:KG {id: 'inputs:gng/SYSTEM/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/SYSTEM'}), (b:KG {id: 'inputs:gng/SYSTEM/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/SYSTEM'}), (b:KG {id: 'inputs:gng/SYSTEM/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P1'}), (b:KG {id: 'inputs:gng/P1/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P1'}), (b:KG {id: 'inputs:gng/P1/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P1'}), (b:KG {id: 'inputs:gng/P1/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P1'}), (b:KG {id: 'inputs:gng/P1/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P1'}), (b:KG {id: 'inputs:gng/P1/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P1'}), (b:KG {id: 'inputs:gng/P1/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P1'}), (b:KG {id: 'inputs:gng/P1/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P2'}), (b:KG {id: 'inputs:gng/P2/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P2'}), (b:KG {id: 'inputs:gng/P2/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P2'}), (b:KG {id: 'inputs:gng/P2/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P2'}), (b:KG {id: 'inputs:gng/P2/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P2'}), (b:KG {id: 'inputs:gng/P2/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P2'}), (b:KG {id: 'inputs:gng/P2/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/P2'}), (b:KG {id: 'inputs:gng/P2/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW1'}), (b:KG {id: 'inputs:gng/DSW1/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW1'}), (b:KG {id: 'inputs:gng/DSW1/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW1'}), (b:KG {id: 'inputs:gng/DSW1/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW1'}), (b:KG {id: 'inputs:gng/DSW1/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW1'}), (b:KG {id: 'inputs:gng/DSW1/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW2'}), (b:KG {id: 'inputs:gng/DSW2/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW2'}), (b:KG {id: 'inputs:gng/DSW2/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW2'}), (b:KG {id: 'inputs:gng/DSW2/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW2'}), (b:KG {id: 'inputs:gng/DSW2/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gng/DSW2'}), (b:KG {id: 'inputs:gng/DSW2/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'region:gng/maincpu'}), (b:KG {id: 'rom:gng/maincpu/mm_c_04'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/maincpu'}), (b:KG {id: 'rom:gng/maincpu/mm_c_03'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/maincpu'}), (b:KG {id: 'rom:gng/maincpu/mm_c_05'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/audiocpu'}), (b:KG {id: 'rom:gng/audiocpu/gg2.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/chars'}), (b:KG {id: 'rom:gng/chars/gg1.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/tiles'}), (b:KG {id: 'rom:gng/tiles/gg11.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/tiles'}), (b:KG {id: 'rom:gng/tiles/gg10.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/tiles'}), (b:KG {id: 'rom:gng/tiles/gg9.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/tiles'}), (b:KG {id: 'rom:gng/tiles/gg8.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/tiles'}), (b:KG {id: 'rom:gng/tiles/gg7.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/tiles'}), (b:KG {id: 'rom:gng/tiles/gg6.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/sprites'}), (b:KG {id: 'rom:gng/sprites/gg17.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/sprites'}), (b:KG {id: 'rom:gng/sprites/gg16.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/sprites'}), (b:KG {id: 'rom:gng/sprites/gg15.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/sprites'}), (b:KG {id: 'rom:gng/sprites/gg14.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/sprites'}), (b:KG {id: 'rom:gng/sprites/gg13.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/sprites'}), (b:KG {id: 'rom:gng/sprites/gg12.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/proms'}), (b:KG {id: 'rom:gng/proms/tbp24s10.14k'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/proms'}), (b:KG {id: 'rom:gng/proms/63s141.2e'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gng/plds'}), (b:KG {id: 'rom:gng/plds/gg-pal10l8.bin'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/maincpu/callback0'}), (b:KG {id: 'handler:gng_state.irq0_line_hold'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 256, sourceColumn: 1, sourceEndLine: 277};
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range5'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range6'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range7'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range8'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range9'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range10'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range11'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range12'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range13'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range14'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range15'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range16'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range17'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map'}), (b:KG {id: 'map:gng_state.gng_main_map/range18'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/audiocpu/callback0'}), (b:KG {id: 'handler:gng_state.irq0_line_hold'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'map:gng_state.sound_map'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/gng.cpp', sourceLine: 308, sourceColumn: 1, sourceEndLine: 315};
MATCH (a:KG {id: 'map:gng_state.sound_map'}), (b:KG {id: 'map:gng_state.sound_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.sound_map'}), (b:KG {id: 'map:gng_state.sound_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.sound_map'}), (b:KG {id: 'map:gng_state.sound_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.sound_map'}), (b:KG {id: 'map:gng_state.sound_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gng_state.sound_map'}), (b:KG {id: 'map:gng_state.sound_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/mainlatch/callback0'}), (b:KG {id: 'handler:gng_state.flip_screen_set'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/mainlatch/callback1'}), (b:KG {id: 'device:gng_state.gng/audiocpu'}) MERGE (a)-[r:TARGETS_DEVICE]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/mainlatch/callback2'}), (b:KG {id: 'handler:gng_state.ym_reset_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gng_state.gng/screen/callback0'}), (b:KG {id: 'handler:gng_state.screen_update'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gng/e0'}), (b:KG {id: 'gfxlayout:charlayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gng/e1'}), (b:KG {id: 'gfxlayout:tilelayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gng/e2'}), (b:KG {id: 'gfxlayout:spritelayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range2'}), (b:KG {id: 'handler:gng_state.fgvideoram_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range3'}), (b:KG {id: 'handler:gng_state.bgvideoram_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range9'}), (b:KG {id: 'handler:palette_device.write8_ext'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'palette'};
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range10'}), (b:KG {id: 'handler:palette_device.write8'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'palette'};
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range11'}), (b:KG {id: 'handler:generic_latch_8_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'soundlatch'};
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range12'}), (b:KG {id: 'handler:gng_state.bgscrollx_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range13'}), (b:KG {id: 'handler:gng_state.bgscrolly_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range14'}), (b:KG {id: 'handler:buffered_spriteram8_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'spriteram'};
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range15'}), (b:KG {id: 'handler:ls259_device.write_d0'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'mainlatch'};
MATCH (a:KG {id: 'map:gng_state.gng_main_map/range16'}), (b:KG {id: 'handler:gng_state.bankswitch_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:gng_state.sound_map/range2'}), (b:KG {id: 'handler:generic_latch_8_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'soundlatch'};
MATCH (a:KG {id: 'map:gng_state.sound_map/range3'}), (b:KG {id: 'handler:ym2203_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ym1'};
MATCH (a:KG {id: 'map:gng_state.sound_map/range4'}), (b:KG {id: 'handler:ym2203_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ym2'};
MATCH (a:KG {id: 'handler:gng_state.screen_update'}), (b:KG {id: 'handler:gng_state.draw_sprites'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'gfxlayout:charlayout'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
MATCH (a:KG {id: 'gfxlayout:tilelayout'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
MATCH (a:KG {id: 'gfxlayout:spritelayout'}), (b:KG {id: 'file:src/mame/capcom/gng.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
