// mamekit knowledge graph — driver src/mame/pacman/pacman.cpp
// generated 2026-07-30T09:34:16.275Z
CREATE CONSTRAINT mamekit_id IF NOT EXISTS FOR (n:KG) REQUIRE n.id IS UNIQUE;
MERGE (n:KG {id: 'file:src/mame/pacman/pacman.cpp'}) SET n:SourceFile SET n += {path: 'src/mame/pacman/pacman.cpp'};
MERGE (n:KG {id: 'file:emu.h'}) SET n:SourceFile SET n += {path: 'emu.h', external: true};
MERGE (n:KG {id: 'file:pacman.h'}) SET n:SourceFile SET n += {path: 'pacman.h', external: true};
MERGE (n:KG {id: 'file:jumpshot.h'}) SET n:SourceFile SET n += {path: 'jumpshot.h', external: true};
MERGE (n:KG {id: 'file:pacplus.h'}) SET n:SourceFile SET n += {path: 'pacplus.h', external: true};
MERGE (n:KG {id: 'file:cpu/s2650/s2650.h'}) SET n:SourceFile SET n += {path: 'cpu/s2650/s2650.h', external: true};
MERGE (n:KG {id: 'file:cpu/z80/z80.h'}) SET n:SourceFile SET n += {path: 'cpu/z80/z80.h', external: true};
MERGE (n:KG {id: 'file:machine/nvram.h'}) SET n:SourceFile SET n += {path: 'machine/nvram.h', external: true};
MERGE (n:KG {id: 'file:sound/ay8910.h'}) SET n:SourceFile SET n += {path: 'sound/ay8910.h', external: true};
MERGE (n:KG {id: 'file:sound/sn76496.h'}) SET n:SourceFile SET n += {path: 'sound/sn76496.h', external: true};
MERGE (n:KG {id: 'file:screen.h'}) SET n:SourceFile SET n += {path: 'screen.h', external: true};
MERGE (n:KG {id: 'file:speaker.h'}) SET n:SourceFile SET n += {path: 'speaker.h', external: true};
MERGE (n:KG {id: 'game:puckman'}) SET n:Game SET n += {name: 'puckman', year: '1980', company: 'Namco', fullname: 'Puck Man (Japan, set 1)', monitor: 'ROT90', cls: 'pacman_state', init: 'empty_init', flags: 'MACHINE_SUPPORTS_SAVE', kind: 'arcade', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 8991, sourceColumn: 1, sourceEndLine: 8991};
MERGE (n:KG {id: 'game:pacman'}) SET n:Game SET n += {name: 'pacman', year: '1980', company: 'Namco (Midway license)', fullname: 'Pac-Man (Midway)', monitor: 'ROT90', cls: 'pacman_state', init: 'empty_init', flags: 'MACHINE_SUPPORTS_SAVE', kind: 'arcade', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 8996, sourceColumn: 1, sourceEndLine: 8996};
MERGE (n:KG {id: 'romset:puckman'}) SET n:RomSet SET n += {name: 'puckman', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4150, sourceColumn: 1, sourceEndLine: 4150};
MERGE (n:KG {id: 'region:puckman/maincpu'}) SET n:RomRegion SET n += {tag: 'maincpu', size: 65536, flags: '0', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4151, sourceColumn: 2, sourceEndLine: 4151};
MERGE (n:KG {id: 'rom:puckman/maincpu/pm1_prg1.6e'}) SET n:Rom SET n += {file: 'pm1_prg1.6e', offset: 0, size: 2048, crc: 'f36e88ab', sha1: '813cecf44bf5464b1aed64b36f5047e4c79ba176', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4152, sourceColumn: 2, sourceEndLine: 4152};
MERGE (n:KG {id: 'rom:puckman/maincpu/pm1_prg2.6k'}) SET n:Rom SET n += {file: 'pm1_prg2.6k', offset: 2048, size: 2048, crc: '618bd9b3', sha1: 'b9ca52b63a49ddece768378d331deebbe34fe177', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4153, sourceColumn: 2, sourceEndLine: 4153};
MERGE (n:KG {id: 'rom:puckman/maincpu/pm1_prg3.6f'}) SET n:Rom SET n += {file: 'pm1_prg3.6f', offset: 4096, size: 2048, crc: '7d177853', sha1: '9b5ddaaa8b564654f97af193dbcc29f81f230a25', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4154, sourceColumn: 2, sourceEndLine: 4154};
MERGE (n:KG {id: 'rom:puckman/maincpu/pm1_prg4.6m'}) SET n:Rom SET n += {file: 'pm1_prg4.6m', offset: 6144, size: 2048, crc: 'd3e8914c', sha1: 'c2f00e1773c6864435f29c8b7f44f2ef85d227d3', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4155, sourceColumn: 2, sourceEndLine: 4155};
MERGE (n:KG {id: 'rom:puckman/maincpu/pm1_prg5.6h'}) SET n:Rom SET n += {file: 'pm1_prg5.6h', offset: 8192, size: 2048, crc: '6bf4f625', sha1: 'afe72fdfec66c145b53ed865f98734686b26e921', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4156, sourceColumn: 2, sourceEndLine: 4156};
MERGE (n:KG {id: 'rom:puckman/maincpu/pm1_prg6.6n'}) SET n:Rom SET n += {file: 'pm1_prg6.6n', offset: 10240, size: 2048, crc: 'a948ce83', sha1: '08759833f7e0690b2ccae573c929e2a48e5bde7f', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4157, sourceColumn: 2, sourceEndLine: 4157};
MERGE (n:KG {id: 'rom:puckman/maincpu/pm1_prg7.6j'}) SET n:Rom SET n += {file: 'pm1_prg7.6j', offset: 12288, size: 2048, crc: 'b6289b26', sha1: 'd249fa9cdde774d5fee7258147cd25fa3f4dc2b3', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4158, sourceColumn: 2, sourceEndLine: 4158};
MERGE (n:KG {id: 'rom:puckman/maincpu/pm1_prg8.6p'}) SET n:Rom SET n += {file: 'pm1_prg8.6p', offset: 14336, size: 2048, crc: '17a88c13', sha1: 'eb462de79f49b7aa8adb0cc6d31535b10550c0ce', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4159, sourceColumn: 2, sourceEndLine: 4159};
MERGE (n:KG {id: 'region:puckman/gfx1'}) SET n:RomRegion SET n += {tag: 'gfx1', size: 8192, flags: '0', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4161, sourceColumn: 2, sourceEndLine: 4161};
MERGE (n:KG {id: 'rom:puckman/gfx1/pm1_chg1.5e'}) SET n:Rom SET n += {file: 'pm1_chg1.5e', offset: 0, size: 2048, crc: '2066a0b7', sha1: '6d4ccc27d6be185589e08aa9f18702b679e49a4a', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4162, sourceColumn: 2, sourceEndLine: 4162};
MERGE (n:KG {id: 'rom:puckman/gfx1/pm1_chg2.5h'}) SET n:Rom SET n += {file: 'pm1_chg2.5h', offset: 2048, size: 2048, crc: '3591b89d', sha1: '79bb456be6c39c1ccd7d077fbe181523131fb300', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4163, sourceColumn: 2, sourceEndLine: 4163};
MERGE (n:KG {id: 'rom:puckman/gfx1/pm1_chg3.5f'}) SET n:Rom SET n += {file: 'pm1_chg3.5f', offset: 4096, size: 2048, crc: '9e39323a', sha1: 'be933e691df4dbe7d12123913c3b7b7b585b7a35', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4164, sourceColumn: 2, sourceEndLine: 4164};
MERGE (n:KG {id: 'rom:puckman/gfx1/pm1_chg4.5j'}) SET n:Rom SET n += {file: 'pm1_chg4.5j', offset: 6144, size: 2048, crc: '1b1d9096', sha1: '53771c573051db43e7185b1d188533056290a620', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4165, sourceColumn: 2, sourceEndLine: 4165};
MERGE (n:KG {id: 'region:puckman/proms'}) SET n:RomRegion SET n += {tag: 'proms', size: 288, flags: '0', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4167, sourceColumn: 2, sourceEndLine: 4167};
MERGE (n:KG {id: 'rom:puckman/proms/pm1-1.7f'}) SET n:Rom SET n += {file: 'pm1-1.7f', offset: 0, size: 32, crc: '2fc650bd', sha1: '8d0268dee78e47c712202b0ec4f1f51109b1f2a5', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4168, sourceColumn: 2, sourceEndLine: 4168};
MERGE (n:KG {id: 'rom:puckman/proms/pm1-4.4a'}) SET n:Rom SET n += {file: 'pm1-4.4a', offset: 32, size: 256, crc: '3eb3a8e4', sha1: '19097b5f60d1030f8b82d9f1d3a241f93e5c75d6', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4169, sourceColumn: 2, sourceEndLine: 4169};
MERGE (n:KG {id: 'region:puckman/namco'}) SET n:RomRegion SET n += {tag: 'namco', size: 512, flags: '0', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4171, sourceColumn: 2, sourceEndLine: 4171};
MERGE (n:KG {id: 'rom:puckman/namco/pm1-3.1m'}) SET n:Rom SET n += {file: 'pm1-3.1m', offset: 0, size: 256, crc: 'a9cc86bf', sha1: 'bbcec0570aeceb582ff8238a4bc8546a23430081', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4172, sourceColumn: 2, sourceEndLine: 4172};
MERGE (n:KG {id: 'rom:puckman/namco/pm1-2.3m'}) SET n:Rom SET n += {file: 'pm1-2.3m', offset: 256, size: 256, crc: '77245b66', sha1: '0c4d0bee858b97632411c440bea6948a74759746', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4173, sourceColumn: 2, sourceEndLine: 4173};
MERGE (n:KG {id: 'romset:pacman'}) SET n:RomSet SET n += {name: 'pacman', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4319, sourceColumn: 1, sourceEndLine: 4319};
MERGE (n:KG {id: 'region:pacman/maincpu'}) SET n:RomRegion SET n += {tag: 'maincpu', size: 65536, flags: '0', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4151, sourceColumn: 2, sourceEndLine: 4151};
MERGE (n:KG {id: 'rom:pacman/maincpu/pacman.6e'}) SET n:Rom SET n += {file: 'pacman.6e', offset: 0, size: 4096, crc: 'c1e6ab10', sha1: 'e87e059c5be45753f7e9f33dff851f16d6751181', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4321, sourceColumn: 2, sourceEndLine: 4321};
MERGE (n:KG {id: 'rom:pacman/maincpu/pacman.6f'}) SET n:Rom SET n += {file: 'pacman.6f', offset: 4096, size: 4096, crc: '1a6fb2d4', sha1: '674d3a7f00d8be5e38b1fdc208ebef5a92d38329', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4322, sourceColumn: 2, sourceEndLine: 4322};
MERGE (n:KG {id: 'rom:pacman/maincpu/pacman.6h'}) SET n:Rom SET n += {file: 'pacman.6h', offset: 8192, size: 4096, crc: 'bcdd1beb', sha1: '8e47e8c2c4d6117d174cdac150392042d3e0a881', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4323, sourceColumn: 2, sourceEndLine: 4323};
MERGE (n:KG {id: 'rom:pacman/maincpu/pacman.6j'}) SET n:Rom SET n += {file: 'pacman.6j', offset: 12288, size: 4096, crc: '817d94e3', sha1: 'd4a70d56bb01d27d094d73db8667ffb00ca69cb9', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4324, sourceColumn: 2, sourceEndLine: 4324};
MERGE (n:KG {id: 'region:pacman/gfx1'}) SET n:RomRegion SET n += {tag: 'gfx1', size: 8192, flags: '0', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4161, sourceColumn: 2, sourceEndLine: 4161};
MERGE (n:KG {id: 'rom:pacman/gfx1/pacman.5e'}) SET n:Rom SET n += {file: 'pacman.5e', offset: 0, size: 4096, crc: '0c944964', sha1: '06ef227747a440831c9a3a613b76693d52a2f0a9', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4265, sourceColumn: 2, sourceEndLine: 4265};
MERGE (n:KG {id: 'rom:pacman/gfx1/pacman.5f'}) SET n:Rom SET n += {file: 'pacman.5f', offset: 4096, size: 4096, crc: '958fedf9', sha1: '4a937ac02216ea8c96477d4a15522070507fb599', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4266, sourceColumn: 2, sourceEndLine: 4266};
MERGE (n:KG {id: 'region:pacman/proms'}) SET n:RomRegion SET n += {tag: 'proms', size: 288, flags: '0', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4167, sourceColumn: 2, sourceEndLine: 4167};
MERGE (n:KG {id: 'rom:pacman/proms/82s123.7f'}) SET n:Rom SET n += {file: '82s123.7f', offset: 0, size: 32, crc: '2fc650bd', sha1: '8d0268dee78e47c712202b0ec4f1f51109b1f2a5', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4269, sourceColumn: 2, sourceEndLine: 4269};
MERGE (n:KG {id: 'rom:pacman/proms/82s126.4a'}) SET n:Rom SET n += {file: '82s126.4a', offset: 32, size: 256, crc: '3eb3a8e4', sha1: '19097b5f60d1030f8b82d9f1d3a241f93e5c75d6', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4270, sourceColumn: 2, sourceEndLine: 4270};
MERGE (n:KG {id: 'region:pacman/namco'}) SET n:RomRegion SET n += {tag: 'namco', size: 512, flags: '0', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4171, sourceColumn: 2, sourceEndLine: 4171};
MERGE (n:KG {id: 'rom:pacman/namco/82s126.1m'}) SET n:Rom SET n += {file: '82s126.1m', offset: 0, size: 256, crc: 'a9cc86bf', sha1: 'bbcec0570aeceb582ff8238a4bc8546a23430081', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4273, sourceColumn: 2, sourceEndLine: 4273};
MERGE (n:KG {id: 'rom:pacman/namco/82s126.3m'}) SET n:Rom SET n += {file: '82s126.3m', offset: 256, size: 256, crc: '77245b66', sha1: '0c4d0bee858b97632411c440bea6948a74759746', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4274, sourceColumn: 2, sourceEndLine: 4274};
MERGE (n:KG {id: 'map:pacman_state.pacman_map'}) SET n:AddressMap SET n += {cls: 'pacman_state', name: 'pacman_map', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1049, sourceColumn: 1, sourceEndLine: 1068};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 16383, raw: 'map(0x0000, 0x3fff).mirror(0x8000).rom()', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1052, sourceColumn: 2, sourceEndLine: 1052, mirror: 32768, rom: true};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range1'}) SET n:AddressRange SET n += {start: 16384, end: 17407, raw: 'map(0x4000, 0x43ff).mirror(0xa000).ram().w(FUNC(pacman_state::pacman_videoram_w)).share("videoram")', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1053, sourceColumn: 2, sourceEndLine: 1053, mirror: 40960, ram: true, share: 'videoram'};
MERGE (n:KG {id: 'handler:pacman_state.pacman_videoram_w'}) SET n:Handler SET n += {method: 'pacman_videoram_w', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman_v.cpp', sourceLine: 235, sourceColumn: 1, sourceEndLine: 239, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_videoram[offset] = data;
	m_bg_tilemap->mark_tile_dirty(offset);'};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range2'}) SET n:AddressRange SET n += {start: 17408, end: 18431, raw: 'map(0x4400, 0x47ff).mirror(0xa000).ram().w(FUNC(pacman_state::pacman_colorram_w)).share("colorram")', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1054, sourceColumn: 2, sourceEndLine: 1054, mirror: 40960, ram: true, share: 'colorram'};
MERGE (n:KG {id: 'handler:pacman_state.pacman_colorram_w'}) SET n:Handler SET n += {method: 'pacman_colorram_w', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman_v.cpp', sourceLine: 241, sourceColumn: 1, sourceEndLine: 245, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_colorram[offset] = data;
	m_bg_tilemap->mark_tile_dirty(offset);'};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range3'}) SET n:AddressRange SET n += {start: 18432, end: 19455, raw: 'map(0x4800, 0x4bff).mirror(0xa000).r(FUNC(pacman_state::pacman_read_nop)).nopw()', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1055, sourceColumn: 2, sourceEndLine: 1055, mirror: 40960, nopw: true};
MERGE (n:KG {id: 'handler:pacman_state.pacman_read_nop'}) SET n:Handler SET n += {method: 'pacman_read_nop', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1030, sourceColumn: 1, sourceEndLine: 1039, sourceParameters: '', sourceBody: '// Return value of reading the bus with no devices enabled.
	// This seems to be common but more tests are needed. Ms Pacman reads bytes in sequence
	// until it hits a 0 for a delimiter, including empty areas.  It writes to "random"
	// addresses each time. This causes the maze to invert sometimes.  See code at $95c3 where
	// level($4e13)=134. DW
	// tests on exactly what determines the value returned have thus far proved inconclusive
	return 0xbf;'};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range4'}) SET n:AddressRange SET n += {start: 19456, end: 20463, raw: 'map(0x4c00, 0x4fef).mirror(0xa000).ram()', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1056, sourceColumn: 2, sourceEndLine: 1056, mirror: 40960, ram: true};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range5'}) SET n:AddressRange SET n += {start: 20464, end: 20479, raw: 'map(0x4ff0, 0x4fff).mirror(0xa000).ram().share("spriteram")', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1057, sourceColumn: 2, sourceEndLine: 1057, mirror: 40960, ram: true, share: 'spriteram'};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range6'}) SET n:AddressRange SET n += {start: 20480, end: 20487, raw: 'map(0x5000, 0x5007).mirror(0xaf38).w(m_mainlatch, FUNC(ls259_device::write_d0))', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1058, sourceColumn: 2, sourceEndLine: 1058, mirror: 44856};
MERGE (n:KG {id: 'handler:ls259_device.write_d0'}) SET n:Handler SET n += {method: 'write_d0', ownerClass: 'ls259_device', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1454, sourceColumn: 2, sourceEndLine: 1454};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range7'}) SET n:AddressRange SET n += {start: 20544, end: 20575, raw: 'map(0x5040, 0x505f).mirror(0xaf00).w(m_namco_sound, FUNC(namco_wsg_device::pacman_sound_w))', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1059, sourceColumn: 2, sourceEndLine: 1059, mirror: 44800};
MERGE (n:KG {id: 'handler:namco_wsg_device.pacman_sound_w'}) SET n:Handler SET n += {method: 'pacman_sound_w', ownerClass: 'namco_wsg_device', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1455, sourceColumn: 2, sourceEndLine: 1455};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range8'}) SET n:AddressRange SET n += {start: 20576, end: 20591, raw: 'map(0x5060, 0x506f).mirror(0xaf00).writeonly().share("spriteram2")', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1060, sourceColumn: 2, sourceEndLine: 1060, mirror: 44800, writeonly: true, share: 'spriteram2'};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range9'}) SET n:AddressRange SET n += {start: 20592, end: 20607, raw: 'map(0x5070, 0x507f).mirror(0xaf00).nopw()', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1061, sourceColumn: 2, sourceEndLine: 1061, mirror: 44800, nopw: true};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range10'}) SET n:AddressRange SET n += {start: 20608, end: 20608, raw: 'map(0x5080, 0x5080).mirror(0xaf3f).nopw()', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1062, sourceColumn: 2, sourceEndLine: 1062, mirror: 44863, nopw: true};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range11'}) SET n:AddressRange SET n += {start: 20672, end: 20672, raw: 'map(0x50c0, 0x50c0).mirror(0xaf3f).w(m_watchdog, FUNC(watchdog_timer_device::reset_w))', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1063, sourceColumn: 2, sourceEndLine: 1063, mirror: 44863};
MERGE (n:KG {id: 'handler:watchdog_timer_device.reset_w'}) SET n:Handler SET n += {method: 'reset_w', ownerClass: 'watchdog_timer_device', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1459, sourceColumn: 2, sourceEndLine: 1459};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range12'}) SET n:AddressRange SET n += {start: 20480, end: 20480, raw: 'map(0x5000, 0x5000).mirror(0xaf3f).portr("IN0")', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1064, sourceColumn: 2, sourceEndLine: 1064, mirror: 44863, portRead: 'IN0'};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range13'}) SET n:AddressRange SET n += {start: 20544, end: 20544, raw: 'map(0x5040, 0x5040).mirror(0xaf3f).portr("IN1")', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1065, sourceColumn: 2, sourceEndLine: 1065, mirror: 44863, portRead: 'IN1'};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range14'}) SET n:AddressRange SET n += {start: 20608, end: 20608, raw: 'map(0x5080, 0x5080).mirror(0xaf3f).portr("DSW1")', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1066, sourceColumn: 2, sourceEndLine: 1066, mirror: 44863, portRead: 'DSW1'};
MERGE (n:KG {id: 'map:pacman_state.pacman_map/range15'}) SET n:AddressRange SET n += {start: 20672, end: 20672, raw: 'map(0x50c0, 0x50c0).mirror(0xaf3f).portr("DSW2")', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1067, sourceColumn: 2, sourceEndLine: 1067, mirror: 44863, portRead: 'DSW2'};
MERGE (n:KG {id: 'map:pacman_state.writeport'}) SET n:AddressMap SET n += {cls: 'pacman_state', name: 'writeport', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1475, sourceColumn: 1, sourceEndLine: 1479, globalMask: 255};
MERGE (n:KG {id: 'map:pacman_state.writeport/range0'}) SET n:AddressRange SET n += {start: 0, end: 0, raw: 'map(0x00, 0x00).w(FUNC(pacman_state::pacman_interrupt_vector_w))', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1478, sourceColumn: 2, sourceEndLine: 1478};
MERGE (n:KG {id: 'handler:pacman_state.pacman_interrupt_vector_w'}) SET n:Handler SET n += {method: 'pacman_interrupt_vector_w', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 394, sourceColumn: 1, sourceEndLine: 397, sourceParameters: 'uint8_t data', sourceBody: 'm_interrupt_vector = data;'};
MERGE (n:KG {id: 'machine:pacman_state.pacman'}) SET n:MachineConfig SET n += {cls: 'pacman_state', name: 'pacman', calls: [], sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3705, sourceColumn: 1, sourceEndLine: 3747};
MERGE (n:KG {id: 'device:pacman_state.pacman/maincpu'}) SET n:Device SET n += {type: 'Z80', tag: 'maincpu', clock: 3072000, config: ['Z80(config, m_maincpu, 18.432_MHz_XTAL / 6)', 'm_maincpu->set_addrmap(AS_PROGRAM, &pacman_state::pacman_map)', 'm_maincpu->set_addrmap(AS_IO, &pacman_state::writeport)', 'm_maincpu->set_irq_acknowledge_callback(FUNC(pacman_state::interrupt_vector_r))'], sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3708, sourceColumn: 2, sourceEndLine: 3708};
MERGE (n:KG {id: 'device:pacman_state.pacman/maincpu/callback0'}) SET n:Callback SET n += {signal: 'set_irq_acknowledge_callback', operation: 'set_irq_acknowledge_callback', raw: 'm_maincpu->set_irq_acknowledge_callback(FUNC(pacman_state::interrupt_vector_r))', ownerTag: 'maincpu', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3711, sourceColumn: 2, sourceEndLine: 3711, targetClass: 'pacman_state', targetMethod: 'interrupt_vector_r'};
MERGE (n:KG {id: 'handler:pacman_state.interrupt_vector_r'}) SET n:Handler SET n += {method: 'interrupt_vector_r', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 399, sourceColumn: 1, sourceEndLine: 402, sourceParameters: 'int irqline', sourceBody: 'return m_interrupt_vector;'};
MERGE (n:KG {id: 'device:pacman_state.pacman/mainlatch'}) SET n:Device SET n += {type: 'LS259', tag: 'mainlatch', clock: null, config: ['LS259(config, m_mainlatch)', 'm_mainlatch->q_out_cb<0>().set(FUNC(pacman_state::irq_mask_w))', 'm_mainlatch->q_out_cb<1>().set("namco", FUNC(namco_wsg_device::sound_enable_w))', 'm_mainlatch->q_out_cb<3>().set(FUNC(pacman_state::flipscreen_w))', 'm_mainlatch->q_out_cb<7>().set(FUNC(pacman_state::coin_counter_w))'], sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3713, sourceColumn: 2, sourceEndLine: 3713};
MERGE (n:KG {id: 'device:pacman_state.pacman/mainlatch/callback0'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set', raw: 'm_mainlatch->q_out_cb<0>().set(FUNC(pacman_state::irq_mask_w))', ownerTag: 'mainlatch', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3714, sourceColumn: 2, sourceEndLine: 3714, slot: '0', targetClass: 'pacman_state', targetMethod: 'irq_mask_w'};
MERGE (n:KG {id: 'handler:pacman_state.irq_mask_w'}) SET n:Handler SET n += {method: 'irq_mask_w', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 380, sourceColumn: 1, sourceEndLine: 385, sourceParameters: 'int state', sourceBody: 'm_irq_mask = state;
	if (!state)
		m_maincpu->set_input_line(INPUT_LINE_IRQ0, CLEAR_LINE);'};
MERGE (n:KG {id: 'device:pacman_state.pacman/mainlatch/callback1'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set', raw: 'm_mainlatch->q_out_cb<1>().set("namco", FUNC(namco_wsg_device::sound_enable_w))', ownerTag: 'mainlatch', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3715, sourceColumn: 2, sourceEndLine: 3715, slot: '1', targetTag: 'namco', targetClass: 'namco_wsg_device', targetMethod: 'sound_enable_w'};
MERGE (n:KG {id: 'handler:namco_wsg_device.sound_enable_w'}) SET n:Handler SET n += {method: 'sound_enable_w', ownerClass: 'namco_wsg_device', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3892, sourceColumn: 2, sourceEndLine: 3892};
MERGE (n:KG {id: 'device:pacman_state.pacman/mainlatch/callback2'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set', raw: 'm_mainlatch->q_out_cb<3>().set(FUNC(pacman_state::flipscreen_w))', ownerTag: 'mainlatch', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3716, sourceColumn: 2, sourceEndLine: 3716, slot: '3', targetClass: 'pacman_state', targetMethod: 'flipscreen_w'};
MERGE (n:KG {id: 'handler:pacman_state.flipscreen_w'}) SET n:Handler SET n += {method: 'flipscreen_w', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman_v.cpp', sourceLine: 247, sourceColumn: 1, sourceEndLine: 251, sourceParameters: 'int state', sourceBody: 'm_flipscreen = state;
	m_bg_tilemap->set_flip(m_flipscreen * (TILEMAP_FLIPX + TILEMAP_FLIPY));'};
MERGE (n:KG {id: 'device:pacman_state.pacman/mainlatch/callback3'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set', raw: 'm_mainlatch->q_out_cb<7>().set(FUNC(pacman_state::coin_counter_w))', ownerTag: 'mainlatch', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3717, sourceColumn: 2, sourceEndLine: 3717, slot: '7', targetClass: 'pacman_state', targetMethod: 'coin_counter_w'};
MERGE (n:KG {id: 'handler:pacman_state.coin_counter_w'}) SET n:Handler SET n += {method: 'coin_counter_w', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 493, sourceColumn: 1, sourceEndLine: 496, sourceParameters: 'int state', sourceBody: 'machine().bookkeeping().coin_counter_w(0, state);'};
MERGE (n:KG {id: 'device:pacman_state.pacman/watchdog'}) SET n:Device SET n += {type: 'WATCHDOG_TIMER', tag: 'watchdog', clock: null, config: ['WATCHDOG_TIMER(config, m_watchdog)', 'm_watchdog->set_vblank_count("screen", 16)'], sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3725, sourceColumn: 2, sourceEndLine: 3725};
MERGE (n:KG {id: 'device:pacman_state.pacman/gfxdecode'}) SET n:Device SET n += {type: 'GFXDECODE', tag: 'gfxdecode', clock: null, config: ['GFXDECODE(config, m_gfxdecode, m_palette, gfx_pacman)'], sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3729, sourceColumn: 2, sourceEndLine: 3729, clockExpr: 'm_palette, gfx_pacman'};
MERGE (n:KG {id: 'device:pacman_state.pacman/palette'}) SET n:Device SET n += {type: 'PALETTE', tag: 'palette', clock: null, config: ['PALETTE(config, m_palette, FUNC(pacman_state::pacman_palette), 128 * 4, 32)'], sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3731, sourceColumn: 2, sourceEndLine: 3731, clockExpr: 'FUNC(pacman_state::pacman_palette), 128 * 4, 32'};
MERGE (n:KG {id: 'device:pacman_state.pacman/screen'}) SET n:Device SET n += {type: 'SCREEN', tag: 'screen', clock: null, config: ['SCREEN(config, m_screen, SCREEN_TYPE_RASTER)', 'm_screen->set_raw(18.432_MHz_XTAL / 3, 384, 0, 288, 264, 0  , 224  )', 'm_screen->set_screen_update(FUNC(pacman_state::screen_update_pacman))', 'm_screen->set_palette(m_palette)', 'm_screen->screen_vblank().set(FUNC(pacman_state::vblank_irq))'], sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3733, sourceColumn: 2, sourceEndLine: 3733, configCalls: ['set_raw(6144000,384,0,288,264,0,224)'], clockExpr: 'SCREEN_TYPE_RASTER', screenRaw: [6144000, 384, 0, 288, 264, 0, 224]};
MERGE (n:KG {id: 'device:pacman_state.pacman/screen/callback0'}) SET n:Callback SET n += {signal: 'set_screen_update', operation: 'set_screen_update', raw: 'm_screen->set_screen_update(FUNC(pacman_state::screen_update_pacman))', ownerTag: 'screen', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3736, sourceColumn: 2, sourceEndLine: 3736, targetClass: 'pacman_state', targetMethod: 'screen_update_pacman'};
MERGE (n:KG {id: 'handler:pacman_state.screen_update_pacman'}) SET n:Handler SET n += {method: 'screen_update_pacman', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman_v.cpp', sourceLine: 362, sourceColumn: 1, sourceEndLine: 376, sourceParameters: 'screen_device &screen, bitmap_ind16 &bitmap, const rectangle &cliprect', sourceBody: 'if (m_bgpriority != 0)
		bitmap.fill(0, cliprect);
	else
		m_bg_tilemap->draw(screen, bitmap, cliprect, TILEMAP_DRAW_OPAQUE, 0);

	if (m_spriteram != nullptr)
		draw_sprites(screen, bitmap, cliprect);

	if (m_bgpriority != 0)
		m_bg_tilemap->draw(screen, bitmap, cliprect, 0, 0);

	return 0;'};
MERGE (n:KG {id: 'device:pacman_state.pacman/screen/callback1'}) SET n:Callback SET n += {signal: 'screen_vblank', operation: 'set', raw: 'm_screen->screen_vblank().set(FUNC(pacman_state::vblank_irq))', ownerTag: 'screen', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3738, sourceColumn: 2, sourceEndLine: 3738, targetClass: 'pacman_state', targetMethod: 'vblank_irq'};
MERGE (n:KG {id: 'handler:pacman_state.vblank_irq'}) SET n:Handler SET n += {method: 'vblank_irq', ownerClass: 'pacman_state', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 362, sourceColumn: 1, sourceEndLine: 366, sourceParameters: 'int state', sourceBody: 'if (state && m_irq_mask)
		m_maincpu->set_input_line(INPUT_LINE_IRQ0, ASSERT_LINE);'};
MERGE (n:KG {id: 'device:pacman_state.pacman/namco'}) SET n:Device SET n += {type: 'NAMCO_WSG', tag: 'namco', clock: 96000, config: ['NAMCO_WSG(config, m_namco_sound, 18.432_MHz_XTAL / 6 / 32)', 'm_namco_sound->add_route(ALL_OUTPUTS, "mono", 1.0)'], sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3745, sourceColumn: 2, sourceEndLine: 3745};
MERGE (n:KG {id: 'audioroute:device:pacman_state.pacman/namco/0'}) SET n:AudioRoute SET n += {output: 'ALL_OUTPUTS', target: 'mono', gain: 1, raw: 'm_namco_sound->add_route(ALL_OUTPUTS, "mono", 1.0)', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3746, sourceColumn: 2, sourceEndLine: 3746};
MERGE (n:KG {id: 'inputs:pacman'}) SET n:InputPorts SET n += {name: 'pacman', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1569, sourceColumn: 8, sourceEndLine: 1569};
MERGE (n:KG {id: 'inputs:pacman/IN0'}) SET n:Port SET n += {tag: 'IN0', modify: false};
MERGE (n:KG {id: 'inputs:pacman/IN0/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_UP', modifiers: ['PORT_PLAYER(1)', 'PORT_4WAY']};
MERGE (n:KG {id: 'inputs:pacman/IN0/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_LEFT', modifiers: ['PORT_PLAYER(1)', 'PORT_4WAY']};
MERGE (n:KG {id: 'inputs:pacman/IN0/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_RIGHT', modifiers: ['PORT_PLAYER(1)', 'PORT_4WAY']};
MERGE (n:KG {id: 'inputs:pacman/IN0/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_DOWN', modifiers: ['PORT_PLAYER(1)', 'PORT_4WAY']};
MERGE (n:KG {id: 'inputs:pacman/IN0/f4'}) SET n:PortField SET n += {kind: 'dip', mask: 16, name: 'Rack Test (Cheat)', defaultValue: 16, location: 'SW:7', settings: ['16=Off', '0=On']};
MERGE (n:KG {id: 'inputs:pacman/IN0/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_COIN1'};
MERGE (n:KG {id: 'inputs:pacman/IN0/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 64, activeLow: true, type: 'IPT_COIN2'};
MERGE (n:KG {id: 'inputs:pacman/IN0/f7'}) SET n:PortField SET n += {kind: 'bit', mask: 128, activeLow: true, type: 'IPT_SERVICE1'};
MERGE (n:KG {id: 'inputs:pacman/IN1'}) SET n:Port SET n += {tag: 'IN1', modify: false};
MERGE (n:KG {id: 'inputs:pacman/IN1/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_UP', modifiers: ['PORT_PLAYER(2)', 'PORT_4WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:pacman/IN1/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_LEFT', modifiers: ['PORT_PLAYER(2)', 'PORT_4WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:pacman/IN1/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_RIGHT', modifiers: ['PORT_PLAYER(2)', 'PORT_4WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:pacman/IN1/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_DOWN', modifiers: ['PORT_PLAYER(2)', 'PORT_4WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:pacman/IN1/f4'}) SET n:PortField SET n += {kind: 'service', mask: 16, activeLow: true};
MERGE (n:KG {id: 'inputs:pacman/IN1/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_START1'};
MERGE (n:KG {id: 'inputs:pacman/IN1/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 64, activeLow: true, type: 'IPT_START2'};
MERGE (n:KG {id: 'inputs:pacman/IN1/f7'}) SET n:PortField SET n += {kind: 'dip', mask: 128, name: 'Cabinet', defaultValue: 128, settings: ['128=Upright', '0=Cocktail']};
MERGE (n:KG {id: 'inputs:pacman/DSW1'}) SET n:Port SET n += {tag: 'DSW1', modify: false};
MERGE (n:KG {id: 'inputs:pacman/DSW1/f0'}) SET n:PortField SET n += {kind: 'dip', mask: 3, name: 'Coinage', defaultValue: 1, location: 'SW:1,2', settings: ['3=2C 1C', '1=1C 1C', '2=1C 2C', '0=Free Play']};
MERGE (n:KG {id: 'inputs:pacman/DSW1/f1'}) SET n:PortField SET n += {kind: 'dip', mask: 12, name: 'Lives', defaultValue: 8, location: 'SW:3,4', settings: ['0=1', '4=2', '8=3', '12=5']};
MERGE (n:KG {id: 'inputs:pacman/DSW1/f2'}) SET n:PortField SET n += {kind: 'dip', mask: 48, name: 'Bonus Life', defaultValue: 0, location: 'SW:5,6', settings: ['0=10000', '16=15000', '32=20000', '48=None']};
MERGE (n:KG {id: 'inputs:pacman/DSW1/f3'}) SET n:PortField SET n += {kind: 'dip', mask: 64, name: 'Difficulty', defaultValue: 64, settings: ['64=Normal', '0=Hard']};
MERGE (n:KG {id: 'inputs:pacman/DSW1/f4'}) SET n:PortField SET n += {kind: 'dip', mask: 128, name: 'Ghost Names', defaultValue: 128, settings: ['128=Normal', '0=Alternate']};
MERGE (n:KG {id: 'inputs:pacman/DSW2'}) SET n:Port SET n += {tag: 'DSW2', modify: false};
MERGE (n:KG {id: 'inputs:pacman/DSW2/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 255, activeLow: false, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'gfxlayout:tilelayout'}) SET n:GfxLayout SET n += {name: 'tilelayout', width: 8, height: 8, total: 'RGN_FRAC(1,2)', planes: 2, planeOffsets: [0, 4], xOffsets: [64, 65, 66, 67, 0, 1, 2, 3], yOffsets: [0, 8, 16, 24, 32, 40, 48, 56], charIncrement: 128};
MERGE (n:KG {id: 'gfxlayout:spritelayout'}) SET n:GfxLayout SET n += {name: 'spritelayout', width: 16, height: 16, total: 'RGN_FRAC(1,2)', planes: 2, planeOffsets: [0, 4], xOffsets: [64, 65, 66, 67, 128, 129, 130, 131, 192, 193, 194, 195, 0, 1, 2, 3], yOffsets: [0, 8, 16, 24, 32, 40, 48, 56, 256, 264, 272, 280, 288, 296, 304, 312], charIncrement: 512};
MERGE (n:KG {id: 'gfxdecode:gfx_pacman'}) SET n:GfxDecode SET n += {name: 'gfx_pacman', sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3668, sourceColumn: 8, sourceEndLine: 3668};
MERGE (n:KG {id: 'gfxdecode:gfx_pacman/e0'}) SET n:GfxDecodeEntry SET n += {region: 'gfx1', offset: 0, layout: 'tilelayout', colorBase: 0, colorCount: 128, xscale: 1, yscale: 1};
MERGE (n:KG {id: 'gfxdecode:gfx_pacman/e1'}) SET n:GfxDecodeEntry SET n += {region: 'gfx1', offset: 4096, layout: 'spritelayout', colorBase: 0, colorCount: 128, xscale: 1, yscale: 1};
MATCH (a:KG {id: 'game:pacman'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 8996, sourceColumn: 1, sourceEndLine: 8996};
MATCH (a:KG {id: 'game:pacman'}), (b:KG {id: 'game:puckman'}) MERGE (a)-[r:CLONE_OF]->(b);
MATCH (a:KG {id: 'game:pacman'}), (b:KG {id: 'machine:pacman_state.pacman'}) MERGE (a)-[r:USES_MACHINE]->(b);
MATCH (a:KG {id: 'game:pacman'}), (b:KG {id: 'inputs:pacman'}) MERGE (a)-[r:USES_INPUTS]->(b);
MATCH (a:KG {id: 'game:pacman'}), (b:KG {id: 'romset:pacman'}) MERGE (a)-[r:USES_ROMSET]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:emu.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:pacman.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:jumpshot.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:pacplus.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:cpu/s2650/s2650.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:cpu/z80/z80.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:machine/nvram.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:sound/ay8910.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:sound/sn76496.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:screen.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/pacman/pacman.cpp'}), (b:KG {id: 'file:speaker.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'game:puckman'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 8991, sourceColumn: 1, sourceEndLine: 8991};
MATCH (a:KG {id: 'game:puckman'}), (b:KG {id: 'machine:pacman_state.pacman'}) MERGE (a)-[r:USES_MACHINE]->(b);
MATCH (a:KG {id: 'game:puckman'}), (b:KG {id: 'inputs:pacman'}) MERGE (a)-[r:USES_INPUTS]->(b);
MATCH (a:KG {id: 'game:puckman'}), (b:KG {id: 'romset:puckman'}) MERGE (a)-[r:USES_ROMSET]->(b);
MATCH (a:KG {id: 'machine:pacman_state.pacman'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3705, sourceColumn: 1, sourceEndLine: 3747};
MATCH (a:KG {id: 'machine:pacman_state.pacman'}), (b:KG {id: 'device:pacman_state.pacman/maincpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:pacman_state.pacman'}), (b:KG {id: 'device:pacman_state.pacman/mainlatch'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:pacman_state.pacman'}), (b:KG {id: 'device:pacman_state.pacman/watchdog'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:pacman_state.pacman'}), (b:KG {id: 'device:pacman_state.pacman/gfxdecode'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:pacman_state.pacman'}), (b:KG {id: 'gfxdecode:gfx_pacman'}) MERGE (a)-[r:DECODES]->(b) SET r += {deviceTag: 'gfxdecode'};
MATCH (a:KG {id: 'machine:pacman_state.pacman'}), (b:KG {id: 'device:pacman_state.pacman/palette'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:pacman_state.pacman'}), (b:KG {id: 'device:pacman_state.pacman/screen'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:pacman_state.pacman'}), (b:KG {id: 'device:pacman_state.pacman/namco'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'inputs:pacman'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1569, sourceColumn: 8, sourceEndLine: 1569};
MATCH (a:KG {id: 'inputs:pacman'}), (b:KG {id: 'inputs:pacman/IN0'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:pacman'}), (b:KG {id: 'inputs:pacman/IN1'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:pacman'}), (b:KG {id: 'inputs:pacman/DSW1'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:pacman'}), (b:KG {id: 'inputs:pacman/DSW2'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'romset:pacman'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4319, sourceColumn: 1, sourceEndLine: 4319};
MATCH (a:KG {id: 'romset:pacman'}), (b:KG {id: 'region:pacman/maincpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:pacman'}), (b:KG {id: 'region:pacman/gfx1'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:pacman'}), (b:KG {id: 'region:pacman/proms'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:pacman'}), (b:KG {id: 'region:pacman/namco'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:puckman'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 4150, sourceColumn: 1, sourceEndLine: 4150};
MATCH (a:KG {id: 'romset:puckman'}), (b:KG {id: 'region:puckman/maincpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:puckman'}), (b:KG {id: 'region:puckman/gfx1'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:puckman'}), (b:KG {id: 'region:puckman/proms'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:puckman'}), (b:KG {id: 'region:puckman/namco'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/maincpu'}), (b:KG {id: 'device:pacman_state.pacman/maincpu/callback0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/maincpu'}), (b:KG {id: 'map:pacman_state.pacman_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:pacman_state.pacman/maincpu'}), (b:KG {id: 'map:pacman_state.writeport'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_IO'};
MATCH (a:KG {id: 'device:pacman_state.pacman/mainlatch'}), (b:KG {id: 'device:pacman_state.pacman/mainlatch/callback0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/mainlatch'}), (b:KG {id: 'device:pacman_state.pacman/mainlatch/callback1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/mainlatch'}), (b:KG {id: 'device:pacman_state.pacman/mainlatch/callback2'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/mainlatch'}), (b:KG {id: 'device:pacman_state.pacman/mainlatch/callback3'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_pacman'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 3668, sourceColumn: 8, sourceEndLine: 3668};
MATCH (a:KG {id: 'gfxdecode:gfx_pacman'}), (b:KG {id: 'gfxdecode:gfx_pacman/e0'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_pacman'}), (b:KG {id: 'gfxdecode:gfx_pacman/e1'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/screen'}), (b:KG {id: 'device:pacman_state.pacman/screen/callback0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/screen'}), (b:KG {id: 'device:pacman_state.pacman/screen/callback1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/namco'}), (b:KG {id: 'audioroute:device:pacman_state.pacman/namco/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN0'}), (b:KG {id: 'inputs:pacman/IN0/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN0'}), (b:KG {id: 'inputs:pacman/IN0/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN0'}), (b:KG {id: 'inputs:pacman/IN0/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN0'}), (b:KG {id: 'inputs:pacman/IN0/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN0'}), (b:KG {id: 'inputs:pacman/IN0/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN0'}), (b:KG {id: 'inputs:pacman/IN0/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN0'}), (b:KG {id: 'inputs:pacman/IN0/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN0'}), (b:KG {id: 'inputs:pacman/IN0/f7'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN1'}), (b:KG {id: 'inputs:pacman/IN1/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN1'}), (b:KG {id: 'inputs:pacman/IN1/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN1'}), (b:KG {id: 'inputs:pacman/IN1/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN1'}), (b:KG {id: 'inputs:pacman/IN1/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN1'}), (b:KG {id: 'inputs:pacman/IN1/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN1'}), (b:KG {id: 'inputs:pacman/IN1/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN1'}), (b:KG {id: 'inputs:pacman/IN1/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/IN1'}), (b:KG {id: 'inputs:pacman/IN1/f7'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/DSW1'}), (b:KG {id: 'inputs:pacman/DSW1/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/DSW1'}), (b:KG {id: 'inputs:pacman/DSW1/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/DSW1'}), (b:KG {id: 'inputs:pacman/DSW1/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/DSW1'}), (b:KG {id: 'inputs:pacman/DSW1/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/DSW1'}), (b:KG {id: 'inputs:pacman/DSW1/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:pacman/DSW2'}), (b:KG {id: 'inputs:pacman/DSW2/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'region:pacman/maincpu'}), (b:KG {id: 'rom:pacman/maincpu/pacman.6e'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:pacman/maincpu'}), (b:KG {id: 'rom:pacman/maincpu/pacman.6f'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:pacman/maincpu'}), (b:KG {id: 'rom:pacman/maincpu/pacman.6h'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:pacman/maincpu'}), (b:KG {id: 'rom:pacman/maincpu/pacman.6j'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:pacman/gfx1'}), (b:KG {id: 'rom:pacman/gfx1/pacman.5e'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:pacman/gfx1'}), (b:KG {id: 'rom:pacman/gfx1/pacman.5f'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:pacman/proms'}), (b:KG {id: 'rom:pacman/proms/82s123.7f'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:pacman/proms'}), (b:KG {id: 'rom:pacman/proms/82s126.4a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:pacman/namco'}), (b:KG {id: 'rom:pacman/namco/82s126.1m'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:pacman/namco'}), (b:KG {id: 'rom:pacman/namco/82s126.3m'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/maincpu'}), (b:KG {id: 'rom:puckman/maincpu/pm1_prg1.6e'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/maincpu'}), (b:KG {id: 'rom:puckman/maincpu/pm1_prg2.6k'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/maincpu'}), (b:KG {id: 'rom:puckman/maincpu/pm1_prg3.6f'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/maincpu'}), (b:KG {id: 'rom:puckman/maincpu/pm1_prg4.6m'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/maincpu'}), (b:KG {id: 'rom:puckman/maincpu/pm1_prg5.6h'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/maincpu'}), (b:KG {id: 'rom:puckman/maincpu/pm1_prg6.6n'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/maincpu'}), (b:KG {id: 'rom:puckman/maincpu/pm1_prg7.6j'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/maincpu'}), (b:KG {id: 'rom:puckman/maincpu/pm1_prg8.6p'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/gfx1'}), (b:KG {id: 'rom:puckman/gfx1/pm1_chg1.5e'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/gfx1'}), (b:KG {id: 'rom:puckman/gfx1/pm1_chg2.5h'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/gfx1'}), (b:KG {id: 'rom:puckman/gfx1/pm1_chg3.5f'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/gfx1'}), (b:KG {id: 'rom:puckman/gfx1/pm1_chg4.5j'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/proms'}), (b:KG {id: 'rom:puckman/proms/pm1-1.7f'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/proms'}), (b:KG {id: 'rom:puckman/proms/pm1-4.4a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/namco'}), (b:KG {id: 'rom:puckman/namco/pm1-3.1m'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:puckman/namco'}), (b:KG {id: 'rom:puckman/namco/pm1-2.3m'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/maincpu/callback0'}), (b:KG {id: 'handler:pacman_state.interrupt_vector_r'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1049, sourceColumn: 1, sourceEndLine: 1068};
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range5'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range6'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range7'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range8'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range9'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range10'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range11'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range12'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range13'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range14'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map'}), (b:KG {id: 'map:pacman_state.pacman_map/range15'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:pacman_state.writeport'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/pacman/pacman.cpp', sourceLine: 1475, sourceColumn: 1, sourceEndLine: 1479};
MATCH (a:KG {id: 'map:pacman_state.writeport'}), (b:KG {id: 'map:pacman_state.writeport/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/mainlatch/callback0'}), (b:KG {id: 'handler:pacman_state.irq_mask_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/mainlatch/callback1'}), (b:KG {id: 'handler:namco_wsg_device.sound_enable_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/mainlatch/callback2'}), (b:KG {id: 'handler:pacman_state.flipscreen_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/mainlatch/callback3'}), (b:KG {id: 'handler:pacman_state.coin_counter_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_pacman/e0'}), (b:KG {id: 'gfxlayout:tilelayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_pacman/e1'}), (b:KG {id: 'gfxlayout:spritelayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/screen/callback0'}), (b:KG {id: 'handler:pacman_state.screen_update_pacman'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:pacman_state.pacman/screen/callback1'}), (b:KG {id: 'handler:pacman_state.vblank_irq'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map/range1'}), (b:KG {id: 'handler:pacman_state.pacman_videoram_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map/range2'}), (b:KG {id: 'handler:pacman_state.pacman_colorram_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map/range3'}), (b:KG {id: 'handler:pacman_state.pacman_read_nop'}) MERGE (a)-[r:READS]->(b);
MATCH (a:KG {id: 'map:pacman_state.pacman_map/range6'}), (b:KG {id: 'handler:ls259_device.write_d0'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'mainlatch'};
MATCH (a:KG {id: 'map:pacman_state.pacman_map/range7'}), (b:KG {id: 'handler:namco_wsg_device.pacman_sound_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'namco'};
MATCH (a:KG {id: 'map:pacman_state.pacman_map/range11'}), (b:KG {id: 'handler:watchdog_timer_device.reset_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'watchdog'};
MATCH (a:KG {id: 'map:pacman_state.writeport/range0'}), (b:KG {id: 'handler:pacman_state.pacman_interrupt_vector_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'gfxlayout:tilelayout'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
MATCH (a:KG {id: 'gfxlayout:spritelayout'}), (b:KG {id: 'file:src/mame/pacman/pacman.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
