// mamekit knowledge graph — driver src/mame/capcom/commando.cpp
// generated 2026-08-22T05:52:09.423Z
CREATE CONSTRAINT mamekit_id IF NOT EXISTS FOR (n:KG) REQUIRE n.id IS UNIQUE;
MERGE (n:KG {id: 'file:src/mame/capcom/commando.cpp'}) SET n:SourceFile SET n += {path: 'src/mame/capcom/commando.cpp'};
MERGE (n:KG {id: 'file:emu.h'}) SET n:SourceFile SET n += {path: 'emu.h', external: true};
MERGE (n:KG {id: 'file:cpu/z80/z80.h'}) SET n:SourceFile SET n += {path: 'cpu/z80/z80.h', external: true};
MERGE (n:KG {id: 'file:machine/gen_latch.h'}) SET n:SourceFile SET n += {path: 'machine/gen_latch.h', external: true};
MERGE (n:KG {id: 'file:machine/timer.h'}) SET n:SourceFile SET n += {path: 'machine/timer.h', external: true};
MERGE (n:KG {id: 'file:sound/ymopn.h'}) SET n:SourceFile SET n += {path: 'sound/ymopn.h', external: true};
MERGE (n:KG {id: 'file:video/bufsprite.h'}) SET n:SourceFile SET n += {path: 'video/bufsprite.h', external: true};
MERGE (n:KG {id: 'file:emupal.h'}) SET n:SourceFile SET n += {path: 'emupal.h', external: true};
MERGE (n:KG {id: 'file:screen.h'}) SET n:SourceFile SET n += {path: 'screen.h', external: true};
MERGE (n:KG {id: 'file:speaker.h'}) SET n:SourceFile SET n += {path: 'speaker.h', external: true};
MERGE (n:KG {id: 'file:tilemap.h'}) SET n:SourceFile SET n += {path: 'tilemap.h', external: true};
MERGE (n:KG {id: 'game:commando'}) SET n:Game SET n += {name: 'commando', year: '1985', company: 'Capcom', fullname: 'Commando (World)', monitor: 'ROT270', cls: 'commando_state', init: 'init_commando', flags: 'MACHINE_SUPPORTS_SAVE', kind: 'arcade', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 1055, sourceColumn: 1, sourceEndLine: 1055, romTransforms: ['{"kind":"byte-substitution","sourceRegion":"maincpu","targetRegion":"decrypted_opcodes","start":1,"end":49152,"table":[0,1,32,33,64,65,96,97,128,129,160,161,192,193,224,225,16,17,48,49,80,81,112,113,144,145,176,177,208,209,240,241,2,3,34,35,66,67,98,99,130,131,162,163,194,195,226,227,18,19,50,51,82,83,114,115,146,147,178,179,210,211,242,243,4,5,36,37,68,69,100,101,132,133,164,165,196,197,228,229,20,21,52,53,84,85,116,117,148,149,180,181,212,213,244,245,6,7,38,39,70,71,102,103,134,135,166,167,198,199,230,231,22,23,54,55,86,87,118,119,150,151,182,183,214,215,246,247,8,9,40,41,72,73,104,105,136,137,168,169,200,201,232,233,24,25,56,57,88,89,120,121,152,153,184,185,216,217,248,249,10,11,42,43,74,75,106,107,138,139,170,171,202,203,234,235,26,27,58,59,90,91,122,123,154,155,186,187,218,219,250,251,12,13,44,45,76,77,108,109,140,141,172,173,204,205,236,237,28,29,60,61,92,93,124,125,156,157,188,189,220,221,252,253,14,15,46,47,78,79,110,111,142,143,174,175,206,207,238,239,30,31,62,63,94,95,126,127,158,159,190,191,222,223,254,255]}']};
MERGE (n:KG {id: 'romset:commando'}) SET n:RomSet SET n += {name: 'commando', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 593, sourceColumn: 1, sourceEndLine: 593};
MERGE (n:KG {id: 'region:commando/maincpu'}) SET n:RomRegion SET n += {tag: 'maincpu', size: 49152, flags: '0', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 594, sourceColumn: 2, sourceEndLine: 594};
MERGE (n:KG {id: 'rom:commando/maincpu/cm04.9m'}) SET n:Rom SET n += {file: 'cm04.9m', offset: 0, size: 32768, crc: '8438b694', sha1: 'e154478d8f1b635355bd777370acabe49cb9d309', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 595, sourceColumn: 2, sourceEndLine: 595};
MERGE (n:KG {id: 'rom:commando/maincpu/cm03.8m'}) SET n:Rom SET n += {file: 'cm03.8m', offset: 32768, size: 16384, crc: '35486542', sha1: '531a85c9e03970ce037be84f2240c2df6f6e3ec1', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 596, sourceColumn: 2, sourceEndLine: 596};
MERGE (n:KG {id: 'region:commando/audiocpu'}) SET n:RomRegion SET n += {tag: 'audiocpu', size: 65536, flags: '0', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 598, sourceColumn: 2, sourceEndLine: 598};
MERGE (n:KG {id: 'rom:commando/audiocpu/cm02.9f'}) SET n:Rom SET n += {file: 'cm02.9f', offset: 0, size: 16384, crc: 'f9cc4a74', sha1: 'ee8dd73919c6f47f62cc6d999de9510db9f79b8f', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 599, sourceColumn: 2, sourceEndLine: 599};
MERGE (n:KG {id: 'region:commando/chars'}) SET n:RomRegion SET n += {tag: 'chars', size: 16384, flags: '0', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 601, sourceColumn: 2, sourceEndLine: 601};
MERGE (n:KG {id: 'rom:commando/chars/vt01.5d'}) SET n:Rom SET n += {file: 'vt01.5d', offset: 0, size: 16384, crc: '505726e0', sha1: '2435c87c9c9d78a6e703cf0e1f6a0288207fcd4c', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 602, sourceColumn: 2, sourceEndLine: 602};
MERGE (n:KG {id: 'region:commando/tiles'}) SET n:RomRegion SET n += {tag: 'tiles', size: 98304, flags: '0', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 604, sourceColumn: 2, sourceEndLine: 604};
MERGE (n:KG {id: 'rom:commando/tiles/vt11.5a'}) SET n:Rom SET n += {file: 'vt11.5a', offset: 0, size: 16384, crc: '7b2e1b48', sha1: '5d49e1d8146e4ef744445b68f35677302e875a85', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 605, sourceColumn: 2, sourceEndLine: 605};
MERGE (n:KG {id: 'rom:commando/tiles/vt12.6a'}) SET n:Rom SET n += {file: 'vt12.6a', offset: 16384, size: 16384, crc: '81b417d3', sha1: '5ec7e3f0c8069384a5f6eb39232c228b9d7b8c0c', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 606, sourceColumn: 2, sourceEndLine: 606};
MERGE (n:KG {id: 'rom:commando/tiles/vt13.7a'}) SET n:Rom SET n += {file: 'vt13.7a', offset: 32768, size: 16384, crc: '5612dbd2', sha1: '9e4e1a22b6cbf60607b9a81dae34482ae55f7c47', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 607, sourceColumn: 2, sourceEndLine: 607};
MERGE (n:KG {id: 'rom:commando/tiles/vt14.8a'}) SET n:Rom SET n += {file: 'vt14.8a', offset: 49152, size: 16384, crc: '2b2dee36', sha1: '8792278464fa3da47176582025f6673a15a581e2', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 608, sourceColumn: 2, sourceEndLine: 608};
MERGE (n:KG {id: 'rom:commando/tiles/vt15.9a'}) SET n:Rom SET n += {file: 'vt15.9a', offset: 65536, size: 16384, crc: 'de70babf', sha1: '6717e23baf55f84d3143fb432140a7c3e102ac26', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 609, sourceColumn: 2, sourceEndLine: 609};
MERGE (n:KG {id: 'rom:commando/tiles/vt16.10a'}) SET n:Rom SET n += {file: 'vt16.10a', offset: 81920, size: 16384, crc: '14178237', sha1: 'f896e71c7004349c9a46155edfd9f0aaa186065d', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 610, sourceColumn: 2, sourceEndLine: 610};
MERGE (n:KG {id: 'region:commando/sprites'}) SET n:RomRegion SET n += {tag: 'sprites', size: 98304, flags: '0', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 612, sourceColumn: 2, sourceEndLine: 612};
MERGE (n:KG {id: 'rom:commando/sprites/vt05.7e'}) SET n:Rom SET n += {file: 'vt05.7e', offset: 0, size: 16384, crc: '79f16e3d', sha1: '04e1f03a4d6b4cc2b81bce3a290bbb95de900d35', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 613, sourceColumn: 2, sourceEndLine: 613};
MERGE (n:KG {id: 'rom:commando/sprites/vt06.8e'}) SET n:Rom SET n += {file: 'vt06.8e', offset: 16384, size: 16384, crc: '26fee521', sha1: '2fbfc73ee860f72a20229a01d4da9f5cc2e858d3', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 614, sourceColumn: 2, sourceEndLine: 614};
MERGE (n:KG {id: 'rom:commando/sprites/vt07.9e'}) SET n:Rom SET n += {file: 'vt07.9e', offset: 32768, size: 16384, crc: 'ca88bdfd', sha1: '548b05460bc7983cc81f15c70e87f47d10db2812', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 615, sourceColumn: 2, sourceEndLine: 615};
MERGE (n:KG {id: 'rom:commando/sprites/vt08.7h'}) SET n:Rom SET n += {file: 'vt08.7h', offset: 49152, size: 16384, crc: '2019c883', sha1: '883c0156ceab99f4849fe36972c4162b4ac8c216', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 616, sourceColumn: 2, sourceEndLine: 616};
MERGE (n:KG {id: 'rom:commando/sprites/vt09.8h'}) SET n:Rom SET n += {file: 'vt09.8h', offset: 65536, size: 16384, crc: '98703982', sha1: 'ba9a9b0dcadd4f52502828408c4a19b0bd518351', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 617, sourceColumn: 2, sourceEndLine: 617};
MERGE (n:KG {id: 'rom:commando/sprites/vt10.9h'}) SET n:Rom SET n += {file: 'vt10.9h', offset: 81920, size: 16384, crc: 'f069d2f8', sha1: '2c92300a9407470b34965021de882f1f7a84730c', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 618, sourceColumn: 2, sourceEndLine: 618};
MERGE (n:KG {id: 'region:commando/irqprom'}) SET n:RomRegion SET n += {tag: 'irqprom', size: 256, flags: '0', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 620, sourceColumn: 2, sourceEndLine: 620};
MERGE (n:KG {id: 'rom:commando/irqprom/vtb5.6l'}) SET n:Rom SET n += {file: 'vtb5.6l', offset: 0, size: 256, crc: '712ac508', sha1: '5349d722ab6733afdda65f6e0a98322f0d515e86', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 621, sourceColumn: 2, sourceEndLine: 621};
MERGE (n:KG {id: 'region:commando/proms'}) SET n:RomRegion SET n += {tag: 'proms', size: 1280, flags: '0', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 623, sourceColumn: 2, sourceEndLine: 623};
MERGE (n:KG {id: 'rom:commando/proms/vtb1.1d'}) SET n:Rom SET n += {file: 'vtb1.1d', offset: 0, size: 256, crc: '3aba15a1', sha1: '8b057f6e26155dd9e48bde182e680fce4519f600', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 624, sourceColumn: 2, sourceEndLine: 624};
MERGE (n:KG {id: 'rom:commando/proms/vtb2.2d'}) SET n:Rom SET n += {file: 'vtb2.2d', offset: 256, size: 256, crc: '88865754', sha1: 'ca6dddca98baf00a65b2fb70b69cf4704ef8c831', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 625, sourceColumn: 2, sourceEndLine: 625};
MERGE (n:KG {id: 'rom:commando/proms/vtb3.3d'}) SET n:Rom SET n += {file: 'vtb3.3d', offset: 512, size: 256, crc: '4c14c3f6', sha1: '644ac17c7413f094ec9a15cba87bbd421b26321f', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 626, sourceColumn: 2, sourceEndLine: 626};
MERGE (n:KG {id: 'rom:commando/proms/vtb4.1h'}) SET n:Rom SET n += {file: 'vtb4.1h', offset: 768, size: 256, crc: 'b388c246', sha1: '038f9851699331ad887b6281a9df053dca3db8fd', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 627, sourceColumn: 2, sourceEndLine: 627};
MERGE (n:KG {id: 'rom:commando/proms/vtb6.6e'}) SET n:Rom SET n += {file: 'vtb6.6e', offset: 1024, size: 256, crc: '0eaf5158', sha1: 'bafd4108708f66cd7b280e47152b108f3e254fc9', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 628, sourceColumn: 2, sourceEndLine: 628};
MERGE (n:KG {id: 'map:commando_state.main_map'}) SET n:AddressMap SET n += {cls: 'commando_state', name: 'main_map', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 351, sourceColumn: 1, sourceEndLine: 371};
MERGE (n:KG {id: 'map:commando_state.main_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 49151, raw: 'map(0x0000, 0xbfff).rom()', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 353, sourceColumn: 2, sourceEndLine: 353, rom: true};
MERGE (n:KG {id: 'map:commando_state.main_map/range1'}) SET n:AddressRange SET n += {start: 49152, end: 49152, raw: 'map(0xc000, 0xc000).portr("SYSTEM")', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 354, sourceColumn: 2, sourceEndLine: 354, portRead: 'SYSTEM'};
MERGE (n:KG {id: 'map:commando_state.main_map/range2'}) SET n:AddressRange SET n += {start: 49153, end: 49153, raw: 'map(0xc001, 0xc001).portr("P1")', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 355, sourceColumn: 2, sourceEndLine: 355, portRead: 'P1'};
MERGE (n:KG {id: 'map:commando_state.main_map/range3'}) SET n:AddressRange SET n += {start: 49154, end: 49154, raw: 'map(0xc002, 0xc002).portr("P2")', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 356, sourceColumn: 2, sourceEndLine: 356, portRead: 'P2'};
MERGE (n:KG {id: 'map:commando_state.main_map/range4'}) SET n:AddressRange SET n += {start: 49155, end: 49155, raw: 'map(0xc003, 0xc003).portr("DSW1")', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 357, sourceColumn: 2, sourceEndLine: 357, portRead: 'DSW1'};
MERGE (n:KG {id: 'map:commando_state.main_map/range5'}) SET n:AddressRange SET n += {start: 49156, end: 49156, raw: 'map(0xc004, 0xc004).portr("DSW2")', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 358, sourceColumn: 2, sourceEndLine: 358, portRead: 'DSW2'};
MERGE (n:KG {id: 'map:commando_state.main_map/range6'}) SET n:AddressRange SET n += {start: 51200, end: 51200, raw: 'map(0xc800, 0xc800).w("soundlatch", FUNC(generic_latch_8_device::write))', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 359, sourceColumn: 2, sourceEndLine: 359};
MERGE (n:KG {id: 'handler:generic_latch_8_device.write'}) SET n:Handler SET n += {method: 'write', ownerClass: 'generic_latch_8_device', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 359, sourceColumn: 2, sourceEndLine: 359};
MERGE (n:KG {id: 'map:commando_state.main_map/range7'}) SET n:AddressRange SET n += {start: 51204, end: 51204, raw: 'map(0xc804, 0xc804).w(FUNC(commando_state::control_w))', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 360, sourceColumn: 2, sourceEndLine: 360};
MERGE (n:KG {id: 'handler:commando_state.control_w'}) SET n:Handler SET n += {method: 'control_w', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 270, sourceColumn: 1, sourceEndLine: 281, sourceParameters: 'uint8_t data', sourceBody: '// bits 0 and 1 are coin counters
	machine().bookkeeping().coin_counter_w(0, data & 0x01);
	machine().bookkeeping().coin_counter_w(1, data & 0x02);

	// bit 4 resets the sound CPU
	m_audiocpu->set_input_line(INPUT_LINE_RESET, (data & 0x10) ? ASSERT_LINE : CLEAR_LINE);

	// bit 7 flips screen
	flip_screen_set(data & 0x80);'};
MERGE (n:KG {id: 'map:commando_state.main_map/range8'}) SET n:AddressRange SET n += {start: 51206, end: 51206, raw: 'map(0xc806, 0xc806).w(m_spriteram, FUNC(buffered_spriteram8_device::write))', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 361, sourceColumn: 2, sourceEndLine: 361};
MERGE (n:KG {id: 'handler:buffered_spriteram8_device.write'}) SET n:Handler SET n += {method: 'write', ownerClass: 'buffered_spriteram8_device', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 361, sourceColumn: 2, sourceEndLine: 361};
MERGE (n:KG {id: 'map:commando_state.main_map/range9'}) SET n:AddressRange SET n += {start: 51208, end: 51209, raw: 'map(0xc808, 0xc809).w(FUNC(commando_state::scrollx_w))', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 362, sourceColumn: 2, sourceEndLine: 362};
MERGE (n:KG {id: 'handler:commando_state.scrollx_w'}) SET n:Handler SET n += {method: 'scrollx_w', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 258, sourceColumn: 1, sourceEndLine: 262, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_scroll_x[offset] = data;
	m_bg_tilemap->set_scrollx(0, m_scroll_x[0] | (m_scroll_x[1] << 8));'};
MERGE (n:KG {id: 'map:commando_state.main_map/range10'}) SET n:AddressRange SET n += {start: 51210, end: 51211, raw: 'map(0xc80a, 0xc80b).w(FUNC(commando_state::scrolly_w))', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 363, sourceColumn: 2, sourceEndLine: 363};
MERGE (n:KG {id: 'handler:commando_state.scrolly_w'}) SET n:Handler SET n += {method: 'scrolly_w', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 264, sourceColumn: 1, sourceEndLine: 268, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_scroll_y[offset] = data;
	m_bg_tilemap->set_scrolly(0, m_scroll_y[0] | (m_scroll_y[1] << 8));'};
MERGE (n:KG {id: 'map:commando_state.main_map/range11'}) SET n:AddressRange SET n += {start: 53248, end: 54271, raw: 'map(0xd000, 0xd3ff).ram().w(FUNC(commando_state::videoram_w<1>)).share(m_videoram[1])', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 364, sourceColumn: 2, sourceEndLine: 364, ram: true, share: 'videoram[1]'};
MERGE (n:KG {id: 'handler:commando_state.videoram_w_1'}) SET n:Handler SET n += {method: 'videoram_w_1', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 245, sourceColumn: 1, sourceEndLine: 249, sourceConstants: ['Which=1'], sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_videoram[Which][offset] = data;
	Which ? m_fg_tilemap->mark_tile_dirty(offset) : m_bg_tilemap->mark_tile_dirty(offset);'};
MERGE (n:KG {id: 'map:commando_state.main_map/range12'}) SET n:AddressRange SET n += {start: 54272, end: 55295, raw: 'map(0xd400, 0xd7ff).ram().w(FUNC(commando_state::colorram_w<1>)).share(m_colorram[1])', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 365, sourceColumn: 2, sourceEndLine: 365, ram: true, share: 'colorram[1]'};
MERGE (n:KG {id: 'handler:commando_state.colorram_w_1'}) SET n:Handler SET n += {method: 'colorram_w_1', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 252, sourceColumn: 1, sourceEndLine: 256, sourceConstants: ['Which=1'], sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_colorram[Which][offset] = data;
	Which ? m_fg_tilemap->mark_tile_dirty(offset) : m_bg_tilemap->mark_tile_dirty(offset);'};
MERGE (n:KG {id: 'map:commando_state.main_map/range13'}) SET n:AddressRange SET n += {start: 55296, end: 56319, raw: 'map(0xd800, 0xdbff).ram().w(FUNC(commando_state::videoram_w<0>)).share(m_videoram[0])', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 366, sourceColumn: 2, sourceEndLine: 366, ram: true, share: 'videoram[0]'};
MERGE (n:KG {id: 'handler:commando_state.videoram_w_0'}) SET n:Handler SET n += {method: 'videoram_w_0', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 245, sourceColumn: 1, sourceEndLine: 249, sourceConstants: ['Which=0'], sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_videoram[Which][offset] = data;
	Which ? m_fg_tilemap->mark_tile_dirty(offset) : m_bg_tilemap->mark_tile_dirty(offset);'};
MERGE (n:KG {id: 'map:commando_state.main_map/range14'}) SET n:AddressRange SET n += {start: 56320, end: 57343, raw: 'map(0xdc00, 0xdfff).ram().w(FUNC(commando_state::colorram_w<0>)).share(m_colorram[0])', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 367, sourceColumn: 2, sourceEndLine: 367, ram: true, share: 'colorram[0]'};
MERGE (n:KG {id: 'handler:commando_state.colorram_w_0'}) SET n:Handler SET n += {method: 'colorram_w_0', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 252, sourceColumn: 1, sourceEndLine: 256, sourceConstants: ['Which=0'], sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_colorram[Which][offset] = data;
	Which ? m_fg_tilemap->mark_tile_dirty(offset) : m_bg_tilemap->mark_tile_dirty(offset);'};
MERGE (n:KG {id: 'map:commando_state.main_map/range15'}) SET n:AddressRange SET n += {start: 57344, end: 65023, raw: 'map(0xe000, 0xfdff).ram()', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 368, sourceColumn: 2, sourceEndLine: 368, ram: true};
MERGE (n:KG {id: 'map:commando_state.main_map/range16'}) SET n:AddressRange SET n += {start: 65024, end: 65407, raw: 'map(0xfe00, 0xff7f).ram().share("spriteram")', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 369, sourceColumn: 2, sourceEndLine: 369, ram: true, share: 'spriteram'};
MERGE (n:KG {id: 'map:commando_state.main_map/range17'}) SET n:AddressRange SET n += {start: 65408, end: 65535, raw: 'map(0xff80, 0xffff).ram()', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 370, sourceColumn: 2, sourceEndLine: 370, ram: true};
MERGE (n:KG {id: 'map:commando_state.decrypted_opcodes_map'}) SET n:AddressMap SET n += {cls: 'commando_state', name: 'decrypted_opcodes_map', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 373, sourceColumn: 1, sourceEndLine: 376};
MERGE (n:KG {id: 'map:commando_state.decrypted_opcodes_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 49151, raw: 'map(0x0000, 0xbfff).rom().share(m_decrypted_opcodes)', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 375, sourceColumn: 2, sourceEndLine: 375, rom: true, share: 'decrypted_opcodes'};
MERGE (n:KG {id: 'map:commando_state.sound_map'}) SET n:AddressMap SET n += {cls: 'commando_state', name: 'sound_map', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 378, sourceColumn: 1, sourceEndLine: 385};
MERGE (n:KG {id: 'map:commando_state.sound_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 16383, raw: 'map(0x0000, 0x3fff).rom()', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 380, sourceColumn: 2, sourceEndLine: 380, rom: true};
MERGE (n:KG {id: 'map:commando_state.sound_map/range1'}) SET n:AddressRange SET n += {start: 16384, end: 18431, raw: 'map(0x4000, 0x47ff).ram()', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 381, sourceColumn: 2, sourceEndLine: 381, ram: true};
MERGE (n:KG {id: 'map:commando_state.sound_map/range2'}) SET n:AddressRange SET n += {start: 24576, end: 24576, raw: 'map(0x6000, 0x6000).r("soundlatch", FUNC(generic_latch_8_device::read))', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 382, sourceColumn: 2, sourceEndLine: 382};
MERGE (n:KG {id: 'handler:generic_latch_8_device.read'}) SET n:Handler SET n += {method: 'read', ownerClass: 'generic_latch_8_device', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 382, sourceColumn: 2, sourceEndLine: 382};
MERGE (n:KG {id: 'map:commando_state.sound_map/range3'}) SET n:AddressRange SET n += {start: 32768, end: 32769, raw: 'map(0x8000, 0x8001).w("ym1", FUNC(ym2203_device::write))', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 383, sourceColumn: 2, sourceEndLine: 383};
MERGE (n:KG {id: 'handler:ym2203_device.write'}) SET n:Handler SET n += {method: 'write', ownerClass: 'ym2203_device', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 384, sourceColumn: 2, sourceEndLine: 384};
MERGE (n:KG {id: 'map:commando_state.sound_map/range4'}) SET n:AddressRange SET n += {start: 32770, end: 32771, raw: 'map(0x8002, 0x8003).w("ym2", FUNC(ym2203_device::write))', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 384, sourceColumn: 2, sourceEndLine: 384};
MERGE (n:KG {id: 'machine:commando_state.commando'}) SET n:MachineConfig SET n += {cls: 'commando_state', name: 'commando', calls: [], resetHandlers: ['commando_state.machine_reset'], startHandlers: ['commando_state.video_start'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 552, sourceColumn: 1, sourceEndLine: 588};
MERGE (n:KG {id: 'handler:commando_state.machine_reset'}) SET n:Handler SET n += {method: 'machine_reset', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 543, sourceColumn: 1, sourceEndLine: 549, sourceParameters: '', sourceBody: 'm_scroll_x[0] = 0;
	m_scroll_x[1] = 0;
	m_scroll_y[0] = 0;
	m_scroll_y[1] = 0;'};
MERGE (n:KG {id: 'handler:commando_state.video_start'}) SET n:Handler SET n += {method: 'video_start', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 303, sourceColumn: 1, sourceEndLine: 309, sourceParameters: '', sourceBody: 'm_bg_tilemap = &machine().tilemap().create(*m_gfxdecode, tilemap_get_info_delegate(*this, FUNC(commando_state::get_bg_tile_info)), TILEMAP_SCAN_COLS, 16, 16, 32, 32);
	m_fg_tilemap = &machine().tilemap().create(*m_gfxdecode, tilemap_get_info_delegate(*this, FUNC(commando_state::get_fg_tile_info)), TILEMAP_SCAN_ROWS, 8, 8, 32, 32);

	m_fg_tilemap->set_transparent_pen(3);'};
MERGE (n:KG {id: 'handler:commando_state.get_bg_tile_info'}) SET n:Handler SET n += {method: 'get_bg_tile_info', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 283, sourceColumn: 1, sourceEndLine: 291, sourceParameters: 'tilemap_t &tilemap, tile_data &tileinfo, tilemap_memory_index tile_index', sourceBody: 'int const attr = m_colorram[0][tile_index];
	int const code = m_videoram[0][tile_index] + ((attr & 0xc0) << 2);
	int const color = attr & 0x0f;
	int const flags = TILE_FLIPYX((attr & 0x30) >> 4);

	tileinfo.set(1, code, color, flags);'};
MERGE (n:KG {id: 'handler:commando_state.get_fg_tile_info'}) SET n:Handler SET n += {method: 'get_fg_tile_info', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 293, sourceColumn: 1, sourceEndLine: 301, sourceParameters: 'tilemap_t &tilemap, tile_data &tileinfo, tilemap_memory_index tile_index', sourceBody: 'int const attr = m_colorram[1][tile_index];
	int const code = m_videoram[1][tile_index] + ((attr & 0xc0) << 2);
	int const color = attr & 0x0f;
	int const flags = TILE_FLIPYX((attr & 0x30) >> 4);

	tileinfo.set(0, code, color, flags);'};
MERGE (n:KG {id: 'device:commando_state.commando/maincpu'}) SET n:Device SET n += {type: 'Z80', tag: 'maincpu', clock: 3000000, config: ['Z80(config, m_maincpu, PHI_MAIN)', 'm_maincpu->set_addrmap(AS_PROGRAM, &commando_state::main_map)', 'm_maincpu->set_addrmap(AS_OPCODES, &commando_state::decrypted_opcodes_map)'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 561, sourceColumn: 2, sourceEndLine: 561};
MERGE (n:KG {id: 'device:commando_state.commando/audiocpu'}) SET n:Device SET n += {type: 'Z80', tag: 'audiocpu', clock: 3000000, config: ['Z80(config, m_audiocpu, PHI_B)', 'm_audiocpu->set_addrmap(AS_PROGRAM, &commando_state::sound_map)'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 565, sourceColumn: 2, sourceEndLine: 565};
MERGE (n:KG {id: 'device:commando_state.commando/scantimer'}) SET n:Device SET n += {type: 'TIMER', tag: 'scantimer', clock: null, config: ['TIMER(config, "scantimer").configure_scanline(FUNC(commando_state::scanline), "screen", 0, 1)'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 568, sourceColumn: 2, sourceEndLine: 568};
MERGE (n:KG {id: 'device:commando_state.commando/scantimer/callback:scantimer:0'}) SET n:Callback SET n += {signal: 'configure_scanline', operation: 'configure_scanline', raw: 'TIMER(config, "scantimer").configure_scanline(FUNC(commando_state::scanline), "screen", 0, 1)', ownerTag: 'scantimer', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 568, sourceColumn: 2, sourceEndLine: 568, scanlineStart: 0, scanlineIncrement: 1, targetClass: 'commando_state', targetMethod: 'scanline'};
MERGE (n:KG {id: 'handler:commando_state.scanline'}) SET n:Handler SET n += {method: 'scanline', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 519, sourceColumn: 1, sourceEndLine: 533, sourceParameters: 'int param', sourceBody: '// interrupts at scanline specified in PROM
	const int scanline = param;
	const uint8_t irq = m_irqprom[scanline & 0xff];

	// RST 08h at scanline 109 (unused)
	// RST 10h at scanline 240 (vblank)
	if (irq & 8)
		m_maincpu->set_input_line_and_vector(0, HOLD_LINE, 0xc7 | (irq << 3 & 0x18));

	// 4 audio interrupts per frame
	if (irq & 4)
		m_audiocpu->set_input_line(0, HOLD_LINE);'};
MERGE (n:KG {id: 'device:commando_state.commando/screen'}) SET n:Device SET n += {type: 'SCREEN', tag: 'screen', clock: null, config: ['screen_device &screen(SCREEN(config, "screen", SCREEN_TYPE_RASTER))', 'screen.set_raw(MAIN / 2, 384, 0, 256, 262, 16, 240)', 'screen.set_screen_update(FUNC(commando_state::screen_update))', 'screen.set_palette(m_palette)'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 571, sourceColumn: 2, sourceEndLine: 571, configCalls: ['set_raw(6000000,384,0,256,262,16,240)'], clockExpr: 'SCREEN_TYPE_RASTER', screenRaw: [6000000, 384, 0, 256, 262, 16, 240]};
MERGE (n:KG {id: 'device:commando_state.commando/screen/callback:screen:0'}) SET n:Callback SET n += {signal: 'set_screen_update', operation: 'set_screen_update', raw: 'screen.set_screen_update(FUNC(commando_state::screen_update))', ownerTag: 'screen', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 573, sourceColumn: 2, sourceEndLine: 573, targetClass: 'commando_state', targetMethod: 'screen_update'};
MERGE (n:KG {id: 'handler:commando_state.screen_update'}) SET n:Handler SET n += {method: 'screen_update', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 340, sourceColumn: 1, sourceEndLine: 346, sourceParameters: 'screen_device &screen, bitmap_ind16 &bitmap, const rectangle &cliprect', sourceBody: 'm_bg_tilemap->draw(screen, bitmap, cliprect, 0, 0);
	draw_sprites(bitmap, cliprect);
	m_fg_tilemap->draw(screen, bitmap, cliprect, 0, 0);
	return 0;'};
MERGE (n:KG {id: 'handler:commando_state.draw_sprites'}) SET n:Handler SET n += {method: 'draw_sprites', ownerClass: 'commando_state', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 311, sourceColumn: 1, sourceEndLine: 338, sourceParameters: 'bitmap_ind16 &bitmap, const rectangle &cliprect', sourceBody: 'uint8_t *spriteram = m_spriteram->buffer();

	for (int offs = m_spriteram->bytes() - 4; offs >= 0; offs -= 4)
	{
		// bit 1 of attr is not used
		int const attr = spriteram[offs + 1];
		int const bank = (attr & 0xc0) >> 6;
		int const code = spriteram[offs] + 256 * bank;
		int const color = (attr & 0x30) >> 4;
		int flipx = attr & 0x04;
		int flipy = attr & 0x08;
		int sx = spriteram[offs + 3] - ((attr & 0x01) << 8);
		int sy = spriteram[offs + 2];

		if (flip_screen())
		{
			sx = 240 - sx;
			sy = 240 - sy;
			flipx = !flipx;
			flipy = !flipy;
		}

		if (bank < 3)
			m_gfxdecode->gfx(2)->transpen(bitmap, cliprect, code, color, flipx, flipy, sx, sy, 15);
	}'};
MERGE (n:KG {id: 'device:commando_state.commando/gfxdecode'}) SET n:Device SET n += {type: 'GFXDECODE', tag: 'gfxdecode', clock: null, config: ['GFXDECODE(config, m_gfxdecode, m_palette, gfx_commando)'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 576, sourceColumn: 2, sourceEndLine: 576, clockExpr: 'm_palette'};
MERGE (n:KG {id: 'device:commando_state.commando/palette'}) SET n:Device SET n += {type: 'PALETTE', tag: 'palette', clock: null, config: ['PALETTE(config, m_palette, palette_device::RGB_444_PROMS, "proms", 256)'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 577, sourceColumn: 2, sourceEndLine: 577, clockExpr: 'palette_device::RGB_444_PROMS'};
MERGE (n:KG {id: 'device:commando_state.commando/spriteram'}) SET n:Device SET n += {type: 'BUFFERED_SPRITERAM8', tag: 'spriteram', clock: null, config: ['BUFFERED_SPRITERAM8(config, m_spriteram)'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 579, sourceColumn: 2, sourceEndLine: 579};
MERGE (n:KG {id: 'device:commando_state.commando/mono'}) SET n:Device SET n += {type: 'SPEAKER', tag: 'mono', clock: null, config: ['SPEAKER(config, "mono").front_center()'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 582, sourceColumn: 2, sourceEndLine: 582};
MERGE (n:KG {id: 'device:commando_state.commando/soundlatch'}) SET n:Device SET n += {type: 'GENERIC_LATCH_8', tag: 'soundlatch', clock: null, config: ['GENERIC_LATCH_8(config, "soundlatch")'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 584, sourceColumn: 2, sourceEndLine: 584};
MERGE (n:KG {id: 'device:commando_state.commando/ym1'}) SET n:Device SET n += {type: 'YM2203', tag: 'ym1', clock: 1500000, config: ['YM2203(config, "ym1", PHI_B / 2).add_route(ALL_OUTPUTS, "mono", 0.15)'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 586, sourceColumn: 2, sourceEndLine: 586};
MERGE (n:KG {id: 'audioroute:device:commando_state.commando/ym1/0'}) SET n:AudioRoute SET n += {output: 'ALL_OUTPUTS', target: 'mono', gain: 0.15, raw: 'YM2203(config, "ym1", PHI_B / 2).add_route(ALL_OUTPUTS, "mono", 0.15)', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 586, sourceColumn: 2, sourceEndLine: 586};
MERGE (n:KG {id: 'device:commando_state.commando/ym2'}) SET n:Device SET n += {type: 'YM2203', tag: 'ym2', clock: 1500000, config: ['YM2203(config, "ym2", PHI_B / 2).add_route(ALL_OUTPUTS, "mono", 0.15)'], sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 587, sourceColumn: 2, sourceEndLine: 587};
MERGE (n:KG {id: 'audioroute:device:commando_state.commando/ym2/0'}) SET n:AudioRoute SET n += {output: 'ALL_OUTPUTS', target: 'mono', gain: 0.15, raw: 'YM2203(config, "ym2", PHI_B / 2).add_route(ALL_OUTPUTS, "mono", 0.15)', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 587, sourceColumn: 2, sourceEndLine: 587};
MERGE (n:KG {id: 'inputs:commando'}) SET n:InputPorts SET n += {name: 'commando', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 389, sourceColumn: 8, sourceEndLine: 389};
MERGE (n:KG {id: 'inputs:commando/SYSTEM'}) SET n:Port SET n += {tag: 'SYSTEM', modify: false};
MERGE (n:KG {id: 'inputs:commando/SYSTEM/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_START1'};
MERGE (n:KG {id: 'inputs:commando/SYSTEM/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_START2'};
MERGE (n:KG {id: 'inputs:commando/SYSTEM/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 12, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:commando/SYSTEM/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 48, activeLow: true, type: 'IPT_UNKNOWN'};
MERGE (n:KG {id: 'inputs:commando/SYSTEM/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 64, activeLow: true, type: 'IPT_COIN2'};
MERGE (n:KG {id: 'inputs:commando/SYSTEM/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 128, activeLow: true, type: 'IPT_COIN1'};
MERGE (n:KG {id: 'inputs:commando/P1'}) SET n:Port SET n += {tag: 'P1', modify: false};
MERGE (n:KG {id: 'inputs:commando/P1/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_RIGHT', modifiers: ['PORT_8WAY']};
MERGE (n:KG {id: 'inputs:commando/P1/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_LEFT', modifiers: ['PORT_8WAY']};
MERGE (n:KG {id: 'inputs:commando/P1/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_DOWN', modifiers: ['PORT_8WAY']};
MERGE (n:KG {id: 'inputs:commando/P1/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_UP', modifiers: ['PORT_8WAY']};
MERGE (n:KG {id: 'inputs:commando/P1/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_BUTTON1'};
MERGE (n:KG {id: 'inputs:commando/P1/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_BUTTON2'};
MERGE (n:KG {id: 'inputs:commando/P1/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 192, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:commando/P2'}) SET n:Port SET n += {tag: 'P2', modify: false};
MERGE (n:KG {id: 'inputs:commando/P2/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_RIGHT', modifiers: ['PORT_8WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:commando/P2/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_LEFT', modifiers: ['PORT_8WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:commando/P2/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_DOWN', modifiers: ['PORT_8WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:commando/P2/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_UP', modifiers: ['PORT_8WAY', 'PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:commando/P2/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_BUTTON1', modifiers: ['PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:commando/P2/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_BUTTON2', modifiers: ['PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:commando/P2/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 192, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:commando/DSW1'}) SET n:Port SET n += {tag: 'DSW1', modify: false};
MERGE (n:KG {id: 'inputs:commando/DSW1/f0'}) SET n:PortField SET n += {kind: 'dip', mask: 3, name: 'Starting Area', defaultValue: 3, location: 'SW1:8,7', settings: ['3=0 (Forest 1)', '1=2 (Desert 1)', '2=4 (Forest 2)', '0=6 (Desert 2)']};
MERGE (n:KG {id: 'inputs:commando/DSW1/f1'}) SET n:PortField SET n += {kind: 'dip', mask: 12, name: 'Lives', defaultValue: 12, location: 'SW1:6,5', settings: ['4=2', '12=3', '8=4', '0=5']};
MERGE (n:KG {id: 'inputs:commando/DSW1/f2'}) SET n:PortField SET n += {kind: 'dip', mask: 48, name: 'Coin B', defaultValue: 48, location: 'SW1:4,3', settings: ['0=4C 1C', '32=3C 1C', '16=2C 1C', '48=1C 1C']};
MERGE (n:KG {id: 'inputs:commando/DSW1/f3'}) SET n:PortField SET n += {kind: 'dip', mask: 192, name: 'Coin A', defaultValue: 192, location: 'SW1:1,2', settings: ['0=2C 1C', '192=1C 1C', '64=1C 2C', '128=1C 3C']};
MERGE (n:KG {id: 'inputs:commando/DSW2'}) SET n:Port SET n += {tag: 'DSW2', modify: false};
MERGE (n:KG {id: 'inputs:commando/DSW2/f0'}) SET n:PortField SET n += {kind: 'dip', mask: 7, name: 'Bonus Life', defaultValue: 7, location: 'SW2:8,7,6', settings: ['7=10K 50K+', '3=10K 60K+', '5=20K 60K+', '1=20K 70K+', '6=30K 70K+', '2=30K 80K+', '4=40K 100K+', '0=None']};
MERGE (n:KG {id: 'inputs:commando/DSW2/f1'}) SET n:PortField SET n += {kind: 'dip', mask: 8, name: 'Demo Sounds', defaultValue: 8, location: 'SW2:5', settings: ['0=Off', '8=On']};
MERGE (n:KG {id: 'inputs:commando/DSW2/f2'}) SET n:PortField SET n += {kind: 'dip', mask: 16, name: 'Difficulty', defaultValue: 16, location: 'SW2:4', settings: ['16=Normal', '0=Difficult']};
MERGE (n:KG {id: 'inputs:commando/DSW2/f3'}) SET n:PortField SET n += {kind: 'dip', mask: 32, name: 'Flip Screen', defaultValue: 0, location: 'SW2:3', settings: ['0=Off', '32=On']};
MERGE (n:KG {id: 'inputs:commando/DSW2/f4'}) SET n:PortField SET n += {kind: 'dip', mask: 192, name: 'Cabinet', defaultValue: 0, location: 'SW2:2,1', settings: ['0=Upright', '64=Upright Two Players', '192=Cocktail']};
MERGE (n:KG {id: 'gfxlayout:charlayout'}) SET n:GfxLayout SET n += {name: 'charlayout', width: 8, height: 8, total: 'RGN_FRAC(1,1)', planes: 2, planeOffsets: [4, 0], xOffsets: [0, 1, 2, 3, 8, 9, 10, 11], yOffsets: [0, 16, 32, 48, 64, 80, 96, 112], charIncrement: 128};
MERGE (n:KG {id: 'gfxlayout:tilelayout'}) SET n:GfxLayout SET n += {name: 'tilelayout', width: 16, height: 16, total: 'RGN_FRAC(1,3)', planes: 3, planeOffsets: ['RGN_FRAC(0,3)', 'RGN_FRAC(1,3)', 'RGN_FRAC(2,3)'], xOffsets: [0, 1, 2, 3, 4, 5, 6, 7, 128, 129, 130, 131, 132, 133, 134, 135], yOffsets: [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120], charIncrement: 256};
MERGE (n:KG {id: 'gfxlayout:spritelayout'}) SET n:GfxLayout SET n += {name: 'spritelayout', width: 16, height: 16, total: 'RGN_FRAC(1,2)', planes: 4, planeOffsets: ['RGN_FRAC(1,2)+4', 'RGN_FRAC(1,2)+0', 4, 0], xOffsets: [0, 1, 2, 3, 8, 9, 10, 11, 256, 257, 258, 259, 264, 265, 266, 267], yOffsets: [0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240], charIncrement: 512};
MERGE (n:KG {id: 'gfxdecode:gfx_commando'}) SET n:GfxDecode SET n += {name: 'gfx_commando', sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 511, sourceColumn: 8, sourceEndLine: 511};
MERGE (n:KG {id: 'gfxdecode:gfx_commando/e0'}) SET n:GfxDecodeEntry SET n += {region: 'chars', offset: 0, layout: 'charlayout', colorBase: 192, colorCount: 16, xscale: 1, yscale: 1};
MERGE (n:KG {id: 'gfxdecode:gfx_commando/e1'}) SET n:GfxDecodeEntry SET n += {region: 'tiles', offset: 0, layout: 'tilelayout', colorBase: 0, colorCount: 16, xscale: 1, yscale: 1};
MERGE (n:KG {id: 'gfxdecode:gfx_commando/e2'}) SET n:GfxDecodeEntry SET n += {region: 'sprites', offset: 0, layout: 'spritelayout', colorBase: 128, colorCount: 4, xscale: 1, yscale: 1};
MATCH (a:KG {id: 'game:commando'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 1055, sourceColumn: 1, sourceEndLine: 1055};
MATCH (a:KG {id: 'game:commando'}), (b:KG {id: 'machine:commando_state.commando'}) MERGE (a)-[r:USES_MACHINE]->(b);
MATCH (a:KG {id: 'game:commando'}), (b:KG {id: 'inputs:commando'}) MERGE (a)-[r:USES_INPUTS]->(b);
MATCH (a:KG {id: 'game:commando'}), (b:KG {id: 'romset:commando'}) MERGE (a)-[r:USES_ROMSET]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:emu.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:cpu/z80/z80.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:machine/gen_latch.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:machine/timer.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:sound/ymopn.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:video/bufsprite.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:emupal.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:screen.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:speaker.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/capcom/commando.cpp'}), (b:KG {id: 'file:tilemap.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 552, sourceColumn: 1, sourceEndLine: 588};
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'handler:commando_state.machine_reset'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'handler:commando_state.video_start'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/maincpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/audiocpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/scantimer'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/screen'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/gfxdecode'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'gfxdecode:gfx_commando'}) MERGE (a)-[r:DECODES]->(b) SET r += {deviceTag: 'gfxdecode'};
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/palette'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/spriteram'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/mono'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/soundlatch'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/ym1'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:commando_state.commando'}), (b:KG {id: 'device:commando_state.commando/ym2'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'inputs:commando'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 389, sourceColumn: 8, sourceEndLine: 389};
MATCH (a:KG {id: 'inputs:commando'}), (b:KG {id: 'inputs:commando/SYSTEM'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:commando'}), (b:KG {id: 'inputs:commando/P1'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:commando'}), (b:KG {id: 'inputs:commando/P2'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:commando'}), (b:KG {id: 'inputs:commando/DSW1'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:commando'}), (b:KG {id: 'inputs:commando/DSW2'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'romset:commando'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 593, sourceColumn: 1, sourceEndLine: 593};
MATCH (a:KG {id: 'romset:commando'}), (b:KG {id: 'region:commando/maincpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:commando'}), (b:KG {id: 'region:commando/audiocpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:commando'}), (b:KG {id: 'region:commando/chars'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:commando'}), (b:KG {id: 'region:commando/tiles'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:commando'}), (b:KG {id: 'region:commando/sprites'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:commando'}), (b:KG {id: 'region:commando/irqprom'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:commando'}), (b:KG {id: 'region:commando/proms'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'handler:commando_state.video_start'}), (b:KG {id: 'handler:commando_state.get_bg_tile_info'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'handler:commando_state.video_start'}), (b:KG {id: 'handler:commando_state.get_fg_tile_info'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:commando_state.commando/maincpu'}), (b:KG {id: 'map:commando_state.main_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:commando_state.commando/maincpu'}), (b:KG {id: 'map:commando_state.decrypted_opcodes_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_OPCODES'};
MATCH (a:KG {id: 'device:commando_state.commando/audiocpu'}), (b:KG {id: 'map:commando_state.sound_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:commando_state.commando/scantimer'}), (b:KG {id: 'device:commando_state.commando/scantimer/callback:scantimer:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:commando_state.commando/screen'}), (b:KG {id: 'device:commando_state.commando/screen/callback:screen:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_commando'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 511, sourceColumn: 8, sourceEndLine: 511};
MATCH (a:KG {id: 'gfxdecode:gfx_commando'}), (b:KG {id: 'gfxdecode:gfx_commando/e0'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_commando'}), (b:KG {id: 'gfxdecode:gfx_commando/e1'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_commando'}), (b:KG {id: 'gfxdecode:gfx_commando/e2'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'device:commando_state.commando/ym1'}), (b:KG {id: 'audioroute:device:commando_state.commando/ym1/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:commando_state.commando/ym2'}), (b:KG {id: 'audioroute:device:commando_state.commando/ym2/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'inputs:commando/SYSTEM'}), (b:KG {id: 'inputs:commando/SYSTEM/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/SYSTEM'}), (b:KG {id: 'inputs:commando/SYSTEM/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/SYSTEM'}), (b:KG {id: 'inputs:commando/SYSTEM/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/SYSTEM'}), (b:KG {id: 'inputs:commando/SYSTEM/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/SYSTEM'}), (b:KG {id: 'inputs:commando/SYSTEM/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/SYSTEM'}), (b:KG {id: 'inputs:commando/SYSTEM/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P1'}), (b:KG {id: 'inputs:commando/P1/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P1'}), (b:KG {id: 'inputs:commando/P1/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P1'}), (b:KG {id: 'inputs:commando/P1/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P1'}), (b:KG {id: 'inputs:commando/P1/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P1'}), (b:KG {id: 'inputs:commando/P1/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P1'}), (b:KG {id: 'inputs:commando/P1/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P1'}), (b:KG {id: 'inputs:commando/P1/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P2'}), (b:KG {id: 'inputs:commando/P2/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P2'}), (b:KG {id: 'inputs:commando/P2/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P2'}), (b:KG {id: 'inputs:commando/P2/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P2'}), (b:KG {id: 'inputs:commando/P2/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P2'}), (b:KG {id: 'inputs:commando/P2/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P2'}), (b:KG {id: 'inputs:commando/P2/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/P2'}), (b:KG {id: 'inputs:commando/P2/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/DSW1'}), (b:KG {id: 'inputs:commando/DSW1/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/DSW1'}), (b:KG {id: 'inputs:commando/DSW1/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/DSW1'}), (b:KG {id: 'inputs:commando/DSW1/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/DSW1'}), (b:KG {id: 'inputs:commando/DSW1/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/DSW2'}), (b:KG {id: 'inputs:commando/DSW2/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/DSW2'}), (b:KG {id: 'inputs:commando/DSW2/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/DSW2'}), (b:KG {id: 'inputs:commando/DSW2/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/DSW2'}), (b:KG {id: 'inputs:commando/DSW2/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:commando/DSW2'}), (b:KG {id: 'inputs:commando/DSW2/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'region:commando/maincpu'}), (b:KG {id: 'rom:commando/maincpu/cm04.9m'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/maincpu'}), (b:KG {id: 'rom:commando/maincpu/cm03.8m'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/audiocpu'}), (b:KG {id: 'rom:commando/audiocpu/cm02.9f'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/chars'}), (b:KG {id: 'rom:commando/chars/vt01.5d'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/tiles'}), (b:KG {id: 'rom:commando/tiles/vt11.5a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/tiles'}), (b:KG {id: 'rom:commando/tiles/vt12.6a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/tiles'}), (b:KG {id: 'rom:commando/tiles/vt13.7a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/tiles'}), (b:KG {id: 'rom:commando/tiles/vt14.8a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/tiles'}), (b:KG {id: 'rom:commando/tiles/vt15.9a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/tiles'}), (b:KG {id: 'rom:commando/tiles/vt16.10a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/sprites'}), (b:KG {id: 'rom:commando/sprites/vt05.7e'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/sprites'}), (b:KG {id: 'rom:commando/sprites/vt06.8e'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/sprites'}), (b:KG {id: 'rom:commando/sprites/vt07.9e'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/sprites'}), (b:KG {id: 'rom:commando/sprites/vt08.7h'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/sprites'}), (b:KG {id: 'rom:commando/sprites/vt09.8h'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/sprites'}), (b:KG {id: 'rom:commando/sprites/vt10.9h'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/irqprom'}), (b:KG {id: 'rom:commando/irqprom/vtb5.6l'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/proms'}), (b:KG {id: 'rom:commando/proms/vtb1.1d'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/proms'}), (b:KG {id: 'rom:commando/proms/vtb2.2d'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/proms'}), (b:KG {id: 'rom:commando/proms/vtb3.3d'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/proms'}), (b:KG {id: 'rom:commando/proms/vtb4.1h'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:commando/proms'}), (b:KG {id: 'rom:commando/proms/vtb6.6e'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 351, sourceColumn: 1, sourceEndLine: 371};
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range5'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range6'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range7'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range8'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range9'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range10'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range11'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range12'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range13'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range14'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range15'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range16'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map'}), (b:KG {id: 'map:commando_state.main_map/range17'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.decrypted_opcodes_map'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 373, sourceColumn: 1, sourceEndLine: 376};
MATCH (a:KG {id: 'map:commando_state.decrypted_opcodes_map'}), (b:KG {id: 'map:commando_state.decrypted_opcodes_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.sound_map'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/capcom/commando.cpp', sourceLine: 378, sourceColumn: 1, sourceEndLine: 385};
MATCH (a:KG {id: 'map:commando_state.sound_map'}), (b:KG {id: 'map:commando_state.sound_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.sound_map'}), (b:KG {id: 'map:commando_state.sound_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.sound_map'}), (b:KG {id: 'map:commando_state.sound_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.sound_map'}), (b:KG {id: 'map:commando_state.sound_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:commando_state.sound_map'}), (b:KG {id: 'map:commando_state.sound_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'device:commando_state.commando/scantimer/callback:scantimer:0'}), (b:KG {id: 'handler:commando_state.scanline'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:commando_state.commando/screen/callback:screen:0'}), (b:KG {id: 'handler:commando_state.screen_update'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_commando/e0'}), (b:KG {id: 'gfxlayout:charlayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_commando/e1'}), (b:KG {id: 'gfxlayout:tilelayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_commando/e2'}), (b:KG {id: 'gfxlayout:spritelayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map/range6'}), (b:KG {id: 'handler:generic_latch_8_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'soundlatch'};
MATCH (a:KG {id: 'map:commando_state.main_map/range7'}), (b:KG {id: 'handler:commando_state.control_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map/range8'}), (b:KG {id: 'handler:buffered_spriteram8_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'spriteram'};
MATCH (a:KG {id: 'map:commando_state.main_map/range9'}), (b:KG {id: 'handler:commando_state.scrollx_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map/range10'}), (b:KG {id: 'handler:commando_state.scrolly_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map/range11'}), (b:KG {id: 'handler:commando_state.videoram_w_1'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map/range12'}), (b:KG {id: 'handler:commando_state.colorram_w_1'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map/range13'}), (b:KG {id: 'handler:commando_state.videoram_w_0'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:commando_state.main_map/range14'}), (b:KG {id: 'handler:commando_state.colorram_w_0'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:commando_state.sound_map/range2'}), (b:KG {id: 'handler:generic_latch_8_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'soundlatch'};
MATCH (a:KG {id: 'map:commando_state.sound_map/range3'}), (b:KG {id: 'handler:ym2203_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ym1'};
MATCH (a:KG {id: 'map:commando_state.sound_map/range4'}), (b:KG {id: 'handler:ym2203_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ym2'};
MATCH (a:KG {id: 'handler:commando_state.screen_update'}), (b:KG {id: 'handler:commando_state.draw_sprites'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'gfxlayout:charlayout'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
MATCH (a:KG {id: 'gfxlayout:tilelayout'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
MATCH (a:KG {id: 'gfxlayout:spritelayout'}), (b:KG {id: 'file:src/mame/capcom/commando.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
