// GENERATED by mamekit — do not edit.
import { registerGeneratedMachine } from "../runtime/core/generated-machine.js";
import { registerGeneratedBoard } from "../runtime/core/generated-board.js";
import { registerGeneratedCpu } from "../runtime/core/generated-cpu.js";
import { registerGeneratedDevice } from "../runtime/core/generated-device.js";
import device_0 from "../runtime/generated/devices/buffered_spriteram8.js";
import device_1 from "../runtime/generated/devices/er2055.js";
import device_2 from "../runtime/generated/devices/generic_latch_8.js";
import cpu_0 from "../runtime/generated/devices/i8039.js";
import cpu_1 from "../runtime/generated/devices/i8080.js";
import cpu_2 from "../runtime/generated/devices/konami1.js";
import device_3 from "../runtime/generated/devices/ls259.js";
import cpu_3 from "../runtime/generated/devices/m6803.js";
import device_4 from "../runtime/generated/devices/mb14241.js";
import device_5 from "../runtime/generated/devices/mb8844.js";
import cpu_4 from "../runtime/generated/devices/mc6809.js";
import device_6 from "../runtime/generated/devices/namco_06xx.js";
import device_7 from "../runtime/generated/devices/namco_51xx.js";
import device_8 from "../runtime/generated/devices/namco_53xx.js";
import device_9 from "../runtime/generated/devices/namco_54xx.js";
import device_10 from "../runtime/generated/devices/nes_cart_slot.js";
import device_11 from "../runtime/generated/devices/nes_control_port.js";
import device_12 from "../runtime/generated/devices/ppu_2c02.js";
import cpu_5 from "../runtime/generated/devices/rp2a03g.js";
import device_13 from "../runtime/generated/devices/starfield_05xx.js";
import cpu_6 from "../runtime/generated/devices/z80.js";
import board_0 from "../games/arcade/commando/generated/board.js";
import board_1 from "../games/arcade/digdug/generated/board.js";
import board_2 from "../games/arcade/galaga/generated/board.js";
import board_3 from "../games/arcade/galaxian/generated/board.js";
import board_4 from "../games/arcade/gng/generated/board.js";
import board_5 from "../games/arcade/gyruss/generated/board.js";
import board_6 from "../games/arcade/invaders/generated/board.js";
import board_7 from "../games/arcade/junofrst/generated/board.js";
import board_8 from "../games/arcade/kungfum/generated/board.js";
import board_9 from "../games/arcade/mpatrol/generated/board.js";
import board_10 from "../games/arcade/pacman/generated/board.js";
import board_11 from "../games/arcade/pooyan/generated/board.js";
import board_12 from "../games/arcade/rocnrope/generated/board.js";
import board_13 from "../games/arcade/timeplt/generated/board.js";
import board_14 from "../games/arcade/zigzagb/generated/board.js";
import board_15 from "../games/consoles/nes/generated/board.js";
const games = [
    { dataPath: 'games/arcade/commando', board: board_0 },
    { dataPath: 'games/arcade/digdug', board: board_1 },
    { dataPath: 'games/arcade/galaga', board: board_2 },
    { dataPath: 'games/arcade/galaxian', board: board_3 },
    { dataPath: 'games/arcade/gng', board: board_4 },
    { dataPath: 'games/arcade/gyruss', board: board_5 },
    { dataPath: 'games/arcade/invaders', board: board_6 },
    { dataPath: 'games/arcade/junofrst', board: board_7 },
    { dataPath: 'games/arcade/kungfum', board: board_8 },
    { dataPath: 'games/arcade/mpatrol', board: board_9 },
    { dataPath: 'games/arcade/pacman', board: board_10 },
    { dataPath: 'games/arcade/pooyan', board: board_11 },
    { dataPath: 'games/arcade/rocnrope', board: board_12 },
    { dataPath: 'games/arcade/timeplt', board: board_13 },
    { dataPath: 'games/arcade/zigzagb', board: board_14 },
    { dataPath: 'games/consoles/nes', board: board_15 },
];
export function registerGeneratedMachines() {
    for (const cpu of [cpu_0, cpu_1, cpu_2, cpu_3, cpu_4, cpu_5, cpu_6])
        registerGeneratedCpu(cpu);
    for (const device of [device_0, device_1, device_2, device_3, device_4, device_5, device_6, device_7, device_8, device_9, device_10, device_11, device_12, device_13])
        registerGeneratedDevice(device);
    for (const { board } of games) {
        registerGeneratedMachine(board.machine);
        registerGeneratedBoard(board.machine.game, board.createBoard);
    }
}
export function generatedGamePath(game) {
    return games.find(entry => entry.board.machine.game === game)?.dataPath;
}
