// GENERATED by mamekit — do not edit.
import { registerGeneratedMachine } from "../runtime/core/generated-machine.js";
import { registerGeneratedBoard } from "../runtime/core/generated-board.js";
import { registerGeneratedCpu } from "../runtime/core/generated-cpu.js";
import { registerGeneratedDevice } from "../runtime/core/generated-device.js";
import device_0 from "../runtime/generated/devices/adc0804.js";
import device_1 from "../runtime/generated/devices/buffered_spriteram16.js";
import device_2 from "../runtime/generated/devices/buffered_spriteram8.js";
import device_3 from "../runtime/generated/devices/coleco_expansion.js";
import device_4 from "../runtime/generated/devices/colecovision_cartridge_slot.js";
import device_5 from "../runtime/generated/devices/dmg_apu.js";
import device_6 from "../runtime/generated/devices/dmg_ppu.js";
import device_7 from "../runtime/generated/devices/er2055.js";
import device_8 from "../runtime/generated/devices/gb_cart_slot.js";
import device_9 from "../runtime/generated/devices/generic_latch_8.js";
import device_10 from "../runtime/generated/devices/hc259.js";
import cpu_0 from "../runtime/generated/devices/hd6309e.js";
import cpu_1 from "../runtime/generated/devices/hd63701y0.js";
import cpu_2 from "../runtime/generated/devices/i8035.js";
import cpu_3 from "../runtime/generated/devices/i8039.js";
import cpu_4 from "../runtime/generated/devices/i8080.js";
import cpu_5 from "../runtime/generated/devices/i8085a.js";
import cpu_6 from "../runtime/generated/devices/i8088.js";
import device_11 from "../runtime/generated/devices/i8255a.js";
import device_12 from "../runtime/generated/devices/i8257.js";
import device_13 from "../runtime/generated/devices/input_merger_all_high.js";
import device_14 from "../runtime/generated/devices/input_merger_any_high.js";
import device_15 from "../runtime/generated/devices/input_merger_any_low.js";
import device_16 from "../runtime/generated/devices/k005849.js";
import device_17 from "../runtime/generated/devices/k007232.js";
import device_18 from "../runtime/generated/devices/k051960.js";
import device_19 from "../runtime/generated/devices/k052109.js";
import device_20 from "../runtime/generated/devices/k053246.js";
import device_21 from "../runtime/generated/devices/k053251.js";
import device_22 from "../runtime/generated/devices/k053260.js";
import cpu_7 from "../runtime/generated/devices/konami.js";
import cpu_8 from "../runtime/generated/devices/konami1.js";
import device_23 from "../runtime/generated/devices/ladybug_video.js";
import device_24 from "../runtime/generated/devices/latch8.js";
import cpu_9 from "../runtime/generated/devices/lr35902.js";
import device_25 from "../runtime/generated/devices/ls157.js";
import device_26 from "../runtime/generated/devices/ls259.js";
import cpu_10 from "../runtime/generated/devices/m58715.js";
import cpu_11 from "../runtime/generated/devices/m6502.js";
import cpu_12 from "../runtime/generated/devices/m6507.js";
import cpu_13 from "../runtime/generated/devices/m68000.js";
import cpu_14 from "../runtime/generated/devices/m68010.js";
import cpu_15 from "../runtime/generated/devices/m6801u4.js";
import cpu_16 from "../runtime/generated/devices/m6802.js";
import cpu_17 from "../runtime/generated/devices/m6803.js";
import cpu_18 from "../runtime/generated/devices/m6808.js";
import device_27 from "../runtime/generated/devices/mb14241.js";
import device_28 from "../runtime/generated/devices/mb8842.js";
import device_29 from "../runtime/generated/devices/mb8843.js";
import device_30 from "../runtime/generated/devices/mb8844.js";
import cpu_19 from "../runtime/generated/devices/mb8884.js";
import cpu_20 from "../runtime/generated/devices/mc6809.js";
import cpu_21 from "../runtime/generated/devices/mc6809e.js";
import device_31 from "../runtime/generated/devices/mc6845.js";
import device_32 from "../runtime/generated/devices/mos6532.js";
import device_33 from "../runtime/generated/devices/namco_06xx.js";
import device_34 from "../runtime/generated/devices/namco_50xx.js";
import device_35 from "../runtime/generated/devices/namco_51xx.js";
import device_36 from "../runtime/generated/devices/namco_52xx.js";
import device_37 from "../runtime/generated/devices/namco_53xx.js";
import device_38 from "../runtime/generated/devices/namco_54xx.js";
import device_39 from "../runtime/generated/devices/neogeo_sprite_optimzied.js";
import device_40 from "../runtime/generated/devices/nes_cart_slot.js";
import device_41 from "../runtime/generated/devices/nes_control_port.js";
import cpu_22 from "../runtime/generated/devices/nsc8105.js";
import device_42 from "../runtime/generated/devices/output_latch.js";
import device_43 from "../runtime/generated/devices/pia6821.js";
import device_44 from "../runtime/generated/devices/pic8259.js";
import device_45 from "../runtime/generated/devices/pit8253.js";
import device_46 from "../runtime/generated/devices/ppu_2c02.js";
import cpu_23 from "../runtime/generated/devices/rp2a03g.js";
import device_47 from "../runtime/generated/devices/rst_neg_buffer.js";
import cpu_24 from "../runtime/generated/devices/sega_315_5098.js";
import cpu_25 from "../runtime/generated/devices/sega_315_5177.js";
import device_48 from "../runtime/generated/devices/segaic16vid.js";
import device_49 from "../runtime/generated/devices/slapstic.js";
import device_50 from "../runtime/generated/devices/starfield_05xx.js";
import device_51 from "../runtime/generated/devices/tecmo_sprite.js";
import device_52 from "../runtime/generated/devices/tia.js";
import device_53 from "../runtime/generated/devices/tia_ntsc_video.js";
import device_54 from "../runtime/generated/devices/tms5220c.js";
import device_55 from "../runtime/generated/devices/tms9928a.js";
import device_56 from "../runtime/generated/devices/trackfld_audio.js";
import device_57 from "../runtime/generated/devices/ttl153.js";
import device_58 from "../runtime/generated/devices/ttl74181.js";
import device_59 from "../runtime/generated/devices/upd7759.js";
import cpu_26 from "../runtime/generated/devices/v30.js";
import device_60 from "../runtime/generated/devices/vcs_cart_slot.js";
import device_61 from "../runtime/generated/devices/vcs_control_port.js";
import device_62 from "../runtime/generated/devices/williams_blitter_sc1.js";
import cpu_27 from "../runtime/generated/devices/z80.js";
import cpu_28 from "../runtime/generated/devices/z8002.js";
import device_63 from "../runtime/generated/devices/z80ctc.js";
import device_64 from "../runtime/generated/devices/z80pio.js";
import board_0 from "../games/arcade/1942/generated/board.js";
import board_1 from "../games/consoles/a2600/generated/board.js";
import board_2 from "../games/arcade/arkanoid/generated/board.js";
import board_3 from "../games/arcade/asteroid/generated/board.js";
import board_4 from "../games/arcade/bankp/generated/board.js";
import board_5 from "../games/arcade/berzerk/generated/board.js";
import board_6 from "../games/arcade/bublbobl/generated/board.js";
import board_7 from "../games/arcade/carnival/generated/board.js";
import board_8 from "../games/arcade/cavenger/generated/board.js";
import board_9 from "../games/arcade/centiped/generated/board.js";
import board_10 from "../games/consoles/coleco/generated/board.js";
import board_11 from "../games/arcade/commando/generated/board.js";
import board_12 from "../games/arcade/congo/generated/board.js";
import board_13 from "../games/arcade/crush/generated/board.js";
import board_14 from "../games/arcade/ddragon/generated/board.js";
import board_15 from "../games/arcade/defender/generated/board.js";
import board_16 from "../games/arcade/digdug/generated/board.js";
import board_17 from "../games/arcade/dkong/generated/board.js";
import board_18 from "../games/arcade/dkongjr/generated/board.js";
import board_19 from "../games/arcade/elevator/generated/board.js";
import board_20 from "../games/arcade/ffight/generated/board.js";
import board_21 from "../games/arcade/friskyt/generated/board.js";
import board_22 from "../games/arcade/frogger/generated/board.js";
import board_23 from "../games/arcade/galaga/generated/board.js";
import board_24 from "../games/arcade/galaxian/generated/board.js";
import board_25 from "../games/consoles/gameboy/generated/board.js";
import board_26 from "../games/arcade/gauntlet/generated/board.js";
import board_27 from "../games/arcade/gberet/generated/board.js";
import board_28 from "../games/arcade/ghouls/generated/board.js";
import board_29 from "../games/arcade/gng/generated/board.js";
import board_30 from "../games/arcade/gunsmoke/generated/board.js";
import board_31 from "../games/arcade/gyruss/generated/board.js";
import board_32 from "../games/arcade/invaders/generated/board.js";
import board_33 from "../games/arcade/joust/generated/board.js";
import board_34 from "../games/arcade/jumpbug/generated/board.js";
import board_35 from "../games/arcade/junglek/generated/board.js";
import board_36 from "../games/arcade/junofrst/generated/board.js";
import board_37 from "../games/arcade/kungfum/generated/board.js";
import board_38 from "../games/arcade/ladybug/generated/board.js";
import board_39 from "../games/arcade/mario/generated/board.js";
import board_40 from "../games/arcade/matmania/generated/board.js";
import board_41 from "../games/arcade/mpatrol/generated/board.js";
import board_42 from "../games/arcade/mrdo/generated/board.js";
import board_43 from "../games/arcade/mslug/generated/board.js";
import board_44 from "../games/arcade/mspacman/generated/board.js";
import board_45 from "../games/consoles/nes/generated/board.js";
import board_46 from "../games/arcade/pacman/generated/board.js";
import board_47 from "../games/arcade/panic/generated/board.js";
import board_48 from "../games/arcade/pengo/generated/board.js";
import board_49 from "../games/arcade/phoenix/generated/board.js";
import board_50 from "../games/arcade/polepos/generated/board.js";
import board_51 from "../games/arcade/pooyan/generated/board.js";
import board_52 from "../games/arcade/popeye/generated/board.js";
import board_53 from "../games/arcade/qbert/generated/board.js";
import board_54 from "../games/arcade/qix/generated/board.js";
import board_55 from "../games/arcade/rampage/generated/board.js";
import board_56 from "../games/arcade/robotron/generated/board.js";
import board_57 from "../games/arcade/rocnrope/generated/board.js";
import board_58 from "../games/arcade/rtype/generated/board.js";
import board_59 from "../games/arcade/rygar/generated/board.js";
import board_60 from "../games/arcade/scramble/generated/board.js";
import board_61 from "../games/arcade/sf2/generated/board.js";
import board_62 from "../games/arcade/sf2ce/generated/board.js";
import board_63 from "../games/arcade/shinobi/generated/board.js";
import board_64 from "../games/arcade/simpsons/generated/board.js";
import board_65 from "../games/arcade/timeplt/generated/board.js";
import board_66 from "../games/arcade/tmnt/generated/board.js";
import board_67 from "../games/arcade/trackfld/generated/board.js";
import board_68 from "../games/arcade/travrusa/generated/board.js";
import board_69 from "../games/arcade/tutankhm/generated/board.js";
import board_70 from "../games/arcade/upndown/generated/board.js";
import board_71 from "../games/arcade/venture/generated/board.js";
import board_72 from "../games/arcade/wboy/generated/board.js";
import board_73 from "../games/arcade/xevious/generated/board.js";
import board_74 from "../games/arcade/zaxxon/generated/board.js";
import board_75 from "../games/arcade/zigzagb/generated/board.js";
const games = [
    { dataPath: 'games/arcade/1942', board: board_0 },
    { dataPath: 'games/consoles/a2600', board: board_1 },
    { dataPath: 'games/arcade/arkanoid', board: board_2 },
    { dataPath: 'games/arcade/asteroid', board: board_3 },
    { dataPath: 'games/arcade/bankp', board: board_4 },
    { dataPath: 'games/arcade/berzerk', board: board_5 },
    { dataPath: 'games/arcade/bublbobl', board: board_6 },
    { dataPath: 'games/arcade/carnival', board: board_7 },
    { dataPath: 'games/arcade/cavenger', board: board_8 },
    { dataPath: 'games/arcade/centiped', board: board_9 },
    { dataPath: 'games/consoles/coleco', board: board_10 },
    { dataPath: 'games/arcade/commando', board: board_11 },
    { dataPath: 'games/arcade/congo', board: board_12 },
    { dataPath: 'games/arcade/crush', board: board_13 },
    { dataPath: 'games/arcade/ddragon', board: board_14 },
    { dataPath: 'games/arcade/defender', board: board_15 },
    { dataPath: 'games/arcade/digdug', board: board_16 },
    { dataPath: 'games/arcade/dkong', board: board_17 },
    { dataPath: 'games/arcade/dkongjr', board: board_18 },
    { dataPath: 'games/arcade/elevator', board: board_19 },
    { dataPath: 'games/arcade/ffight', board: board_20 },
    { dataPath: 'games/arcade/friskyt', board: board_21 },
    { dataPath: 'games/arcade/frogger', board: board_22 },
    { dataPath: 'games/arcade/galaga', board: board_23 },
    { dataPath: 'games/arcade/galaxian', board: board_24 },
    { dataPath: 'games/consoles/gameboy', board: board_25 },
    { dataPath: 'games/arcade/gauntlet', board: board_26 },
    { dataPath: 'games/arcade/gberet', board: board_27 },
    { dataPath: 'games/arcade/ghouls', board: board_28 },
    { dataPath: 'games/arcade/gng', board: board_29 },
    { dataPath: 'games/arcade/gunsmoke', board: board_30 },
    { dataPath: 'games/arcade/gyruss', board: board_31 },
    { dataPath: 'games/arcade/invaders', board: board_32 },
    { dataPath: 'games/arcade/joust', board: board_33 },
    { dataPath: 'games/arcade/jumpbug', board: board_34 },
    { dataPath: 'games/arcade/junglek', board: board_35 },
    { dataPath: 'games/arcade/junofrst', board: board_36 },
    { dataPath: 'games/arcade/kungfum', board: board_37 },
    { dataPath: 'games/arcade/ladybug', board: board_38 },
    { dataPath: 'games/arcade/mario', board: board_39 },
    { dataPath: 'games/arcade/matmania', board: board_40 },
    { dataPath: 'games/arcade/mpatrol', board: board_41 },
    { dataPath: 'games/arcade/mrdo', board: board_42 },
    { dataPath: 'games/arcade/mslug', board: board_43 },
    { dataPath: 'games/arcade/mspacman', board: board_44 },
    { dataPath: 'games/consoles/nes', board: board_45 },
    { dataPath: 'games/arcade/pacman', board: board_46 },
    { dataPath: 'games/arcade/panic', board: board_47 },
    { dataPath: 'games/arcade/pengo', board: board_48 },
    { dataPath: 'games/arcade/phoenix', board: board_49 },
    { dataPath: 'games/arcade/polepos', board: board_50 },
    { dataPath: 'games/arcade/pooyan', board: board_51 },
    { dataPath: 'games/arcade/popeye', board: board_52 },
    { dataPath: 'games/arcade/qbert', board: board_53 },
    { dataPath: 'games/arcade/qix', board: board_54 },
    { dataPath: 'games/arcade/rampage', board: board_55 },
    { dataPath: 'games/arcade/robotron', board: board_56 },
    { dataPath: 'games/arcade/rocnrope', board: board_57 },
    { dataPath: 'games/arcade/rtype', board: board_58 },
    { dataPath: 'games/arcade/rygar', board: board_59 },
    { dataPath: 'games/arcade/scramble', board: board_60 },
    { dataPath: 'games/arcade/sf2', board: board_61 },
    { dataPath: 'games/arcade/sf2ce', board: board_62 },
    { dataPath: 'games/arcade/shinobi', board: board_63 },
    { dataPath: 'games/arcade/simpsons', board: board_64 },
    { dataPath: 'games/arcade/timeplt', board: board_65 },
    { dataPath: 'games/arcade/tmnt', board: board_66 },
    { dataPath: 'games/arcade/trackfld', board: board_67 },
    { dataPath: 'games/arcade/travrusa', board: board_68 },
    { dataPath: 'games/arcade/tutankhm', board: board_69 },
    { dataPath: 'games/arcade/upndown', board: board_70 },
    { dataPath: 'games/arcade/venture', board: board_71 },
    { dataPath: 'games/arcade/wboy', board: board_72 },
    { dataPath: 'games/arcade/xevious', board: board_73 },
    { dataPath: 'games/arcade/zaxxon', board: board_74 },
    { dataPath: 'games/arcade/zigzagb', board: board_75 },
];
export function registerGeneratedMachines() {
    for (const cpu of [cpu_0, cpu_1, cpu_2, cpu_3, cpu_4, cpu_5, cpu_6, cpu_7, cpu_8, cpu_9, cpu_10, cpu_11, cpu_12, cpu_13, cpu_14, cpu_15, cpu_16, cpu_17, cpu_18, cpu_19, cpu_20, cpu_21, cpu_22, cpu_23, cpu_24, cpu_25, cpu_26, cpu_27, cpu_28])
        registerGeneratedCpu(cpu);
    for (const device of [device_0, device_1, device_2, device_3, device_4, device_5, device_6, device_7, device_8, device_9, device_10, device_11, device_12, device_13, device_14, device_15, device_16, device_17, device_18, device_19, device_20, device_21, device_22, device_23, device_24, device_25, device_26, device_27, device_28, device_29, device_30, device_31, device_32, device_33, device_34, device_35, device_36, device_37, device_38, device_39, device_40, device_41, device_42, device_43, device_44, device_45, device_46, device_47, device_48, device_49, device_50, device_51, device_52, device_53, device_54, device_55, device_56, device_57, device_58, device_59, device_60, device_61, device_62, device_63, device_64])
        registerGeneratedDevice(device);
    for (const { board } of games) {
        registerGeneratedMachine(board.machine);
        registerGeneratedBoard(board.machine.game, board.createBoard);
    }
}
export function generatedGamePath(game) {
    return games.find(entry => entry.board.machine.game === game)?.dataPath;
}
