// GENERATED by mamekit — do not edit.
import { registerGeneratedMachine } from "../runtime/core/generated-machine.js";
import { registerGeneratedBoard } from "../runtime/core/generated-board.js";
import { registerGeneratedCpu } from "../runtime/core/generated-cpu.js";
import { registerGeneratedDevice } from "../runtime/core/generated-device.js";
import device_0 from "../runtime/generated/devices/buffered_spriteram8.js";
import device_1 from "../runtime/generated/devices/er2055.js";
import device_2 from "../runtime/generated/devices/generic_latch_8.js";
import cpu_0 from "../runtime/generated/devices/hd6309e.js";
import cpu_1 from "../runtime/generated/devices/hd63701y0.js";
import cpu_2 from "../runtime/generated/devices/i8035.js";
import cpu_3 from "../runtime/generated/devices/i8039.js";
import cpu_4 from "../runtime/generated/devices/i8080.js";
import cpu_5 from "../runtime/generated/devices/i8085a.js";
import device_3 from "../runtime/generated/devices/i8255a.js";
import device_4 from "../runtime/generated/devices/i8257.js";
import device_5 from "../runtime/generated/devices/input_merger_all_high.js";
import device_6 from "../runtime/generated/devices/input_merger_any_high.js";
import cpu_6 from "../runtime/generated/devices/konami1.js";
import device_7 from "../runtime/generated/devices/latch8.js";
import device_8 from "../runtime/generated/devices/ls259.js";
import cpu_7 from "../runtime/generated/devices/m58715.js";
import cpu_8 from "../runtime/generated/devices/m6502.js";
import cpu_9 from "../runtime/generated/devices/m68000.js";
import cpu_10 from "../runtime/generated/devices/m6801u4.js";
import cpu_11 from "../runtime/generated/devices/m6802.js";
import cpu_12 from "../runtime/generated/devices/m6803.js";
import cpu_13 from "../runtime/generated/devices/m6808.js";
import device_9 from "../runtime/generated/devices/mb14241.js";
import device_10 from "../runtime/generated/devices/mb8843.js";
import device_11 from "../runtime/generated/devices/mb8844.js";
import cpu_14 from "../runtime/generated/devices/mb8884.js";
import cpu_15 from "../runtime/generated/devices/mc6809.js";
import cpu_16 from "../runtime/generated/devices/mc6809e.js";
import device_12 from "../runtime/generated/devices/mc6845.js";
import device_13 from "../runtime/generated/devices/mos6532.js";
import device_14 from "../runtime/generated/devices/namco_06xx.js";
import device_15 from "../runtime/generated/devices/namco_51xx.js";
import device_16 from "../runtime/generated/devices/namco_53xx.js";
import device_17 from "../runtime/generated/devices/namco_54xx.js";
import cpu_17 from "../runtime/generated/devices/nsc8105.js";
import device_18 from "../runtime/generated/devices/output_latch.js";
import device_19 from "../runtime/generated/devices/pia6821.js";
import device_20 from "../runtime/generated/devices/pit8253.js";
import device_21 from "../runtime/generated/devices/starfield_05xx.js";
import device_22 from "../runtime/generated/devices/ttl153.js";
import device_23 from "../runtime/generated/devices/ttl74181.js";
import cpu_18 from "../runtime/generated/devices/z80.js";
import device_24 from "../runtime/generated/devices/z80ctc.js";
import board_0 from "../games/arcade/1942/generated/board.js";
import board_1 from "../games/arcade/asteroid/generated/board.js";
import board_2 from "../games/arcade/bankp/generated/board.js";
import board_3 from "../games/arcade/berzerk/generated/board.js";
import board_4 from "../games/arcade/bublbobl/generated/board.js";
import board_5 from "../games/arcade/carnival/generated/board.js";
import board_6 from "../games/arcade/commando/generated/board.js";
import board_7 from "../games/arcade/crush/generated/board.js";
import board_8 from "../games/arcade/ddragon/generated/board.js";
import board_9 from "../games/arcade/defender/generated/board.js";
import board_10 from "../games/arcade/digdug/generated/board.js";
import board_11 from "../games/arcade/dkong/generated/board.js";
import board_12 from "../games/arcade/dkongjr/generated/board.js";
import board_13 from "../games/arcade/elevator/generated/board.js";
import board_14 from "../games/arcade/friskyt/generated/board.js";
import board_15 from "../games/arcade/frogger/generated/board.js";
import board_16 from "../games/arcade/galaga/generated/board.js";
import board_17 from "../games/arcade/galaxian/generated/board.js";
import board_18 from "../games/arcade/ghouls/generated/board.js";
import board_19 from "../games/arcade/gng/generated/board.js";
import board_20 from "../games/arcade/gunsmoke/generated/board.js";
import board_21 from "../games/arcade/gyruss/generated/board.js";
import board_22 from "../games/arcade/invaders/generated/board.js";
import board_23 from "../games/arcade/jumpbug/generated/board.js";
import board_24 from "../games/arcade/junglek/generated/board.js";
import board_25 from "../games/arcade/junofrst/generated/board.js";
import board_26 from "../games/arcade/kungfum/generated/board.js";
import board_27 from "../games/arcade/mario/generated/board.js";
import board_28 from "../games/arcade/matmania/generated/board.js";
import board_29 from "../games/arcade/mpatrol/generated/board.js";
import board_30 from "../games/arcade/pacman/generated/board.js";
import board_31 from "../games/arcade/panic/generated/board.js";
import board_32 from "../games/arcade/pengo/generated/board.js";
import board_33 from "../games/arcade/phoenix/generated/board.js";
import board_34 from "../games/arcade/pooyan/generated/board.js";
import board_35 from "../games/arcade/popeye/generated/board.js";
import board_36 from "../games/arcade/qix/generated/board.js";
import board_37 from "../games/arcade/rampage/generated/board.js";
import board_38 from "../games/arcade/rocnrope/generated/board.js";
import board_39 from "../games/arcade/scramble/generated/board.js";
import board_40 from "../games/arcade/sf2ce/generated/board.js";
import board_41 from "../games/arcade/timeplt/generated/board.js";
import board_42 from "../games/arcade/travrusa/generated/board.js";
import board_43 from "../games/arcade/tutankhm/generated/board.js";
import board_44 from "../games/arcade/venture/generated/board.js";
import board_45 from "../games/arcade/zaxxon/generated/board.js";
import board_46 from "../games/arcade/zigzagb/generated/board.js";
const games = [
    { dataPath: 'games/arcade/1942', board: board_0 },
    { dataPath: 'games/arcade/asteroid', board: board_1 },
    { dataPath: 'games/arcade/bankp', board: board_2 },
    { dataPath: 'games/arcade/berzerk', board: board_3 },
    { dataPath: 'games/arcade/bublbobl', board: board_4 },
    { dataPath: 'games/arcade/carnival', board: board_5 },
    { dataPath: 'games/arcade/commando', board: board_6 },
    { dataPath: 'games/arcade/crush', board: board_7 },
    { dataPath: 'games/arcade/ddragon', board: board_8 },
    { dataPath: 'games/arcade/defender', board: board_9 },
    { dataPath: 'games/arcade/digdug', board: board_10 },
    { dataPath: 'games/arcade/dkong', board: board_11 },
    { dataPath: 'games/arcade/dkongjr', board: board_12 },
    { dataPath: 'games/arcade/elevator', board: board_13 },
    { dataPath: 'games/arcade/friskyt', board: board_14 },
    { dataPath: 'games/arcade/frogger', board: board_15 },
    { dataPath: 'games/arcade/galaga', board: board_16 },
    { dataPath: 'games/arcade/galaxian', board: board_17 },
    { dataPath: 'games/arcade/ghouls', board: board_18 },
    { dataPath: 'games/arcade/gng', board: board_19 },
    { dataPath: 'games/arcade/gunsmoke', board: board_20 },
    { dataPath: 'games/arcade/gyruss', board: board_21 },
    { dataPath: 'games/arcade/invaders', board: board_22 },
    { dataPath: 'games/arcade/jumpbug', board: board_23 },
    { dataPath: 'games/arcade/junglek', board: board_24 },
    { dataPath: 'games/arcade/junofrst', board: board_25 },
    { dataPath: 'games/arcade/kungfum', board: board_26 },
    { dataPath: 'games/arcade/mario', board: board_27 },
    { dataPath: 'games/arcade/matmania', board: board_28 },
    { dataPath: 'games/arcade/mpatrol', board: board_29 },
    { dataPath: 'games/arcade/pacman', board: board_30 },
    { dataPath: 'games/arcade/panic', board: board_31 },
    { dataPath: 'games/arcade/pengo', board: board_32 },
    { dataPath: 'games/arcade/phoenix', board: board_33 },
    { dataPath: 'games/arcade/pooyan', board: board_34 },
    { dataPath: 'games/arcade/popeye', board: board_35 },
    { dataPath: 'games/arcade/qix', board: board_36 },
    { dataPath: 'games/arcade/rampage', board: board_37 },
    { dataPath: 'games/arcade/rocnrope', board: board_38 },
    { dataPath: 'games/arcade/scramble', board: board_39 },
    { dataPath: 'games/arcade/sf2ce', board: board_40 },
    { dataPath: 'games/arcade/timeplt', board: board_41 },
    { dataPath: 'games/arcade/travrusa', board: board_42 },
    { dataPath: 'games/arcade/tutankhm', board: board_43 },
    { dataPath: 'games/arcade/venture', board: board_44 },
    { dataPath: 'games/arcade/zaxxon', board: board_45 },
    { dataPath: 'games/arcade/zigzagb', board: board_46 },
];
export function registerGeneratedMachines() {
    for (const cpu of [cpu_0, cpu_1, cpu_2, cpu_3, cpu_4, cpu_5, cpu_6, cpu_7, cpu_8, cpu_9, cpu_10, cpu_11, cpu_12, cpu_13, cpu_14, cpu_15, cpu_16, cpu_17, cpu_18])
        registerGeneratedCpu(cpu);
    for (const device of [device_0, device_1, device_2, device_3, device_4, device_5, device_6, device_7, device_8, device_9, device_10, device_11, device_12, device_13, device_14, device_15, device_16, device_17, device_18, device_19, device_20, device_21, device_22, device_23, device_24])
        registerGeneratedDevice(device);
    for (const { board } of games) {
        registerGeneratedMachine(board.machine);
        registerGeneratedBoard(board.machine.game, board.createBoard);
    }
}
export function generatedGamePath(game) {
    return games.find(entry => entry.board.machine.game === game)?.dataPath;
}
