// mamekit knowledge graph — driver src/mame/konami/gyruss.cpp
// generated 2026-08-22T05:52:25.401Z
CREATE CONSTRAINT mamekit_id IF NOT EXISTS FOR (n:KG) REQUIRE n.id IS UNIQUE;
MERGE (n:KG {id: 'file:src/mame/konami/gyruss.cpp'}) SET n:SourceFile SET n += {path: 'src/mame/konami/gyruss.cpp'};
MERGE (n:KG {id: 'file:emu.h'}) SET n:SourceFile SET n += {path: 'emu.h', external: true};
MERGE (n:KG {id: 'file:konami1.h'}) SET n:SourceFile SET n += {path: 'konami1.h', external: true};
MERGE (n:KG {id: 'file:konamipt.h'}) SET n:SourceFile SET n += {path: 'konamipt.h', external: true};
MERGE (n:KG {id: 'file:cpu/m6809/m6809.h'}) SET n:SourceFile SET n += {path: 'cpu/m6809/m6809.h', external: true};
MERGE (n:KG {id: 'file:cpu/mcs48/mcs48.h'}) SET n:SourceFile SET n += {path: 'cpu/mcs48/mcs48.h', external: true};
MERGE (n:KG {id: 'file:cpu/z80/z80.h'}) SET n:SourceFile SET n += {path: 'cpu/z80/z80.h', external: true};
MERGE (n:KG {id: 'file:machine/74259.h'}) SET n:SourceFile SET n += {path: 'machine/74259.h', external: true};
MERGE (n:KG {id: 'file:machine/gen_latch.h'}) SET n:SourceFile SET n += {path: 'machine/gen_latch.h', external: true};
MERGE (n:KG {id: 'file:sound/ay8910.h'}) SET n:SourceFile SET n += {path: 'sound/ay8910.h', external: true};
MERGE (n:KG {id: 'file:sound/discrete.h'}) SET n:SourceFile SET n += {path: 'sound/discrete.h', external: true};
MERGE (n:KG {id: 'file:video/resnet.h'}) SET n:SourceFile SET n += {path: 'video/resnet.h', external: true};
MERGE (n:KG {id: 'file:emupal.h'}) SET n:SourceFile SET n += {path: 'emupal.h', external: true};
MERGE (n:KG {id: 'file:screen.h'}) SET n:SourceFile SET n += {path: 'screen.h', external: true};
MERGE (n:KG {id: 'file:speaker.h'}) SET n:SourceFile SET n += {path: 'speaker.h', external: true};
MERGE (n:KG {id: 'file:tilemap.h'}) SET n:SourceFile SET n += {path: 'tilemap.h', external: true};
MERGE (n:KG {id: 'file:logmacro.h'}) SET n:SourceFile SET n += {path: 'logmacro.h', external: true};
MERGE (n:KG {id: 'game:gyruss'}) SET n:Game SET n += {name: 'gyruss', year: '1983', company: 'Konami', fullname: 'Gyruss', monitor: 'ROT90', cls: 'gyruss_state', init: 'empty_init', flags: 'MACHINE_SUPPORTS_SAVE', kind: 'arcade', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 946, sourceColumn: 1, sourceEndLine: 946};
MERGE (n:KG {id: 'romset:gyruss'}) SET n:RomSet SET n += {name: 'gyruss', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 801, sourceColumn: 1, sourceEndLine: 801};
MERGE (n:KG {id: 'region:gyruss/maincpu'}) SET n:RomRegion SET n += {tag: 'maincpu', size: 32768, flags: '0', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 802, sourceColumn: 2, sourceEndLine: 802};
MERGE (n:KG {id: 'rom:gyruss/maincpu/gyrussk.1'}) SET n:Rom SET n += {file: 'gyrussk.1', offset: 0, size: 8192, crc: 'c673b43d', sha1: '7c464fb154bac35dd6e2f547e157addeb8798194', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 803, sourceColumn: 2, sourceEndLine: 803};
MERGE (n:KG {id: 'rom:gyruss/maincpu/gyrussk.2'}) SET n:Rom SET n += {file: 'gyrussk.2', offset: 8192, size: 8192, crc: 'a4ec03e4', sha1: '08c33ad7fcc2ad5e5787a1050284e3f8164f4618', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 804, sourceColumn: 2, sourceEndLine: 804};
MERGE (n:KG {id: 'rom:gyruss/maincpu/gyrussk.3'}) SET n:Rom SET n += {file: 'gyrussk.3', offset: 16384, size: 8192, crc: '27454a98', sha1: '030c7df225652ee20d5ef64d005eb011dc89a27d', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 805, sourceColumn: 2, sourceEndLine: 805};
MERGE (n:KG {id: 'region:gyruss/sub'}) SET n:RomRegion SET n += {tag: 'sub', size: 65536, flags: '0', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 813, sourceColumn: 2, sourceEndLine: 813};
MERGE (n:KG {id: 'rom:gyruss/sub/gyrussk.9'}) SET n:Rom SET n += {file: 'gyrussk.9', offset: 57344, size: 8192, crc: '822bf27e', sha1: '36d5bea2392a7d3476dd797dc05602705cfa23ef', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 814, sourceColumn: 2, sourceEndLine: 814};
MERGE (n:KG {id: 'region:gyruss/audiocpu'}) SET n:RomRegion SET n += {tag: 'audiocpu', size: 24576, flags: '0', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 816, sourceColumn: 2, sourceEndLine: 816};
MERGE (n:KG {id: 'rom:gyruss/audiocpu/gyrussk.1a'}) SET n:Rom SET n += {file: 'gyrussk.1a', offset: 0, size: 8192, crc: 'f4ae1c17', sha1: 'ae568c96a31d910afe30d2b7eeb9ed1ed07290e3', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 817, sourceColumn: 2, sourceEndLine: 817};
MERGE (n:KG {id: 'rom:gyruss/audiocpu/gyrussk.2a'}) SET n:Rom SET n += {file: 'gyrussk.2a', offset: 8192, size: 8192, crc: 'ba498115', sha1: '9cd1f42898cc590f39ba7cb3c975b0b3d3062eba', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 818, sourceColumn: 2, sourceEndLine: 818};
MERGE (n:KG {id: 'region:gyruss/audio2'}) SET n:RomRegion SET n += {tag: 'audio2', size: 4096, flags: '0', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 821, sourceColumn: 2, sourceEndLine: 821};
MERGE (n:KG {id: 'rom:gyruss/audio2/gyrussk.3a'}) SET n:Rom SET n += {file: 'gyrussk.3a', offset: 0, size: 4096, crc: '3f9b5dea', sha1: '6e807da02c2885b18e8cc2199f12f6be9040bf75', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 822, sourceColumn: 2, sourceEndLine: 822};
MERGE (n:KG {id: 'region:gyruss/sprites'}) SET n:RomRegion SET n += {tag: 'sprites', size: 32768, flags: '0', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 824, sourceColumn: 2, sourceEndLine: 824};
MERGE (n:KG {id: 'rom:gyruss/sprites/gyrussk.6'}) SET n:Rom SET n += {file: 'gyrussk.6', offset: 0, size: 8192, crc: 'c949db10', sha1: 'fcb8bcbd2bdd751fecb322a33c8a92fb6f07a7ab', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 825, sourceColumn: 2, sourceEndLine: 825};
MERGE (n:KG {id: 'rom:gyruss/sprites/gyrussk.5'}) SET n:Rom SET n += {file: 'gyrussk.5', offset: 8192, size: 8192, crc: '4f22411a', sha1: '763bcd039f8c1838a0d7da7d4dadc14a26e25596', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 826, sourceColumn: 2, sourceEndLine: 826};
MERGE (n:KG {id: 'rom:gyruss/sprites/gyrussk.8'}) SET n:Rom SET n += {file: 'gyrussk.8', offset: 16384, size: 8192, crc: '47cd1fbc', sha1: '8203c4ff0b1cd7b4dbc708e300bfeac1e7366e09', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 827, sourceColumn: 2, sourceEndLine: 827};
MERGE (n:KG {id: 'rom:gyruss/sprites/gyrussk.7'}) SET n:Rom SET n += {file: 'gyrussk.7', offset: 24576, size: 8192, crc: '8e8d388c', sha1: '8f2928d71c02aba977d67575d6e34d69bda2b9d4', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 828, sourceColumn: 2, sourceEndLine: 828};
MERGE (n:KG {id: 'region:gyruss/tiles'}) SET n:RomRegion SET n += {tag: 'tiles', size: 8192, flags: '0', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 830, sourceColumn: 2, sourceEndLine: 830};
MERGE (n:KG {id: 'rom:gyruss/tiles/gyrussk.4'}) SET n:Rom SET n += {file: 'gyrussk.4', offset: 0, size: 8192, crc: '27d8329b', sha1: '564ff945465a23d93a93137ad277298770dfa06a', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 810, sourceColumn: 2, sourceEndLine: 810};
MERGE (n:KG {id: 'region:gyruss/proms'}) SET n:RomRegion SET n += {tag: 'proms', size: 544, flags: '0', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 833, sourceColumn: 2, sourceEndLine: 833};
MERGE (n:KG {id: 'rom:gyruss/proms/gyrussk.pr3'}) SET n:Rom SET n += {file: 'gyrussk.pr3', offset: 0, size: 32, crc: '98782db3', sha1: 'b891e43b25187faca8002919ccb44d744daa3594', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 834, sourceColumn: 2, sourceEndLine: 834};
MERGE (n:KG {id: 'rom:gyruss/proms/gyrussk.pr1'}) SET n:Rom SET n += {file: 'gyrussk.pr1', offset: 32, size: 256, crc: '7ed057de', sha1: 'c04069ae1e2c62f9b3048844cd8cf5e1b03b7d3c', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 835, sourceColumn: 2, sourceEndLine: 835};
MERGE (n:KG {id: 'rom:gyruss/proms/gyrussk.pr2'}) SET n:Rom SET n += {file: 'gyrussk.pr2', offset: 288, size: 256, crc: 'de823a81', sha1: '1af94b2a6a319a89b238a5076a2867f1cfd279b0', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 836, sourceColumn: 2, sourceEndLine: 836};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map'}) SET n:AddressMap SET n += {cls: 'gyruss_state', name: 'main_cpu1_map', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 403, sourceColumn: 1, sourceEndLine: 417};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 32767, raw: 'map(0x0000, 0x7fff).rom()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 405, sourceColumn: 2, sourceEndLine: 405, rom: true};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range1'}) SET n:AddressRange SET n += {start: 32768, end: 33791, raw: 'map(0x8000, 0x83ff).ram().share(m_colorram)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 406, sourceColumn: 2, sourceEndLine: 406, ram: true, share: 'colorram'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range2'}) SET n:AddressRange SET n += {start: 33792, end: 34815, raw: 'map(0x8400, 0x87ff).ram().share(m_videoram)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 407, sourceColumn: 2, sourceEndLine: 407, ram: true, share: 'videoram'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range3'}) SET n:AddressRange SET n += {start: 36864, end: 40959, raw: 'map(0x9000, 0x9fff).ram()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 408, sourceColumn: 2, sourceEndLine: 408, ram: true};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range4'}) SET n:AddressRange SET n += {start: 40960, end: 43007, raw: 'map(0xa000, 0xa7ff).ram().share("main_cpus")', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 409, sourceColumn: 2, sourceEndLine: 409, ram: true, share: 'main_cpus'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range5'}) SET n:AddressRange SET n += {start: 49152, end: 49152, raw: 'map(0xc000, 0xc000).portr("DSW2").nopw()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 410, sourceColumn: 2, sourceEndLine: 410, nopw: true, portRead: 'DSW2'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range6'}) SET n:AddressRange SET n += {start: 49280, end: 49280, raw: 'map(0xc080, 0xc080).portr("SYSTEM").w(FUNC(gyruss_state::sh_irqtrigger_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 411, sourceColumn: 2, sourceEndLine: 411, portRead: 'SYSTEM'};
MERGE (n:KG {id: 'handler:gyruss_state.sh_irqtrigger_w'}) SET n:Handler SET n += {method: 'sh_irqtrigger_w', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 372, sourceColumn: 1, sourceEndLine: 376, sourceParameters: 'uint8_t data', sourceBody: '// writing to this register triggers IRQ on the sound CPU
	m_audiocpu->set_input_line(0, HOLD_LINE); // Z80 IM1'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range7'}) SET n:AddressRange SET n += {start: 49312, end: 49312, raw: 'map(0xc0a0, 0xc0a0).portr("P1")', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 412, sourceColumn: 2, sourceEndLine: 412, portRead: 'P1'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range8'}) SET n:AddressRange SET n += {start: 49344, end: 49344, raw: 'map(0xc0c0, 0xc0c0).portr("P2")', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 413, sourceColumn: 2, sourceEndLine: 413, portRead: 'P2'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range9'}) SET n:AddressRange SET n += {start: 49376, end: 49376, raw: 'map(0xc0e0, 0xc0e0).portr("DSW1")', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 414, sourceColumn: 2, sourceEndLine: 414, portRead: 'DSW1'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range10'}) SET n:AddressRange SET n += {start: 49408, end: 49408, raw: 'map(0xc100, 0xc100).portr("DSW3").w("soundlatch", FUNC(generic_latch_8_device::write))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 415, sourceColumn: 2, sourceEndLine: 415, portRead: 'DSW3'};
MERGE (n:KG {id: 'handler:generic_latch_8_device.write'}) SET n:Handler SET n += {method: 'write', ownerClass: 'generic_latch_8_device', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 456, sourceColumn: 2, sourceEndLine: 456};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu1_map/range11'}) SET n:AddressRange SET n += {start: 49536, end: 49543, raw: 'map(0xc180, 0xc187).w("mainlatch", FUNC(ls259_device::write_d0))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 416, sourceColumn: 2, sourceEndLine: 416};
MERGE (n:KG {id: 'handler:ls259_device.write_d0'}) SET n:Handler SET n += {method: 'write_d0', ownerClass: 'ls259_device', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 416, sourceColumn: 2, sourceEndLine: 416};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu2_map'}) SET n:AddressMap SET n += {cls: 'gyruss_state', name: 'main_cpu2_map', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 419, sourceColumn: 1, sourceEndLine: 428};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu2_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 0, raw: 'map(0x0000, 0x0000).r(FUNC(gyruss_state::scanline_r))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 421, sourceColumn: 2, sourceEndLine: 421};
MERGE (n:KG {id: 'handler:gyruss_state.scanline_r'}) SET n:Handler SET n += {method: 'scanline_r', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 274, sourceColumn: 1, sourceEndLine: 278, sourceParameters: '', sourceBody: '// reads 1V - 128V
	return m_screen->vpos();'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu2_map/range1'}) SET n:AddressRange SET n += {start: 8192, end: 8192, raw: 'map(0x2000, 0x2000).w(FUNC(gyruss_state::slave_irq_mask_w)).nopr()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 422, sourceColumn: 2, sourceEndLine: 422, nopr: true};
MERGE (n:KG {id: 'handler:gyruss_state.slave_irq_mask_w'}) SET n:Handler SET n += {method: 'slave_irq_mask_w', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 390, sourceColumn: 1, sourceEndLine: 395, sourceParameters: 'uint8_t data', sourceBody: 'm_slave_irq_mask = data & 1;
	if (!m_slave_irq_mask)
		m_subcpu->set_input_line(0, CLEAR_LINE);'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu2_map/range2'}) SET n:AddressRange SET n += {start: 16384, end: 16447, raw: 'map(0x4000, 0x403f).ram()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 423, sourceColumn: 2, sourceEndLine: 423, ram: true};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu2_map/range3'}) SET n:AddressRange SET n += {start: 16448, end: 16639, raw: 'map(0x4040, 0x40ff).ram().w(FUNC(gyruss_state::spriteram_w)).share(m_spriteram)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 424, sourceColumn: 2, sourceEndLine: 424, ram: true, share: 'spriteram'};
MERGE (n:KG {id: 'handler:gyruss_state.spriteram_w'}) SET n:Handler SET n += {method: 'spriteram_w', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 244, sourceColumn: 1, sourceEndLine: 248, sourceParameters: 'offs_t offset, uint8_t data', sourceBody: 'm_screen->update_partial(m_screen->vpos());
	m_spriteram[offset] = data;'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu2_map/range4'}) SET n:AddressRange SET n += {start: 16640, end: 18431, raw: 'map(0x4100, 0x47ff).ram()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 425, sourceColumn: 2, sourceEndLine: 425, ram: true};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu2_map/range5'}) SET n:AddressRange SET n += {start: 24576, end: 26623, raw: 'map(0x6000, 0x67ff).ram().share("main_cpus")', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 426, sourceColumn: 2, sourceEndLine: 426, ram: true, share: 'main_cpus'};
MERGE (n:KG {id: 'map:gyruss_state.main_cpu2_map/range6'}) SET n:AddressRange SET n += {start: 57344, end: 65535, raw: 'map(0xe000, 0xffff).rom()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 427, sourceColumn: 2, sourceEndLine: 427, rom: true};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_map'}) SET n:AddressMap SET n += {cls: 'gyruss_state', name: 'audio_cpu1_map', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 430, sourceColumn: 1, sourceEndLine: 435};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 24575, raw: 'map(0x0000, 0x5fff).rom()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 432, sourceColumn: 2, sourceEndLine: 432, rom: true};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_map/range1'}) SET n:AddressRange SET n += {start: 24576, end: 25599, raw: 'map(0x6000, 0x63ff).ram()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 433, sourceColumn: 2, sourceEndLine: 433, ram: true};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_map/range2'}) SET n:AddressRange SET n += {start: 32768, end: 32768, raw: 'map(0x8000, 0x8000).r("soundlatch", FUNC(generic_latch_8_device::read))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 434, sourceColumn: 2, sourceEndLine: 434};
MERGE (n:KG {id: 'handler:generic_latch_8_device.read'}) SET n:Handler SET n += {method: 'read', ownerClass: 'generic_latch_8_device', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 466, sourceColumn: 2, sourceEndLine: 466};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}) SET n:AddressMap SET n += {cls: 'gyruss_state', name: 'audio_cpu1_io_map', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 437, sourceColumn: 1, sourceEndLine: 457, globalMask: 255};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 0, raw: 'map(0x00, 0x00).w("ay1", FUNC(ay8910_device::address_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 440, sourceColumn: 2, sourceEndLine: 440};
MERGE (n:KG {id: 'handler:ay8910_device.address_w'}) SET n:Handler SET n += {method: 'address_w', ownerClass: 'ay8910_device', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 452, sourceColumn: 2, sourceEndLine: 452};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range1'}) SET n:AddressRange SET n += {start: 1, end: 1, raw: 'map(0x01, 0x01).r("ay1", FUNC(ay8910_device::data_r))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 441, sourceColumn: 2, sourceEndLine: 441};
MERGE (n:KG {id: 'handler:ay8910_device.data_r'}) SET n:Handler SET n += {method: 'data_r', ownerClass: 'ay8910_device', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 453, sourceColumn: 2, sourceEndLine: 453};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range2'}) SET n:AddressRange SET n += {start: 2, end: 2, raw: 'map(0x02, 0x02).w("ay1", FUNC(ay8910_device::data_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 442, sourceColumn: 2, sourceEndLine: 442};
MERGE (n:KG {id: 'handler:ay8910_device.data_w'}) SET n:Handler SET n += {method: 'data_w', ownerClass: 'ay8910_device', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 454, sourceColumn: 2, sourceEndLine: 454};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range3'}) SET n:AddressRange SET n += {start: 4, end: 4, raw: 'map(0x04, 0x04).w("ay2", FUNC(ay8910_device::address_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 443, sourceColumn: 2, sourceEndLine: 443};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range4'}) SET n:AddressRange SET n += {start: 5, end: 5, raw: 'map(0x05, 0x05).r("ay2", FUNC(ay8910_device::data_r))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 444, sourceColumn: 2, sourceEndLine: 444};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range5'}) SET n:AddressRange SET n += {start: 6, end: 6, raw: 'map(0x06, 0x06).w("ay2", FUNC(ay8910_device::data_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 445, sourceColumn: 2, sourceEndLine: 445};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range6'}) SET n:AddressRange SET n += {start: 8, end: 8, raw: 'map(0x08, 0x08).w("ay3", FUNC(ay8910_device::address_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 446, sourceColumn: 2, sourceEndLine: 446};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range7'}) SET n:AddressRange SET n += {start: 9, end: 9, raw: 'map(0x09, 0x09).r("ay3", FUNC(ay8910_device::data_r))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 447, sourceColumn: 2, sourceEndLine: 447};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range8'}) SET n:AddressRange SET n += {start: 10, end: 10, raw: 'map(0x0a, 0x0a).w("ay3", FUNC(ay8910_device::data_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 448, sourceColumn: 2, sourceEndLine: 448};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range9'}) SET n:AddressRange SET n += {start: 12, end: 12, raw: 'map(0x0c, 0x0c).w("ay4", FUNC(ay8910_device::address_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 449, sourceColumn: 2, sourceEndLine: 449};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range10'}) SET n:AddressRange SET n += {start: 13, end: 13, raw: 'map(0x0d, 0x0d).r("ay4", FUNC(ay8910_device::data_r))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 450, sourceColumn: 2, sourceEndLine: 450};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range11'}) SET n:AddressRange SET n += {start: 14, end: 14, raw: 'map(0x0e, 0x0e).w("ay4", FUNC(ay8910_device::data_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 451, sourceColumn: 2, sourceEndLine: 451};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range12'}) SET n:AddressRange SET n += {start: 16, end: 16, raw: 'map(0x10, 0x10).w("ay5", FUNC(ay8910_device::address_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 452, sourceColumn: 2, sourceEndLine: 452};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range13'}) SET n:AddressRange SET n += {start: 17, end: 17, raw: 'map(0x11, 0x11).r("ay5", FUNC(ay8910_device::data_r))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 453, sourceColumn: 2, sourceEndLine: 453};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range14'}) SET n:AddressRange SET n += {start: 18, end: 18, raw: 'map(0x12, 0x12).w("ay5", FUNC(ay8910_device::data_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 454, sourceColumn: 2, sourceEndLine: 454};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range15'}) SET n:AddressRange SET n += {start: 20, end: 20, raw: 'map(0x14, 0x14).w(FUNC(gyruss_state::i8039_irq_w))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 455, sourceColumn: 2, sourceEndLine: 455};
MERGE (n:KG {id: 'handler:gyruss_state.i8039_irq_w'}) SET n:Handler SET n += {method: 'i8039_irq_w', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 378, sourceColumn: 1, sourceEndLine: 381, sourceParameters: 'uint8_t data', sourceBody: 'm_audiocpu_2->set_input_line(0, ASSERT_LINE);'};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range16'}) SET n:AddressRange SET n += {start: 24, end: 24, raw: 'map(0x18, 0x18).w("soundlatch2", FUNC(generic_latch_8_device::write))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 456, sourceColumn: 2, sourceEndLine: 456};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu2_map'}) SET n:AddressMap SET n += {cls: 'gyruss_state', name: 'audio_cpu2_map', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 459, sourceColumn: 1, sourceEndLine: 462};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu2_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 4095, raw: 'map(0x0000, 0x0fff).rom()', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 461, sourceColumn: 2, sourceEndLine: 461, rom: true};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu2_io_map'}) SET n:AddressMap SET n += {cls: 'gyruss_state', name: 'audio_cpu2_io_map', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 464, sourceColumn: 1, sourceEndLine: 467};
MERGE (n:KG {id: 'map:gyruss_state.audio_cpu2_io_map/range0'}) SET n:AddressRange SET n += {start: 0, end: 255, raw: 'map(0x00, 0xff).r("soundlatch2", FUNC(generic_latch_8_device::read))', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 466, sourceColumn: 2, sourceEndLine: 466};
MERGE (n:KG {id: 'machine:gyruss_state.gyruss'}) SET n:MachineConfig SET n += {cls: 'gyruss_state', name: 'gyruss', calls: [], startHandlers: ['gyruss_state.video_start'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 691, sourceColumn: 1, sourceEndLine: 791};
MERGE (n:KG {id: 'handler:gyruss_state.video_start'}) SET n:Handler SET n += {method: 'video_start', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 263, sourceColumn: 1, sourceEndLine: 270, sourceParameters: '', sourceBody: 'm_tilemap = &machine().tilemap().create(*m_gfxdecode, tilemap_get_info_delegate(*this, FUNC(gyruss_state::get_tile_info)), TILEMAP_SCAN_ROWS, 8, 8, 32, 32);
	m_tilemap->set_transmask(0, 0x00, 0); // opaque
	m_tilemap->set_transmask(1, 0x0f, 0); // transparent

	save_item(NAME(m_flipscreen));'};
MERGE (n:KG {id: 'handler:gyruss_state.get_tile_info'}) SET n:Handler SET n += {method: 'get_tile_info', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 251, sourceColumn: 1, sourceEndLine: 260, sourceParameters: 'tilemap_t &tilemap, tile_data &tileinfo, tilemap_memory_index tile_index', sourceBody: 'int const code = ((m_colorram[tile_index] & 0x20) << 3) | m_videoram[tile_index];
	int const color = m_colorram[tile_index] & 0x0f;
	int const flags = TILE_FLIPYX(m_colorram[tile_index] >> 6);

	tileinfo.group = (m_colorram[tile_index] & 0x10) ? 0 : 1;

	tileinfo.set(2, code, color, flags);'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/maincpu'}) SET n:Device SET n += {type: 'Z80', tag: 'maincpu', clock: 3072000, config: ['Z80(config, m_maincpu, MASTER_CLOCK / 6)', 'm_maincpu->set_addrmap(AS_PROGRAM, &gyruss_state::main_cpu1_map)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 710, sourceColumn: 2, sourceEndLine: 710};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/sub'}) SET n:Device SET n += {type: 'KONAMI1', tag: 'sub', clock: 1536000, config: ['KONAMI1(config, m_subcpu, MASTER_CLOCK / 12)', 'm_subcpu->set_addrmap(AS_PROGRAM, &gyruss_state::main_cpu2_map)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 713, sourceColumn: 2, sourceEndLine: 713};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/audiocpu'}) SET n:Device SET n += {type: 'Z80', tag: 'audiocpu', clock: 3579545.25, config: ['Z80(config, m_audiocpu, SOUND_CLOCK / 4)', 'm_audiocpu->set_addrmap(AS_PROGRAM, &gyruss_state::audio_cpu1_map)', 'm_audiocpu->set_addrmap(AS_IO, &gyruss_state::audio_cpu1_io_map)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 716, sourceColumn: 2, sourceEndLine: 716};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/audio2'}) SET n:Device SET n += {type: 'I8039', tag: 'audio2', clock: 8000000, config: ['I8039(config, m_audiocpu_2, XTAL(8\'000\'000))', 'm_audiocpu_2->set_addrmap(AS_PROGRAM, &gyruss_state::audio_cpu2_map)', 'm_audiocpu_2->set_addrmap(AS_IO, &gyruss_state::audio_cpu2_io_map)', 'm_audiocpu_2->p1_out_cb().set(FUNC(gyruss_state::dac_w))', 'm_audiocpu_2->p2_out_cb().set(FUNC(gyruss_state::irq_clear_w))'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 720, sourceColumn: 2, sourceEndLine: 720};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/audio2/callback:audio2:0'}) SET n:Callback SET n += {signal: 'p1_out_cb', operation: 'set', raw: 'm_audiocpu_2->p1_out_cb().set(FUNC(gyruss_state::dac_w))', ownerTag: 'audio2', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 723, sourceColumn: 2, sourceEndLine: 723, targetClass: 'gyruss_state', targetMethod: 'dac_w'};
MERGE (n:KG {id: 'handler:gyruss_state.dac_w'}) SET n:Handler SET n += {method: 'dac_w', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 349, sourceColumn: 1, sourceEndLine: 352, sourceParameters: 'uint8_t data', sourceBody: 'm_discrete->write(NODE(16), data);'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/audio2/callback:audio2:1'}) SET n:Callback SET n += {signal: 'p2_out_cb', operation: 'set', raw: 'm_audiocpu_2->p2_out_cb().set(FUNC(gyruss_state::irq_clear_w))', ownerTag: 'audio2', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 724, sourceColumn: 2, sourceEndLine: 724, targetClass: 'gyruss_state', targetMethod: 'irq_clear_w'};
MERGE (n:KG {id: 'handler:gyruss_state.irq_clear_w'}) SET n:Handler SET n += {method: 'irq_clear_w', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 354, sourceColumn: 1, sourceEndLine: 357, sourceParameters: 'uint8_t data', sourceBody: 'm_audiocpu_2->set_input_line(0, CLEAR_LINE);'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/mainlatch'}) SET n:Device SET n += {type: 'LS259', tag: 'mainlatch', clock: null, config: ['ls259_device &mainlatch(LS259(config, "mainlatch"))', 'mainlatch.q_out_cb<0>().set(FUNC(gyruss_state::master_nmi_mask_w))', 'mainlatch.q_out_cb<2>().set(FUNC(gyruss_state::coin_counter_w<0>))', 'mainlatch.q_out_cb<3>().set(FUNC(gyruss_state::coin_counter_w<1>))', 'mainlatch.q_out_cb<5>().set(FUNC(gyruss_state::flipscreen_w))'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 728, sourceColumn: 2, sourceEndLine: 728};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:0'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set', raw: 'mainlatch.q_out_cb<0>().set(FUNC(gyruss_state::master_nmi_mask_w))', ownerTag: 'mainlatch', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 729, sourceColumn: 2, sourceEndLine: 729, slot: '0', targetClass: 'gyruss_state', targetMethod: 'master_nmi_mask_w'};
MERGE (n:KG {id: 'handler:gyruss_state.master_nmi_mask_w'}) SET n:Handler SET n += {method: 'master_nmi_mask_w', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 383, sourceColumn: 1, sourceEndLine: 388, sourceParameters: 'int state', sourceBody: 'm_master_nmi_mask = state;
	if (!m_master_nmi_mask)
		m_maincpu->set_input_line(INPUT_LINE_NMI, CLEAR_LINE);'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:1'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set', raw: 'mainlatch.q_out_cb<2>().set(FUNC(gyruss_state::coin_counter_w<0>))', ownerTag: 'mainlatch', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 730, sourceColumn: 2, sourceEndLine: 730, slot: '2', targetClass: 'gyruss_state', targetMethod: 'coin_counter_w_0'};
MERGE (n:KG {id: 'handler:gyruss_state.coin_counter_w_0'}) SET n:Handler SET n += {method: 'coin_counter_w_0', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 398, sourceColumn: 1, sourceEndLine: 401, sourceConstants: ['Which=0'], sourceParameters: 'int state', sourceBody: 'machine().bookkeeping().coin_counter_w(Which, state);'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:2'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set', raw: 'mainlatch.q_out_cb<3>().set(FUNC(gyruss_state::coin_counter_w<1>))', ownerTag: 'mainlatch', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 731, sourceColumn: 2, sourceEndLine: 731, slot: '3', targetClass: 'gyruss_state', targetMethod: 'coin_counter_w_1'};
MERGE (n:KG {id: 'handler:gyruss_state.coin_counter_w_1'}) SET n:Handler SET n += {method: 'coin_counter_w_1', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 398, sourceColumn: 1, sourceEndLine: 401, sourceConstants: ['Which=1'], sourceParameters: 'int state', sourceBody: 'machine().bookkeeping().coin_counter_w(Which, state);'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:3'}) SET n:Callback SET n += {signal: 'q_out_cb', operation: 'set', raw: 'mainlatch.q_out_cb<5>().set(FUNC(gyruss_state::flipscreen_w))', ownerTag: 'mainlatch', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 732, sourceColumn: 2, sourceEndLine: 732, slot: '5', targetClass: 'gyruss_state', targetMethod: 'flipscreen_w'};
MERGE (n:KG {id: 'handler:gyruss_state.flipscreen_w'}) SET n:Handler SET n += {method: 'flipscreen_w', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 281, sourceColumn: 1, sourceEndLine: 284, sourceParameters: 'int state', sourceBody: 'm_flipscreen = state;'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/screen'}) SET n:Device SET n += {type: 'SCREEN', tag: 'screen', clock: null, config: ['SCREEN(config, m_screen, SCREEN_TYPE_RASTER)', 'm_screen->set_raw(PIXEL_CLOCK, HTOTAL, HBEND, HBSTART, VTOTAL, VBEND, VBSTART)', 'm_screen->set_screen_update(FUNC(gyruss_state::screen_update))', 'm_screen->set_palette(m_palette)', 'm_screen->screen_vblank().set(FUNC(gyruss_state::vblank_irq))'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 735, sourceColumn: 2, sourceEndLine: 735, configCalls: ['set_raw(6144000,396,0,256,256,16,240)'], clockExpr: 'SCREEN_TYPE_RASTER', screenRaw: [6144000, 396, 0, 256, 256, 16, 240]};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/screen/callback:screen:0'}) SET n:Callback SET n += {signal: 'set_screen_update', operation: 'set_screen_update', raw: 'm_screen->set_screen_update(FUNC(gyruss_state::screen_update))', ownerTag: 'screen', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 737, sourceColumn: 2, sourceEndLine: 737, targetClass: 'gyruss_state', targetMethod: 'screen_update'};
MERGE (n:KG {id: 'handler:gyruss_state.screen_update'}) SET n:Handler SET n += {method: 'screen_update', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 305, sourceColumn: 1, sourceEndLine: 318, sourceParameters: 'screen_device &screen, bitmap_ind16 &bitmap, const rectangle &cliprect', sourceBody: 'if (cliprect.min_y == screen.visible_area().min_y)
	{
		machine().tilemap().mark_all_dirty();
		machine().tilemap().set_flip_all(m_flipscreen ? (TILEMAP_FLIPX | TILEMAP_FLIPY) : 0);
	}

	m_tilemap->draw(screen, bitmap, cliprect, TILEMAP_DRAW_OPAQUE, 0);
	draw_sprites(bitmap, cliprect);
	m_tilemap->draw(screen, bitmap, cliprect, 0, 0);

	return 0;'};
MERGE (n:KG {id: 'handler:gyruss_state.draw_sprites'}) SET n:Handler SET n += {method: 'draw_sprites', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 287, sourceColumn: 1, sourceEndLine: 302, sourceParameters: 'bitmap_ind16 &bitmap, const rectangle &cliprect', sourceBody: 'for (int offs = 0xbc; offs >= 0; offs -= 4)
	{
		int const x = m_spriteram[offs];
		int const y = 241 - m_spriteram[offs + 3];

		int const gfx_bank = m_spriteram[offs + 1] & 0x01;
		int const code = ((m_spriteram[offs + 2] & 0x20) << 2) | (m_spriteram[offs + 1] >> 1);
		int const color = m_spriteram[offs + 2] & 0x0f;
		int const flip_x = ~m_spriteram[offs + 2] & 0x40;
		int const flip_y =  m_spriteram[offs + 2] & 0x80;

		m_gfxdecode->gfx(gfx_bank)->transpen(bitmap, cliprect, code, color, flip_x, flip_y, x, y, 0);
	}'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/screen/callback:screen:1'}) SET n:Callback SET n += {signal: 'screen_vblank', operation: 'set', raw: 'm_screen->screen_vblank().set(FUNC(gyruss_state::vblank_irq))', ownerTag: 'screen', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 739, sourceColumn: 2, sourceEndLine: 739, targetClass: 'gyruss_state', targetMethod: 'vblank_irq'};
MERGE (n:KG {id: 'handler:gyruss_state.vblank_irq'}) SET n:Handler SET n += {method: 'vblank_irq', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 682, sourceColumn: 1, sourceEndLine: 689, sourceParameters: 'int state', sourceBody: 'if (state && m_master_nmi_mask)
		m_maincpu->set_input_line(INPUT_LINE_NMI, ASSERT_LINE);

	if (state && m_slave_irq_mask)
		m_subcpu->set_input_line(0, ASSERT_LINE);'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/gfxdecode'}) SET n:Device SET n += {type: 'GFXDECODE', tag: 'gfxdecode', clock: null, config: ['GFXDECODE(config, m_gfxdecode, m_palette, gfx_gyruss)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 741, sourceColumn: 2, sourceEndLine: 741, clockExpr: 'm_palette'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/palette'}) SET n:Device SET n += {type: 'PALETTE', tag: 'palette', clock: null, config: ['PALETTE(config, m_palette, FUNC(gyruss_state::palette), 16*4+16*16, 32)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 742, sourceColumn: 2, sourceEndLine: 742, clockExpr: 'FUNC(gyruss_state::palette)'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/speaker'}) SET n:Device SET n += {type: 'SPEAKER', tag: 'speaker', clock: 2, config: ['SPEAKER(config, "speaker", 2).front()'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 745, sourceColumn: 2, sourceEndLine: 745};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/soundlatch'}) SET n:Device SET n += {type: 'GENERIC_LATCH_8', tag: 'soundlatch', clock: null, config: ['GENERIC_LATCH_8(config, "soundlatch")'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 747, sourceColumn: 2, sourceEndLine: 747};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/soundlatch2'}) SET n:Device SET n += {type: 'GENERIC_LATCH_8', tag: 'soundlatch2', clock: null, config: ['GENERIC_LATCH_8(config, "soundlatch2")'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 748, sourceColumn: 2, sourceEndLine: 748};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/ay1'}) SET n:Device SET n += {type: 'AY8910', tag: 'ay1', clock: 1789772.625, config: ['ay8910_device &ay1(AY8910(config, "ay1", SOUND_CLOCK / 8))', 'ay1.set_flags(AY8910_DISCRETE_OUTPUT)', 'ay1.set_resistors_load(RES_K(3.3), RES_K(3.3), RES_K(3.3))', 'ay1.port_b_write_callback().set(FUNC(gyruss_state::filter_w<0>))', 'ay1.add_route(0, "discrete", 1.0, 0)', 'ay1.add_route(1, "discrete", 1.0, 1)', 'ay1.add_route(2, "discrete", 1.0, 2)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 750, sourceColumn: 2, sourceEndLine: 750, configCalls: ['set_flags(4)']};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay1/0'}) SET n:AudioRoute SET n += {output: '0', target: 'discrete', gain: 1, input: 0, raw: 'ay1.add_route(0, "discrete", 1.0, 0)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 754, sourceColumn: 2, sourceEndLine: 754};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay1/1'}) SET n:AudioRoute SET n += {output: '1', target: 'discrete', gain: 1, input: 1, raw: 'ay1.add_route(1, "discrete", 1.0, 1)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 755, sourceColumn: 2, sourceEndLine: 755};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay1/2'}) SET n:AudioRoute SET n += {output: '2', target: 'discrete', gain: 1, input: 2, raw: 'ay1.add_route(2, "discrete", 1.0, 2)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 756, sourceColumn: 2, sourceEndLine: 756};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/ay1/callback:ay1:0'}) SET n:Callback SET n += {signal: 'port_b_write_callback', operation: 'set', raw: 'ay1.port_b_write_callback().set(FUNC(gyruss_state::filter_w<0>))', ownerTag: 'ay1', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 753, sourceColumn: 2, sourceEndLine: 753, targetClass: 'gyruss_state', targetMethod: 'filter_w_0'};
MERGE (n:KG {id: 'handler:gyruss_state.filter_w_0'}) SET n:Handler SET n += {method: 'filter_w_0', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 360, sourceColumn: 1, sourceEndLine: 370, sourceConstants: ['Which=0'], sourceParameters: 'uint8_t data', sourceBody: 'LOGFILTER("chip %d - %02x\\n", Which, data);
	for (int i = 0; i < 3; i++)
	{
		// low bit: 47000pF = 0.047uF
		// high bit: 220000pF = 0.22uF
		m_discrete->write(NODE(3 * Which + i + 21), data & 3);
		data >>= 2;
	}'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/ay2'}) SET n:Device SET n += {type: 'AY8910', tag: 'ay2', clock: 1789772.625, config: ['ay8910_device &ay2(AY8910(config, "ay2", SOUND_CLOCK / 8))', 'ay2.set_flags(AY8910_DISCRETE_OUTPUT)', 'ay2.set_resistors_load(RES_K(3.3), RES_K(3.3), RES_K(3.3))', 'ay2.port_b_write_callback().set(FUNC(gyruss_state::filter_w<1>))', 'ay2.add_route(0, "discrete", 1.0, 3)', 'ay2.add_route(1, "discrete", 1.0, 4)', 'ay2.add_route(2, "discrete", 1.0, 5)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 758, sourceColumn: 2, sourceEndLine: 758, configCalls: ['set_flags(4)']};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay2/0'}) SET n:AudioRoute SET n += {output: '0', target: 'discrete', gain: 1, input: 3, raw: 'ay2.add_route(0, "discrete", 1.0, 3)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 762, sourceColumn: 2, sourceEndLine: 762};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay2/1'}) SET n:AudioRoute SET n += {output: '1', target: 'discrete', gain: 1, input: 4, raw: 'ay2.add_route(1, "discrete", 1.0, 4)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 763, sourceColumn: 2, sourceEndLine: 763};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay2/2'}) SET n:AudioRoute SET n += {output: '2', target: 'discrete', gain: 1, input: 5, raw: 'ay2.add_route(2, "discrete", 1.0, 5)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 764, sourceColumn: 2, sourceEndLine: 764};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/ay2/callback:ay2:0'}) SET n:Callback SET n += {signal: 'port_b_write_callback', operation: 'set', raw: 'ay2.port_b_write_callback().set(FUNC(gyruss_state::filter_w<1>))', ownerTag: 'ay2', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 761, sourceColumn: 2, sourceEndLine: 761, targetClass: 'gyruss_state', targetMethod: 'filter_w_1'};
MERGE (n:KG {id: 'handler:gyruss_state.filter_w_1'}) SET n:Handler SET n += {method: 'filter_w_1', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 360, sourceColumn: 1, sourceEndLine: 370, sourceConstants: ['Which=1'], sourceParameters: 'uint8_t data', sourceBody: 'LOGFILTER("chip %d - %02x\\n", Which, data);
	for (int i = 0; i < 3; i++)
	{
		// low bit: 47000pF = 0.047uF
		// high bit: 220000pF = 0.22uF
		m_discrete->write(NODE(3 * Which + i + 21), data & 3);
		data >>= 2;
	}'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/ay3'}) SET n:Device SET n += {type: 'AY8910', tag: 'ay3', clock: 1789772.625, config: ['ay8910_device &ay3(AY8910(config, "ay3", SOUND_CLOCK / 8))', 'ay3.set_flags(AY8910_DISCRETE_OUTPUT)', 'ay3.set_resistors_load(RES_K(3.3), RES_K(3.3), RES_K(3.3))', 'ay3.port_a_read_callback().set(FUNC(gyruss_state::porta_r))', 'ay3.add_route(0, "discrete", 1.0, 6)', 'ay3.add_route(1, "discrete", 1.0, 7)', 'ay3.add_route(2, "discrete", 1.0, 8)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 766, sourceColumn: 2, sourceEndLine: 766, configCalls: ['set_flags(4)']};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay3/0'}) SET n:AudioRoute SET n += {output: '0', target: 'discrete', gain: 1, input: 6, raw: 'ay3.add_route(0, "discrete", 1.0, 6)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 770, sourceColumn: 2, sourceEndLine: 770};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay3/1'}) SET n:AudioRoute SET n += {output: '1', target: 'discrete', gain: 1, input: 7, raw: 'ay3.add_route(1, "discrete", 1.0, 7)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 771, sourceColumn: 2, sourceEndLine: 771};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay3/2'}) SET n:AudioRoute SET n += {output: '2', target: 'discrete', gain: 1, input: 8, raw: 'ay3.add_route(2, "discrete", 1.0, 8)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 772, sourceColumn: 2, sourceEndLine: 772};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/ay3/callback:ay3:0'}) SET n:Callback SET n += {signal: 'port_a_read_callback', operation: 'set', raw: 'ay3.port_a_read_callback().set(FUNC(gyruss_state::porta_r))', ownerTag: 'ay3', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 769, sourceColumn: 2, sourceEndLine: 769, targetClass: 'gyruss_state', targetMethod: 'porta_r'};
MERGE (n:KG {id: 'handler:gyruss_state.porta_r'}) SET n:Handler SET n += {method: 'porta_r', ownerClass: 'gyruss_state', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 343, sourceColumn: 1, sourceEndLine: 346, sourceParameters: '', sourceBody: 'return TABLE((m_audiocpu->total_cycles() / 1024) % 10, 0x00, 0x01, 0x02, 0x03, 0x04, 0x09, 0x0a, 0x0b, 0x0a, 0x0d);'};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/ay4'}) SET n:Device SET n += {type: 'AY8910', tag: 'ay4', clock: 1789772.625, config: ['ay8910_device &ay4(AY8910(config, "ay4", SOUND_CLOCK / 8))', 'ay4.set_flags(AY8910_DISCRETE_OUTPUT)', 'ay4.set_resistors_load(RES_K(3.3), RES_K(3.3), RES_K(3.3))', 'ay4.add_route(0, "discrete", 1.0, 9)', 'ay4.add_route(1, "discrete", 1.0, 10)', 'ay4.add_route(2, "discrete", 1.0, 11)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 774, sourceColumn: 2, sourceEndLine: 774, configCalls: ['set_flags(4)']};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay4/0'}) SET n:AudioRoute SET n += {output: '0', target: 'discrete', gain: 1, input: 9, raw: 'ay4.add_route(0, "discrete", 1.0, 9)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 777, sourceColumn: 2, sourceEndLine: 777};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay4/1'}) SET n:AudioRoute SET n += {output: '1', target: 'discrete', gain: 1, input: 10, raw: 'ay4.add_route(1, "discrete", 1.0, 10)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 778, sourceColumn: 2, sourceEndLine: 778};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay4/2'}) SET n:AudioRoute SET n += {output: '2', target: 'discrete', gain: 1, input: 11, raw: 'ay4.add_route(2, "discrete", 1.0, 11)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 779, sourceColumn: 2, sourceEndLine: 779};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/ay5'}) SET n:Device SET n += {type: 'AY8910', tag: 'ay5', clock: 1789772.625, config: ['ay8910_device &ay5(AY8910(config, "ay5", SOUND_CLOCK / 8))', 'ay5.set_flags(AY8910_DISCRETE_OUTPUT)', 'ay5.set_resistors_load(RES_K(3.3), RES_K(3.3), RES_K(3.3))', 'ay5.add_route(0, "discrete", 1.0, 12)', 'ay5.add_route(1, "discrete", 1.0, 13)', 'ay5.add_route(2, "discrete", 1.0, 14)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 781, sourceColumn: 2, sourceEndLine: 781, configCalls: ['set_flags(4)']};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay5/0'}) SET n:AudioRoute SET n += {output: '0', target: 'discrete', gain: 1, input: 12, raw: 'ay5.add_route(0, "discrete", 1.0, 12)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 784, sourceColumn: 2, sourceEndLine: 784};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay5/1'}) SET n:AudioRoute SET n += {output: '1', target: 'discrete', gain: 1, input: 13, raw: 'ay5.add_route(1, "discrete", 1.0, 13)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 785, sourceColumn: 2, sourceEndLine: 785};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/ay5/2'}) SET n:AudioRoute SET n += {output: '2', target: 'discrete', gain: 1, input: 14, raw: 'ay5.add_route(2, "discrete", 1.0, 14)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 786, sourceColumn: 2, sourceEndLine: 786};
MERGE (n:KG {id: 'device:gyruss_state.gyruss/discrete'}) SET n:Device SET n += {type: 'DISCRETE', tag: 'discrete', clock: null, config: ['DISCRETE(config, m_discrete, sound_discrete)', 'm_discrete->add_route(0, "speaker", 1.0, 1)', 'm_discrete->add_route(1, "speaker", 1.0, 0)'], sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 788, sourceColumn: 2, sourceEndLine: 788, clockExpr: 'sound_discrete'};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/discrete/0'}) SET n:AudioRoute SET n += {output: '0', target: 'speaker', gain: 1, input: 1, raw: 'm_discrete->add_route(0, "speaker", 1.0, 1)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 789, sourceColumn: 2, sourceEndLine: 789};
MERGE (n:KG {id: 'audioroute:device:gyruss_state.gyruss/discrete/1'}) SET n:AudioRoute SET n += {output: '1', target: 'speaker', gain: 1, input: 0, raw: 'm_discrete->add_route(1, "speaker", 1.0, 0)', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 790, sourceColumn: 2, sourceEndLine: 790};
MERGE (n:KG {id: 'inputs:gyruss'}) SET n:InputPorts SET n += {name: 'gyruss', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 470, sourceColumn: 8, sourceEndLine: 470};
MERGE (n:KG {id: 'inputs:gyruss/SYSTEM'}) SET n:Port SET n += {tag: 'SYSTEM', modify: false};
MERGE (n:KG {id: 'inputs:gyruss/SYSTEM/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_COIN1'};
MERGE (n:KG {id: 'inputs:gyruss/SYSTEM/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_COIN2'};
MERGE (n:KG {id: 'inputs:gyruss/SYSTEM/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_SERVICE1'};
MERGE (n:KG {id: 'inputs:gyruss/SYSTEM/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_START1'};
MERGE (n:KG {id: 'inputs:gyruss/SYSTEM/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_START2'};
MERGE (n:KG {id: 'inputs:gyruss/SYSTEM/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 224, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:gyruss/P1'}) SET n:Port SET n += {tag: 'P1', modify: false};
MERGE (n:KG {id: 'inputs:gyruss/P1/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_LEFT'};
MERGE (n:KG {id: 'inputs:gyruss/P1/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_RIGHT'};
MERGE (n:KG {id: 'inputs:gyruss/P1/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_UP'};
MERGE (n:KG {id: 'inputs:gyruss/P1/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_DOWN'};
MERGE (n:KG {id: 'inputs:gyruss/P1/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_BUTTON1'};
MERGE (n:KG {id: 'inputs:gyruss/P1/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_UNKNOWN'};
MERGE (n:KG {id: 'inputs:gyruss/P1/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 64, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:gyruss/P1/f7'}) SET n:PortField SET n += {kind: 'bit', mask: 128, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:gyruss/P2'}) SET n:Port SET n += {tag: 'P2', modify: false};
MERGE (n:KG {id: 'inputs:gyruss/P2/f0'}) SET n:PortField SET n += {kind: 'bit', mask: 1, activeLow: true, type: 'IPT_JOYSTICK_LEFT', modifiers: ['PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gyruss/P2/f1'}) SET n:PortField SET n += {kind: 'bit', mask: 2, activeLow: true, type: 'IPT_JOYSTICK_RIGHT', modifiers: ['PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gyruss/P2/f2'}) SET n:PortField SET n += {kind: 'bit', mask: 4, activeLow: true, type: 'IPT_JOYSTICK_UP', modifiers: ['PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gyruss/P2/f3'}) SET n:PortField SET n += {kind: 'bit', mask: 8, activeLow: true, type: 'IPT_JOYSTICK_DOWN', modifiers: ['PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gyruss/P2/f4'}) SET n:PortField SET n += {kind: 'bit', mask: 16, activeLow: true, type: 'IPT_BUTTON1', modifiers: ['PORT_COCKTAIL']};
MERGE (n:KG {id: 'inputs:gyruss/P2/f5'}) SET n:PortField SET n += {kind: 'bit', mask: 32, activeLow: true, type: 'IPT_UNKNOWN'};
MERGE (n:KG {id: 'inputs:gyruss/P2/f6'}) SET n:PortField SET n += {kind: 'bit', mask: 64, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:gyruss/P2/f7'}) SET n:PortField SET n += {kind: 'bit', mask: 128, activeLow: true, type: 'IPT_UNUSED'};
MERGE (n:KG {id: 'inputs:gyruss/DSW1'}) SET n:Port SET n += {tag: 'DSW1', modify: false};
MERGE (n:KG {id: 'inputs:gyruss/DSW1/f0'}) SET n:PortField SET n += {kind: 'dip', mask: 15, name: 'Coin A', defaultValue: 15, location: '#SW1":1,2,3,4"', settings: ['2=4C 1C', '5=3C 1C', '8=2C 1C', '4=3C 2C', '1=4C 3C', '15=1C 1C', '3=3C 4C', '7=2C 3C', '14=1C 2C', '6=2C 5C', '13=1C 3C', '12=1C 4C', '11=1C 5C', '10=1C 6C', '9=1C 7C', '0=Free Play']};
MERGE (n:KG {id: 'inputs:gyruss/DSW1/f1'}) SET n:PortField SET n += {kind: 'dip', mask: 240, name: 'Coin B', defaultValue: 240, location: '#SW1":5,6,7,8"', settings: ['32=4C 1C', '80=3C 1C', '128=2C 1C', '64=3C 2C', '16=4C 3C', '240=1C 1C', '48=3C 4C', '112=2C 3C', '224=1C 2C', '96=2C 5C', '208=1C 3C', '192=1C 4C', '176=1C 5C', '160=1C 6C', '144=1C 7C', '0=Free Play']};
MERGE (n:KG {id: 'inputs:gyruss/DSW2'}) SET n:Port SET n += {tag: 'DSW2', modify: false};
MERGE (n:KG {id: 'inputs:gyruss/DSW2/f0'}) SET n:PortField SET n += {kind: 'dip', mask: 3, name: 'Lives', defaultValue: 3, location: 'SW2:1,2', settings: ['3=3', '2=4', '1=5', '0=255 (Cheat)']};
MERGE (n:KG {id: 'inputs:gyruss/DSW2/f1'}) SET n:PortField SET n += {kind: 'dip', mask: 4, name: 'Cabinet', defaultValue: 0, location: 'SW2:3', settings: ['0=Upright', '4=Cocktail']};
MERGE (n:KG {id: 'inputs:gyruss/DSW2/f2'}) SET n:PortField SET n += {kind: 'dip', mask: 8, name: 'Bonus Life', defaultValue: 8, location: 'SW2:4', settings: ['8=30k 90k 60k+', '0=40k 110k 70k+']};
MERGE (n:KG {id: 'inputs:gyruss/DSW2/f3'}) SET n:PortField SET n += {kind: 'dip', mask: 112, name: 'Difficulty', defaultValue: 48, location: 'SW2:5,6,7', settings: ['112=1 (Easiest)', '96=2', '80=3', '64=4', '48=5 (Average)', '32=6', '16=7', '0=8 (Hardest)']};
MERGE (n:KG {id: 'inputs:gyruss/DSW2/f4'}) SET n:PortField SET n += {kind: 'dip', mask: 128, name: 'Demo Sounds', defaultValue: 0, location: 'SW2:8', settings: ['128=Off', '0=On']};
MERGE (n:KG {id: 'inputs:gyruss/DSW3'}) SET n:Port SET n += {tag: 'DSW3', modify: false};
MERGE (n:KG {id: 'inputs:gyruss/DSW3/f0'}) SET n:PortField SET n += {kind: 'dip', mask: 1, name: 'Demo Music', defaultValue: 0, location: 'SW3:1', settings: ['1=Off', '0=On']};
MERGE (n:KG {id: 'inputs:gyruss/DSW3/f1'}) SET n:PortField SET n += {kind: 'dip', mask: 254, name: 'Unused'};
MERGE (n:KG {id: 'gfxlayout:charlayout'}) SET n:GfxLayout SET n += {name: 'charlayout', width: 8, height: 8, total: 512, planes: 2, planeOffsets: [4, 0], xOffsets: [0, 1, 2, 3, 64, 65, 66, 67], yOffsets: [0, 8, 16, 24, 32, 40, 48, 56], charIncrement: 128};
MERGE (n:KG {id: 'gfxlayout:spritelayout'}) SET n:GfxLayout SET n += {name: 'spritelayout', width: 8, height: 16, total: 256, planes: 4, planeOffsets: [131076, 131072, 4, 0], xOffsets: [0, 1, 2, 3, 64, 65, 66, 67], yOffsets: [0, 8, 16, 24, 32, 40, 48, 56, 256, 264, 272, 280, 288, 296, 304, 312], charIncrement: 512};
MERGE (n:KG {id: 'gfxdecode:gfx_gyruss'}) SET n:GfxDecode SET n += {name: 'gfx_gyruss', sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 577, sourceColumn: 8, sourceEndLine: 577};
MERGE (n:KG {id: 'gfxdecode:gfx_gyruss/e0'}) SET n:GfxDecodeEntry SET n += {region: 'sprites', offset: 0, layout: 'spritelayout', colorBase: 0, colorCount: 16, xscale: 1, yscale: 1};
MERGE (n:KG {id: 'gfxdecode:gfx_gyruss/e1'}) SET n:GfxDecodeEntry SET n += {region: 'sprites', offset: 16, layout: 'spritelayout', colorBase: 0, colorCount: 16, xscale: 1, yscale: 1};
MERGE (n:KG {id: 'gfxdecode:gfx_gyruss/e2'}) SET n:GfxDecodeEntry SET n += {region: 'tiles', offset: 0, layout: 'charlayout', colorBase: 256, colorCount: 16, xscale: 1, yscale: 1};
MATCH (a:KG {id: 'game:gyruss'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 946, sourceColumn: 1, sourceEndLine: 946};
MATCH (a:KG {id: 'game:gyruss'}), (b:KG {id: 'machine:gyruss_state.gyruss'}) MERGE (a)-[r:USES_MACHINE]->(b);
MATCH (a:KG {id: 'game:gyruss'}), (b:KG {id: 'inputs:gyruss'}) MERGE (a)-[r:USES_INPUTS]->(b);
MATCH (a:KG {id: 'game:gyruss'}), (b:KG {id: 'romset:gyruss'}) MERGE (a)-[r:USES_ROMSET]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:emu.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:konami1.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:konamipt.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:cpu/m6809/m6809.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:cpu/mcs48/mcs48.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:cpu/z80/z80.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:machine/74259.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:machine/gen_latch.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:sound/ay8910.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:sound/discrete.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:video/resnet.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:emupal.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:screen.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:speaker.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:tilemap.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'file:src/mame/konami/gyruss.cpp'}), (b:KG {id: 'file:logmacro.h'}) MERGE (a)-[r:INCLUDES]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 691, sourceColumn: 1, sourceEndLine: 791};
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'handler:gyruss_state.video_start'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/maincpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/sub'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/audiocpu'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/audio2'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/mainlatch'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/screen'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/gfxdecode'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'gfxdecode:gfx_gyruss'}) MERGE (a)-[r:DECODES]->(b) SET r += {deviceTag: 'gfxdecode'};
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/palette'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/speaker'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/soundlatch'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/soundlatch2'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/ay1'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/ay2'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/ay3'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/ay4'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/ay5'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'machine:gyruss_state.gyruss'}), (b:KG {id: 'device:gyruss_state.gyruss/discrete'}) MERGE (a)-[r:HAS_DEVICE]->(b);
MATCH (a:KG {id: 'inputs:gyruss'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 470, sourceColumn: 8, sourceEndLine: 470};
MATCH (a:KG {id: 'inputs:gyruss'}), (b:KG {id: 'inputs:gyruss/SYSTEM'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:gyruss'}), (b:KG {id: 'inputs:gyruss/P1'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:gyruss'}), (b:KG {id: 'inputs:gyruss/P2'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:gyruss'}), (b:KG {id: 'inputs:gyruss/DSW1'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:gyruss'}), (b:KG {id: 'inputs:gyruss/DSW2'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'inputs:gyruss'}), (b:KG {id: 'inputs:gyruss/DSW3'}) MERGE (a)-[r:HAS_PORT]->(b);
MATCH (a:KG {id: 'romset:gyruss'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 801, sourceColumn: 1, sourceEndLine: 801};
MATCH (a:KG {id: 'romset:gyruss'}), (b:KG {id: 'region:gyruss/maincpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gyruss'}), (b:KG {id: 'region:gyruss/sub'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gyruss'}), (b:KG {id: 'region:gyruss/audiocpu'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gyruss'}), (b:KG {id: 'region:gyruss/audio2'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gyruss'}), (b:KG {id: 'region:gyruss/sprites'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gyruss'}), (b:KG {id: 'region:gyruss/tiles'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'romset:gyruss'}), (b:KG {id: 'region:gyruss/proms'}) MERGE (a)-[r:HAS_REGION]->(b);
MATCH (a:KG {id: 'handler:gyruss_state.video_start'}), (b:KG {id: 'handler:gyruss_state.get_tile_info'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/maincpu'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:gyruss_state.gyruss/sub'}), (b:KG {id: 'map:gyruss_state.main_cpu2_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:gyruss_state.gyruss/audiocpu'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:gyruss_state.gyruss/audiocpu'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_IO'};
MATCH (a:KG {id: 'device:gyruss_state.gyruss/audio2'}), (b:KG {id: 'device:gyruss_state.gyruss/audio2/callback:audio2:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/audio2'}), (b:KG {id: 'device:gyruss_state.gyruss/audio2/callback:audio2:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/audio2'}), (b:KG {id: 'map:gyruss_state.audio_cpu2_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_PROGRAM'};
MATCH (a:KG {id: 'device:gyruss_state.gyruss/audio2'}), (b:KG {id: 'map:gyruss_state.audio_cpu2_io_map'}) MERGE (a)-[r:HAS_MAP]->(b) SET r += {space: 'AS_IO'};
MATCH (a:KG {id: 'device:gyruss_state.gyruss/mainlatch'}), (b:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/mainlatch'}), (b:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/mainlatch'}), (b:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:2'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/mainlatch'}), (b:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:3'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/screen'}), (b:KG {id: 'device:gyruss_state.gyruss/screen/callback:screen:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/screen'}), (b:KG {id: 'device:gyruss_state.gyruss/screen/callback:screen:1'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gyruss'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 577, sourceColumn: 8, sourceEndLine: 577};
MATCH (a:KG {id: 'gfxdecode:gfx_gyruss'}), (b:KG {id: 'gfxdecode:gfx_gyruss/e0'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gyruss'}), (b:KG {id: 'gfxdecode:gfx_gyruss/e1'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gyruss'}), (b:KG {id: 'gfxdecode:gfx_gyruss/e2'}) MERGE (a)-[r:HAS_ENTRY]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay1'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay1/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay1'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay1/1'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay1'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay1/2'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay1'}), (b:KG {id: 'device:gyruss_state.gyruss/ay1/callback:ay1:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay2'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay2/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay2'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay2/1'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay2'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay2/2'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay2'}), (b:KG {id: 'device:gyruss_state.gyruss/ay2/callback:ay2:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay3'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay3/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay3'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay3/1'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay3'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay3/2'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay3'}), (b:KG {id: 'device:gyruss_state.gyruss/ay3/callback:ay3:0'}) MERGE (a)-[r:HAS_CALLBACK]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay4'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay4/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay4'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay4/1'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay4'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay4/2'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay5'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay5/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay5'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay5/1'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay5'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/ay5/2'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/discrete'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/discrete/0'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/discrete'}), (b:KG {id: 'audioroute:device:gyruss_state.gyruss/discrete/1'}) MERGE (a)-[r:HAS_AUDIO_ROUTE]->(b);
MATCH (a:KG {id: 'inputs:gyruss/SYSTEM'}), (b:KG {id: 'inputs:gyruss/SYSTEM/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/SYSTEM'}), (b:KG {id: 'inputs:gyruss/SYSTEM/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/SYSTEM'}), (b:KG {id: 'inputs:gyruss/SYSTEM/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/SYSTEM'}), (b:KG {id: 'inputs:gyruss/SYSTEM/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/SYSTEM'}), (b:KG {id: 'inputs:gyruss/SYSTEM/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/SYSTEM'}), (b:KG {id: 'inputs:gyruss/SYSTEM/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P1'}), (b:KG {id: 'inputs:gyruss/P1/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P1'}), (b:KG {id: 'inputs:gyruss/P1/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P1'}), (b:KG {id: 'inputs:gyruss/P1/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P1'}), (b:KG {id: 'inputs:gyruss/P1/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P1'}), (b:KG {id: 'inputs:gyruss/P1/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P1'}), (b:KG {id: 'inputs:gyruss/P1/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P1'}), (b:KG {id: 'inputs:gyruss/P1/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P1'}), (b:KG {id: 'inputs:gyruss/P1/f7'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P2'}), (b:KG {id: 'inputs:gyruss/P2/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P2'}), (b:KG {id: 'inputs:gyruss/P2/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P2'}), (b:KG {id: 'inputs:gyruss/P2/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P2'}), (b:KG {id: 'inputs:gyruss/P2/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P2'}), (b:KG {id: 'inputs:gyruss/P2/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P2'}), (b:KG {id: 'inputs:gyruss/P2/f5'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P2'}), (b:KG {id: 'inputs:gyruss/P2/f6'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/P2'}), (b:KG {id: 'inputs:gyruss/P2/f7'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/DSW1'}), (b:KG {id: 'inputs:gyruss/DSW1/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/DSW1'}), (b:KG {id: 'inputs:gyruss/DSW1/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/DSW2'}), (b:KG {id: 'inputs:gyruss/DSW2/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/DSW2'}), (b:KG {id: 'inputs:gyruss/DSW2/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/DSW2'}), (b:KG {id: 'inputs:gyruss/DSW2/f2'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/DSW2'}), (b:KG {id: 'inputs:gyruss/DSW2/f3'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/DSW2'}), (b:KG {id: 'inputs:gyruss/DSW2/f4'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/DSW3'}), (b:KG {id: 'inputs:gyruss/DSW3/f0'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'inputs:gyruss/DSW3'}), (b:KG {id: 'inputs:gyruss/DSW3/f1'}) MERGE (a)-[r:HAS_FIELD]->(b);
MATCH (a:KG {id: 'region:gyruss/maincpu'}), (b:KG {id: 'rom:gyruss/maincpu/gyrussk.1'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/maincpu'}), (b:KG {id: 'rom:gyruss/maincpu/gyrussk.2'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/maincpu'}), (b:KG {id: 'rom:gyruss/maincpu/gyrussk.3'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/sub'}), (b:KG {id: 'rom:gyruss/sub/gyrussk.9'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/audiocpu'}), (b:KG {id: 'rom:gyruss/audiocpu/gyrussk.1a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/audiocpu'}), (b:KG {id: 'rom:gyruss/audiocpu/gyrussk.2a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/audio2'}), (b:KG {id: 'rom:gyruss/audio2/gyrussk.3a'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/sprites'}), (b:KG {id: 'rom:gyruss/sprites/gyrussk.6'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/sprites'}), (b:KG {id: 'rom:gyruss/sprites/gyrussk.5'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/sprites'}), (b:KG {id: 'rom:gyruss/sprites/gyrussk.8'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/sprites'}), (b:KG {id: 'rom:gyruss/sprites/gyrussk.7'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/tiles'}), (b:KG {id: 'rom:gyruss/tiles/gyrussk.4'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/proms'}), (b:KG {id: 'rom:gyruss/proms/gyrussk.pr3'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/proms'}), (b:KG {id: 'rom:gyruss/proms/gyrussk.pr1'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'region:gyruss/proms'}), (b:KG {id: 'rom:gyruss/proms/gyrussk.pr2'}) MERGE (a)-[r:LOADS]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 403, sourceColumn: 1, sourceEndLine: 417};
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range5'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range6'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range7'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range8'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range9'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range10'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map'}), (b:KG {id: 'map:gyruss_state.main_cpu1_map/range11'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 419, sourceColumn: 1, sourceEndLine: 428};
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map'}), (b:KG {id: 'map:gyruss_state.main_cpu2_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map'}), (b:KG {id: 'map:gyruss_state.main_cpu2_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map'}), (b:KG {id: 'map:gyruss_state.main_cpu2_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map'}), (b:KG {id: 'map:gyruss_state.main_cpu2_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map'}), (b:KG {id: 'map:gyruss_state.main_cpu2_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map'}), (b:KG {id: 'map:gyruss_state.main_cpu2_map/range5'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map'}), (b:KG {id: 'map:gyruss_state.main_cpu2_map/range6'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_map'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 430, sourceColumn: 1, sourceEndLine: 435};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 437, sourceColumn: 1, sourceEndLine: 457};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range1'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range2'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range3'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range4'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range5'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range6'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range7'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range8'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range9'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range10'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range11'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range12'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range13'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range14'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range15'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range16'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/audio2/callback:audio2:0'}), (b:KG {id: 'handler:gyruss_state.dac_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/audio2/callback:audio2:1'}), (b:KG {id: 'handler:gyruss_state.irq_clear_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu2_map'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 459, sourceColumn: 1, sourceEndLine: 462};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu2_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu2_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu2_io_map'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b) SET r += {sourceFile: 'src/mame/konami/gyruss.cpp', sourceLine: 464, sourceColumn: 1, sourceEndLine: 467};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu2_io_map'}), (b:KG {id: 'map:gyruss_state.audio_cpu2_io_map/range0'}) MERGE (a)-[r:HAS_RANGE]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:0'}), (b:KG {id: 'handler:gyruss_state.master_nmi_mask_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:1'}), (b:KG {id: 'handler:gyruss_state.coin_counter_w_0'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:2'}), (b:KG {id: 'handler:gyruss_state.coin_counter_w_1'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/mainlatch/callback:mainlatch:3'}), (b:KG {id: 'handler:gyruss_state.flipscreen_w'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/screen/callback:screen:0'}), (b:KG {id: 'handler:gyruss_state.screen_update'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/screen/callback:screen:1'}), (b:KG {id: 'handler:gyruss_state.vblank_irq'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gyruss/e0'}), (b:KG {id: 'gfxlayout:spritelayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gyruss/e1'}), (b:KG {id: 'gfxlayout:spritelayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'gfxdecode:gfx_gyruss/e2'}), (b:KG {id: 'gfxlayout:charlayout'}) MERGE (a)-[r:USES_LAYOUT]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay1/callback:ay1:0'}), (b:KG {id: 'handler:gyruss_state.filter_w_0'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay2/callback:ay2:0'}), (b:KG {id: 'handler:gyruss_state.filter_w_1'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'device:gyruss_state.gyruss/ay3/callback:ay3:0'}), (b:KG {id: 'handler:gyruss_state.porta_r'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map/range6'}), (b:KG {id: 'handler:gyruss_state.sh_irqtrigger_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map/range10'}), (b:KG {id: 'handler:generic_latch_8_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'soundlatch'};
MATCH (a:KG {id: 'map:gyruss_state.main_cpu1_map/range11'}), (b:KG {id: 'handler:ls259_device.write_d0'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'mainlatch'};
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map/range0'}), (b:KG {id: 'handler:gyruss_state.scanline_r'}) MERGE (a)-[r:READS]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map/range1'}), (b:KG {id: 'handler:gyruss_state.slave_irq_mask_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:gyruss_state.main_cpu2_map/range3'}), (b:KG {id: 'handler:gyruss_state.spriteram_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_map/range2'}), (b:KG {id: 'handler:generic_latch_8_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'soundlatch'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range0'}), (b:KG {id: 'handler:ay8910_device.address_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay1'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range1'}), (b:KG {id: 'handler:ay8910_device.data_r'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'ay1'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range2'}), (b:KG {id: 'handler:ay8910_device.data_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay1'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range3'}), (b:KG {id: 'handler:ay8910_device.address_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay2'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range4'}), (b:KG {id: 'handler:ay8910_device.data_r'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'ay2'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range5'}), (b:KG {id: 'handler:ay8910_device.data_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay2'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range6'}), (b:KG {id: 'handler:ay8910_device.address_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay3'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range7'}), (b:KG {id: 'handler:ay8910_device.data_r'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'ay3'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range8'}), (b:KG {id: 'handler:ay8910_device.data_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay3'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range9'}), (b:KG {id: 'handler:ay8910_device.address_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay4'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range10'}), (b:KG {id: 'handler:ay8910_device.data_r'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'ay4'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range11'}), (b:KG {id: 'handler:ay8910_device.data_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay4'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range12'}), (b:KG {id: 'handler:ay8910_device.address_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay5'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range13'}), (b:KG {id: 'handler:ay8910_device.data_r'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'ay5'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range14'}), (b:KG {id: 'handler:ay8910_device.data_w'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'ay5'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range15'}), (b:KG {id: 'handler:gyruss_state.i8039_irq_w'}) MERGE (a)-[r:WRITES]->(b);
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu1_io_map/range16'}), (b:KG {id: 'handler:generic_latch_8_device.write'}) MERGE (a)-[r:WRITES]->(b) SET r += {deviceTag: 'soundlatch2'};
MATCH (a:KG {id: 'map:gyruss_state.audio_cpu2_io_map/range0'}), (b:KG {id: 'handler:generic_latch_8_device.read'}) MERGE (a)-[r:READS]->(b) SET r += {deviceTag: 'soundlatch2'};
MATCH (a:KG {id: 'handler:gyruss_state.screen_update'}), (b:KG {id: 'handler:gyruss_state.draw_sprites'}) MERGE (a)-[r:CALLS_HANDLER]->(b);
MATCH (a:KG {id: 'gfxlayout:spritelayout'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
MATCH (a:KG {id: 'gfxlayout:charlayout'}), (b:KG {id: 'file:src/mame/konami/gyruss.cpp'}) MERGE (a)-[r:DEFINED_IN]->(b);
